{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.123.684.0 (23.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Dimension - Employee\",\"Dimension - Depo Product\",\"Dimension - SC_TP\",\"Dimension - FX\",\"Dimension - Delta Type\",\"Dimension - Loan Product\",\"Dimension - Employee Secondary\",\"Fact - Employee Hierarchy\",\"Fact - Bonus\",\"Fact - Bonus Plan\",\"Measures - Bonus Plan\",\"Fact - Employee Hierarchy Plan Bridge\",\"Measures - Bonus\",\"Measures - Employee Hierarchy\",\"Measures - Depos\",\"Measures - Home\",\"Measures - Loans\",\"Measures - General\",\"Fact - Loans\",\"Fact - Loans Hierarchy Bridge\",\"Fact - Depos Hierarchy Bridge\",\"Fact - Depos\",\"Measures - Opers\",\"Dimension - DEPO_DISB_TP\",\"Fact - Bonus Hierarchy Bridge\",\"Dimension - Currency\",\"Dimension - Role Type\",\"Dimension - Plan\",\"Dimension - Bonus Tree\",\"Update Date\",\"REPORTING\",\"Fact - Ranking  Hierarchy Bridge\",\"Fact - Ranking\",\"BI_RLS_TST\",\"Simulation\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Employee"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Hierarchy"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Portflolios"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Bridges"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "5"
          }
        ],
        "folder": "Bonus"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "6"
          }
        ],
        "folder": "Measures"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ],
        "folder": "Helper Dimensions"
      }
    ],
    "relationships": [
      {
        "name": "73ada670-dfe9-4b85-a1fb-d80c6b936f8c",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "EMP_ID",
        "fromTable": "Fact - Employee Hierarchy",
        "securityFilteringBehavior": "bothDirections",
        "toColumn": "EMP_ID",
        "toTable": "Dimension - Employee"
      },
      {
        "name": "901c0c08-fef3-46db-a39d-1e574eaa106b",
        "fromColumn": "End of Month",
        "fromTable": "Dimension - Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_90cc4c3a-556c-4348-b92e-22a9c3eaf1ef"
      },
      {
        "name": "6257c2e5-5a2f-4794-ab3d-a8894eff608c",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "SC_TP",
        "fromTable": "Fact - Employee Hierarchy",
        "toColumn": "SC_TP",
        "toTable": "Dimension - SC_TP"
      },
      {
        "name": "e6d25fbd-bb08-493b-903d-fea8d9dc9c94",
        "fromColumn": "Date",
        "fromTable": "Dimension - Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_fdedc1cd-39c2-441d-8541-0b5f03e5e557"
      },
      {
        "name": "53860b93-a1c7-4337-b054-727a59ff1928",
        "fromColumn": "SNAP_DATE",
        "fromTable": "Fact - Employee Hierarchy",
        "toColumn": "Date",
        "toTable": "Dimension - Calendar"
      },
      {
        "name": "5160476e-ed66-473b-aca5-c1949fd84e91",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DW_ID",
        "fromTable": "Fact - Employee Hierarchy Plan Bridge",
        "toColumn": "DW_ID",
        "toTable": "Fact - Employee Hierarchy"
      },
      {
        "name": "97546f17-cf36-4d36-bcd0-8a1722ef176c",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "PRNT_EMP_ID",
        "fromTable": "Fact - Employee Hierarchy",
        "toColumn": "EMP_ID",
        "toTable": "Dimension - Employee Secondary"
      },
      {
        "name": "2a47a7e0-3da0-4e9a-ac53-41f8a92ea164",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DW_ID_DEPO",
        "fromTable": "Fact - Depos Hierarchy Bridge",
        "toColumn": "DW_ID",
        "toTable": "Fact - Depos"
      },
      {
        "name": "8086151b-9b6c-446d-b391-c3f5d9258d67",
        "fromColumn": "DW_ID",
        "fromTable": "Fact - Loans Hierarchy Bridge",
        "toColumn": "DW_ID",
        "toTable": "Fact - Employee Hierarchy"
      },
      {
        "name": "08869daf-96db-4bc4-8998-5cbfa967ea94",
        "fromColumn": "DW_ID",
        "fromTable": "Fact - Depos Hierarchy Bridge",
        "toColumn": "DW_ID",
        "toTable": "Fact - Employee Hierarchy"
      },
      {
        "name": "34a86736-8ab8-447e-89c7-eac17e430bc9",
        "fromColumn": "PROD_ID",
        "fromTable": "Fact - Depos",
        "toColumn": "DEPO_PROD_ID",
        "toTable": "Dimension - Depo Product"
      },
      {
        "name": "5d24b2bc-1e69-4b51-acca-c5f8923c547a",
        "fromColumn": "PROD_ID",
        "fromTable": "Fact - Loans",
        "toColumn": "LOAN_PROD_ID",
        "toTable": "Dimension - Loan Product"
      },
      {
        "name": "813f6c64-e104-4e15-bde8-7e72d083df48",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DW_ID",
        "fromTable": "Fact - Bonus Hierarchy Bridge",
        "toColumn": "DW_ID",
        "toTable": "Fact - Employee Hierarchy"
      },
      {
        "name": "2d4afe23-8ae9-433f-93a6-8f442181003d",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DW_ID_PLAN",
        "fromTable": "Fact - Employee Hierarchy Plan Bridge",
        "toColumn": "DW_ID",
        "toTable": "Fact - Bonus Plan"
      },
      {
        "name": "293a101e-5301-44de-a015-0eb38faebbf3",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DW_ID_LOAN",
        "fromTable": "Fact - Loans Hierarchy Bridge",
        "toColumn": "DW_ID",
        "toTable": "Fact - Loans"
      },
      {
        "name": "c37ad6da-0fc2-45b1-b614-092bbc842d90",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DW_ID_BNS",
        "fromTable": "Fact - Bonus Hierarchy Bridge",
        "toColumn": "DW_ID",
        "toTable": "Fact - Bonus"
      },
      {
        "name": "cbbf51c3-433d-4841-8202-1370b71f0b30",
        "fromColumn": "CCY",
        "fromTable": "Fact - Depos",
        "toColumn": "CCY_DESCR",
        "toTable": "Dimension - Currency"
      },
      {
        "name": "0b29959c-005a-4f74-868b-6c63d5ff7cdb",
        "fromColumn": "CCY",
        "fromTable": "Fact - Loans",
        "toColumn": "CCY_DESCR",
        "toTable": "Dimension - Currency"
      },
      {
        "name": "f27f028c-181b-402c-bc87-6376db465458",
        "fromColumn": "ROLE_TP",
        "fromTable": "Fact - Loans",
        "toColumn": "ROLE_DESCR",
        "toTable": "Dimension - Role Type"
      },
      {
        "name": "54ac4151-c88f-4f02-a166-f6db0abcf321",
        "fromColumn": "ROLE_TP",
        "fromTable": "Fact - Depos",
        "toColumn": "ROLE_DESCR",
        "toTable": "Dimension - Role Type"
      },
      {
        "name": "79a42124-ffa0-4f2b-a93e-b1a0e30d208b",
        "fromColumn": "PLN_TP",
        "fromTable": "Fact - Bonus Plan",
        "toCardinality": "many",
        "toColumn": "PLN_TP",
        "toTable": "Dimension - Plan"
      },
      {
        "name": "e3693451-93f8-4578-9363-0fc630ebdf44",
        "fromColumn": "DT",
        "fromTable": "Update Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_cfca3bbe-65e4-447b-88e2-c168447172aa"
      },
      {
        "name": "57e4921c-9a93-4606-ba90-94c46b490a08",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DW_ID",
        "fromTable": "Fact - Ranking  Hierarchy Bridge",
        "toColumn": "DW_ID",
        "toTable": "Fact - Employee Hierarchy"
      },
      {
        "name": "d88e1fed-d52a-4fb6-8ab3-59071250f2d1",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DW_ID_RNK",
        "fromTable": "Fact - Ranking  Hierarchy Bridge",
        "toColumn": "DW_ID",
        "toTable": "Fact - Ranking"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_f0f39127-5302-41e9-949b-1c629ce3b9b5",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d86bf493-710b-42ec-8c7a-5ddabb32abaf",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cd552454-9ea7-4b87-9a20-0942c583f26a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "54e156b8-5fdd-437e-85e9-34d7ac36ec5d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c5c69b34-25d8-4cbb-be4d-8a3d7286635e",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "60d2dd3c-70f0-4a99-8f1d-f3c63ff7df65",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "99eb3f2f-347b-4c1c-a892-f8875aad48d2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "80f34b53-7190-4eff-aee5-30626bc1fc1c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "42522efa-4659-475f-8a10-ac68a1aea9d3",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "02e78a57-f3a8-4cac-8468-a66af1fbabca",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6ec8507b-001b-4450-ba4d-7028d9615c03",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "13ca9886-05dd-484f-b779-6aed77d242c0",
                "ordinal": 3
              }
            ],
            "lineageTag": "0deb51da-0036-4b6c-b7f8-62a5eaadd03a"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "edbfd1d3-3a9a-44d5-8d3d-738aee112382",
        "partitions": [
          {
            "name": "DateTableTemplate_f0f39127-5302-41e9-949b-1c629ce3b9b5-f5977470-7bdd-4fcd-9d81-c48548633c2e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Fact - Bonus",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "BNS_M",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b2ebeb91-6c02-43a1-803e-4a6ded4b3872",
            "sourceColumn": "BNS_M",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_M_NPS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e639cb9d-24aa-4c4b-bc2d-6234037815c3",
            "sourceColumn": "BNS_M_NPS",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_M_NPS_VAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "54aca056-c36b-4faa-93da-f91a45d9bf9e",
            "sourceColumn": "BNS_M_NPS_VAL",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_M_IAS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3c2e013a-d49e-44f2-8394-8458cb5ea955",
            "sourceColumn": "BNS_M_IAS",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_M_IAS_VAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1adeeccd-9af8-4323-bdcd-fe465363cfb0",
            "sourceColumn": "BNS_M_IAS_VAL",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_M_TOTAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "dataType": "double",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "91d4ec1c-e944-490b-9a3a-32514fbb7bde",
            "sourceColumn": "BNS_M_TOTAL",
            "summarizeBy": "none"
          },
          {
            "name": "FRST_BUCKT_FOND",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7d1bc02c-f1e8-4c7e-b401-547dcfa5a992",
            "sourceColumn": "FRST_BUCKT_FOND",
            "summarizeBy": "none"
          },
          {
            "name": "FRST_BUCKT_FOND_FLF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "81b060c7-4084-46a7-a9c7-99698eb607ef",
            "sourceColumn": "FRST_BUCKT_FOND_FLF",
            "summarizeBy": "none"
          },
          {
            "name": "FRST_BUCKT_FOND_WGHT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3fb4f773-98b7-44b5-945d-caa8e3fe3f96",
            "sourceColumn": "FRST_BUCKT_FOND_WGHT",
            "summarizeBy": "none"
          },
          {
            "name": "SCND_BUCKT_FOND",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "880ccb8e-68c2-491f-8535-409dc247bf47",
            "sourceColumn": "SCND_BUCKT_FOND",
            "summarizeBy": "none"
          },
          {
            "name": "SCND_BUCKT_FOND_FLF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8bc74891-cca0-49cb-ad73-2cb1a2319dca",
            "sourceColumn": "SCND_BUCKT_FOND_FLF",
            "summarizeBy": "none"
          },
          {
            "name": "SCND_BUCKT_FOND_WGHT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "281f1b28-0003-413e-a235-d0dd5cb925f2",
            "sourceColumn": "SCND_BUCKT_FOND_WGHT",
            "summarizeBy": "none"
          },
          {
            "name": "TOT_FOND",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5c10add5-65f0-4760-aeb2-7f9534833c4b",
            "sourceColumn": "TOT_FOND",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_M_IAS_NPS_LEFTOVER_PCT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f9634cf7-0fab-4731-bb96-c5fa3daefc59",
            "sourceColumn": "BNS_M_IAS_NPS_LEFTOVER_PCT",
            "summarizeBy": "none"
          },
          {
            "name": "SC_CORR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "01d602b7-63d8-4138-8705-65c90a7fbb16",
            "sourceColumn": "SC_CORR",
            "summarizeBy": "none"
          },
          {
            "name": "SC_CORR_FLF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6db4c34f-dff2-4f76-b36d-a12915fec75f",
            "sourceColumn": "SC_CORR_FLF",
            "summarizeBy": "none"
          },
          {
            "name": "SC_NOCORR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f7abdf0e-387e-4701-b13b-2cdb8750cdf8",
            "sourceColumn": "SC_NOCORR",
            "summarizeBy": "none"
          },
          {
            "name": "TOT_INC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bd763d47-da04-45ff-8d08-8bc299218303",
            "sourceColumn": "TOT_INC",
            "summarizeBy": "none"
          },
          {
            "name": "TOT_DEPO_PMT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f1d41fcd-cf88-47a3-9b41-6ffbc0a21775",
            "sourceColumn": "TOT_DEPO_PMT",
            "summarizeBy": "none"
          },
          {
            "name": "TOT_DEPO_RVN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "97c39c93-c88c-4b6f-a242-e144f9900d99",
            "sourceColumn": "TOT_DEPO_RVN",
            "summarizeBy": "none"
          },
          {
            "name": "TOT_INC_CMSN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c48e30ff-3a0f-4db3-a4ca-44c039e5cdfd",
            "sourceColumn": "TOT_INC_CMSN",
            "summarizeBy": "none"
          },
          {
            "name": "TOT_INC_CNV",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c5506cf8-ec99-492f-a14c-30179250d8d3",
            "sourceColumn": "TOT_INC_CNV",
            "summarizeBy": "none"
          },
          {
            "name": "TOT_INC_INTRS_INC_GEL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "037ee0eb-c459-48be-886d-8c7d80612fce",
            "sourceColumn": "TOT_INC_INTRS_INC_GEL",
            "summarizeBy": "none"
          },
          {
            "name": "TOT_INC_INTRS_INC_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "761f4e54-47f9-49d5-a55f-3170ceb67ea8",
            "sourceColumn": "TOT_INC_INTRS_INC_USD",
            "summarizeBy": "none"
          },
          {
            "name": "TOT_INC_INTRS_INC_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b26abc92-9a0f-4fd7-ab16-5df0a7c8dc48",
            "sourceColumn": "TOT_INC_INTRS_INC_EUR",
            "summarizeBy": "none"
          },
          {
            "name": "TOT_INC_OPR_REV",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9df0d1fb-ab00-4256-add0-ab02f89cda55",
            "sourceColumn": "TOT_INC_OPR_REV",
            "summarizeBy": "none"
          },
          {
            "name": "TOT_INC_PNLT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fdb78867-bdfc-4081-b041-da6508db50ac",
            "sourceColumn": "TOT_INC_PNLT",
            "summarizeBy": "none"
          },
          {
            "name": "TOT_INC_PRPMT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "46875b51-535b-49d9-b814-83466cfba50a",
            "sourceColumn": "TOT_INC_PRPMT",
            "summarizeBy": "none"
          },
          {
            "name": "ERN_TOT_INC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cccb46f9-4092-4032-9705-f6e68ff36405",
            "sourceColumn": "ERN_TOT_INC",
            "summarizeBy": "none"
          },
          {
            "name": "ERN_TOT_DEPO_PMT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0b748284-482b-4331-a131-e3d7a7a9106f",
            "sourceColumn": "ERN_TOT_DEPO_PMT",
            "summarizeBy": "none"
          },
          {
            "name": "ERN_TOT_DEPO_RVN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9b043047-2919-45df-a596-c3f806f1d0da",
            "sourceColumn": "ERN_TOT_DEPO_RVN",
            "summarizeBy": "none"
          },
          {
            "name": "ERN_TOT_INC_CMSN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4b1fd906-14c3-45da-9764-85e68834302b",
            "sourceColumn": "ERN_TOT_INC_CMSN",
            "summarizeBy": "none"
          },
          {
            "name": "ERN_TOT_INC_CNV",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6bc3b02f-795e-4c15-9c7b-5ea6e50ed64a",
            "sourceColumn": "ERN_TOT_INC_CNV",
            "summarizeBy": "none"
          },
          {
            "name": "ERN_TOT_INC_INTRS_INC_GEL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8f466b6a-b911-477b-99bf-389de24b2c1f",
            "sourceColumn": "ERN_TOT_INC_INTRS_INC_GEL",
            "summarizeBy": "none"
          },
          {
            "name": "ERN_TOT_INC_INTRS_INC_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9790e0be-4ce4-478c-9630-239828673eb6",
            "sourceColumn": "ERN_TOT_INC_INTRS_INC_USD",
            "summarizeBy": "none"
          },
          {
            "name": "ERN_TOT_INC_INTRS_INC_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e90487f5-24b9-411d-8a94-a9f0215fd5e7",
            "sourceColumn": "ERN_TOT_INC_INTRS_INC_EUR",
            "summarizeBy": "none"
          },
          {
            "name": "ERN_TOT_INC_OPR_REV",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d0202e40-a1d3-48f2-8eae-80961bdfd3ac",
            "sourceColumn": "ERN_TOT_INC_OPR_REV",
            "summarizeBy": "none"
          },
          {
            "name": "ERN_TOT_INC_PNLT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8727568c-7f22-425e-a2bb-a8fabd2314ca",
            "sourceColumn": "ERN_TOT_INC_PNLT",
            "summarizeBy": "none"
          },
          {
            "name": "ERN_TOT_INC_PRPMT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bb9fa3a1-874a-44ae-8ab6-b269fab38aa7",
            "sourceColumn": "ERN_TOT_INC_PRPMT",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_Y",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e7d5b663-d533-4b95-805b-caf0557fb0f1",
            "sourceColumn": "BNS_Y",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_Y_FLF_CORR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d24cbc11-c57b-4b13-98fe-5c8e8b281fa5",
            "sourceColumn": "BNS_Y_FLF_CORR",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_Y_TOTAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1c9213a0-2c0b-4dd0-b0bb-de99c53d09fc",
            "sourceColumn": "BNS_Y_TOTAL",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_SHR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d3d10d76-5567-49b2-8fbb-8248c956a09e",
            "sourceColumn": "BNS_SHR",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_OVDU_CORR_AMT_PROD_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b65521d3-f9a9-46be-938d-efc5bb86b0a5",
            "sourceColumn": "BNS_OVDU_CORR_AMT_PROD_1",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_OVDU_CORR_AMT_PROD_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d7589572-230f-4285-a359-ead797e61550",
            "sourceColumn": "BNS_OVDU_CORR_AMT_PROD_2",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_OVDU_CORR_AMT_PROD_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f04eb7e3-4c43-4602-a41f-67456a49019e",
            "sourceColumn": "BNS_OVDU_CORR_AMT_PROD_3",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_OVDU_CORR_AMT_PROD_4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a837da60-1ecb-4489-9a7a-e4c701343af5",
            "sourceColumn": "BNS_OVDU_CORR_AMT_PROD_4",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_M_PROJ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "edac38e9-16c0-4435-ae8a-106e8fd4bad4",
            "sourceColumn": "BNS_M_PROJ",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_CUTOVER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "dataType": "double",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "81913a5a-3b2e-4ef1-88fd-ab0f94f71bee",
            "sourceColumn": "BNS_CUTOVER",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_AFTER_OVDU_CORR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8418026a-8466-4cbe-943d-0de23302f38a",
            "sourceColumn": "BNS_AFTER_OVDU_CORR",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_AFTER_SC_CORR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "49d39d90-44cc-430b-bd99-f0bd51879d6f",
            "sourceColumn": "BNS_AFTER_SC_CORR",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_AFTER_FLF_CORR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fd66363d-407b-48e8-b5f8-703280446f1f",
            "sourceColumn": "BNS_AFTER_FLF_CORR",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_AFTER_GRPFLF_CORR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f02e6b43-1bf6-4d49-9d0a-4d9b0f6782ea",
            "sourceColumn": "BNS_AFTER_GRPFLF_CORR",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_GRP_CUMLTD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "78fb2edd-0cfc-44ff-ae72-c4fd73486eb2",
            "sourceColumn": "BNS_GRP_CUMLTD",
            "summarizeBy": "none"
          },
          {
            "name": "DW_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4ce77a5-7ff1-4a26-94b4-bbc9b99d2965",
            "sourceColumn": "DW_ID",
            "summarizeBy": "none"
          },
          {
            "name": "TOT_FLF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8441a688-a03b-4717-a36a-ce63af82be96",
            "sourceColumn": "TOT_FLF",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_NOAGRO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d1686455-6815-4004-9a96-8fe5f36f1504",
            "sourceColumn": "BNS_NOAGRO",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_Y_IAS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "3692d27b-d07d-42ef-b620-ab0024593f51",
            "sourceColumn": "BNS_Y_IAS",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_Y_IAS_NPS_LEFTOVER_PCT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "8a410471-ebee-442f-b88e-726f2b20c091",
            "sourceColumn": "BNS_Y_IAS_NPS_LEFTOVER_PCT",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_Y_IAS_VAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "4366574d-15a3-4ad9-b470-0fbc43aa91c0",
            "sourceColumn": "BNS_Y_IAS_VAL",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_Y_NPS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "5fa664bd-326d-4d41-bd7e-40b208dfcbbc",
            "sourceColumn": "BNS_Y_NPS",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_Y_NPS_VAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "6aef3aa8-5840-4525-9039-07f9a697f84c",
            "sourceColumn": "BNS_Y_NPS_VAL",
            "summarizeBy": "none"
          },
          {
            "name": "SME_KPI_WGHT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ec6f6027-eb79-4796-b59c-ce5a0a38806c",
            "sourceColumn": "SME_KPI_WGHT",
            "summarizeBy": "none"
          },
          {
            "name": "SC_FLF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e5b2e08b-feef-48d5-8275-082af49d285a",
            "sourceColumn": "SC_FLF",
            "summarizeBy": "none"
          },
          {
            "name": "PB_KPI_WGHT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5dc8a268-433e-4cda-a9b8-00bae3eee8ab",
            "sourceColumn": "PB_KPI_WGHT",
            "summarizeBy": "none"
          },
          {
            "name": "OP_KPI_WGHT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f22863d6-cb29-4c53-be9b-09a691a50b77",
            "sourceColumn": "OP_KPI_WGHT",
            "summarizeBy": "none"
          },
          {
            "name": "CM_KPI_WGHT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "adbe144c-0f91-4cd6-b26d-d5c587b321f1",
            "sourceColumn": "CM_KPI_WGHT",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_Y_FINAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "dataType": "double",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "14a0ef08-430d-4321-b34f-0ea77a4d374e",
            "sourceColumn": "BNS_Y_FINAL",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_M_FINAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5bba34f2-b50d-414c-b26a-1054a34ef18c",
            "sourceColumn": "BNS_M_FINAL",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_AFTER_Y_FLF_CORR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f0709e57-1228-498f-94df-d15521cf5f51",
            "sourceColumn": "BNS_AFTER_Y_FLF_CORR",
            "summarizeBy": "none"
          },
          {
            "name": "OVDU_PCT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6ae2c977-86d3-4186-97f9-bb74ce2d3537",
            "sourceColumn": "OVDU_PCT",
            "summarizeBy": "none"
          },
          {
            "name": "CARD_Y_FLF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "68038487-659a-4f46-a4e7-ea07aa293938",
            "sourceColumn": "CARD_Y_FLF",
            "summarizeBy": "none"
          },
          {
            "name": "CARD_OP_KPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c6d916d2-ce4f-4376-9c22-fd81722d5517",
            "sourceColumn": "CARD_OP_KPI",
            "summarizeBy": "none"
          },
          {
            "name": "CARD_SME_KPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "429d64a3-259a-4dd5-bb27-374bba766e4c",
            "sourceColumn": "CARD_SME_KPI",
            "summarizeBy": "none"
          },
          {
            "name": "CARD_PB_KPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "59ca1c80-2d05-40c8-8729-a6b492f63bd5",
            "sourceColumn": "CARD_PB_KPI",
            "summarizeBy": "none"
          },
          {
            "name": "CARD_CM_KPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f4c8b862-23d8-460f-830c-87e5cf9a3232",
            "sourceColumn": "CARD_CM_KPI",
            "summarizeBy": "none"
          },
          {
            "name": "TOT_INC_GRP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c8e1aac6-d137-4f58-8990-a9b90286b07a",
            "sourceColumn": "TOT_INC_GRP",
            "summarizeBy": "none"
          },
          {
            "name": "ROLE_TP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "168c230d-8333-43e0-888d-875af500198a",
            "sourceColumn": "ROLE_TP",
            "summarizeBy": "none"
          },
          {
            "name": "ERN_TOT_INC_INTRS_INC_GEL_STP2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c7a2448d-a5c3-4e81-89ce-6011da54b0a1",
            "sourceColumn": "ERN_TOT_INC_INTRS_INC_GEL_STP2",
            "summarizeBy": "none"
          },
          {
            "name": "ERN_TOT_INC_INTRS_INC_USD_STP2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fcc89c44-75d7-412b-bad4-a554d2f138e2",
            "sourceColumn": "ERN_TOT_INC_INTRS_INC_USD_STP2",
            "summarizeBy": "none"
          },
          {
            "name": "ERN_TOT_INC_INTRS_INC_EUR_STP2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ec348a28-fd4e-442e-9093-a9b2702f982e",
            "sourceColumn": "ERN_TOT_INC_INTRS_INC_EUR_STP2",
            "summarizeBy": "none"
          },
          {
            "name": "ERN_TOT_INC_STP2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5c085401-f665-4534-8423-970f1de15e7e",
            "sourceColumn": "ERN_TOT_INC_STP2",
            "summarizeBy": "none"
          },
          {
            "name": "HEAD_SHR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "be764112-3dc1-4c7a-aa2c-783ec802b0f3",
            "sourceColumn": "HEAD_SHR",
            "summarizeBy": "none"
          },
          {
            "name": "BNS_AFTER_TAX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b5ed36ff-6dd7-4bc2-95c7-22407e5edb46",
            "sourceColumn": "BNS_AFTER_TAX",
            "summarizeBy": "none"
          },
          {
            "name": "TOT_FND",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "08171f61-8432-4118-a7ac-e40a7fecc902",
            "sourceColumn": "TOT_FND",
            "summarizeBy": "none"
          },
          {
            "name": "bns_cutover_y",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3970284f-0602-4c6e-9ce8-8df089aefd5a",
            "sourceColumn": "bns_cutover_y",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a994bcce-f1dd-4578-96d8-97385a62924a",
        "partitions": [
          {
            "name": "Fact - Bonus-1fa5ff0f-e4da-4f80-9324-49f0a431791b",
            "mode": "import",
            "queryGroup": "Bonus",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"select DW_ID, TOT_INC_PRPMT, TOT_INC_PNLT, TOT_INC_OPR_REV, TOT_INC_INTRS_INC_USD, TOT_INC_INTRS_INC_GEL, TOT_INC_INTRS_INC_EUR, TOT_INC_CNV, TOT_INC_CMSN, TOT_INC, TOT_FOND, TOT_FLF, TOT_DEPO_RVN, TOT_DEPO_PMT, SME_KPI_WGHT, SC_NOCORR, SC_FLF, SC_CORR_FLF, SC_CORR, SCND_BUCKT_FOND_WGHT, SCND_BUCKT_FOND_FLF, SCND_BUCKT_FOND, PB_KPI_WGHT, OP_KPI_WGHT, FRST_BUCKT_FOND_WGHT, FRST_BUCKT_FOND_FLF, FRST_BUCKT_FOND, ERN_TOT_INC_PRPMT, ERN_TOT_INC_PNLT, ERN_TOT_INC_OPR_REV, ERN_TOT_INC_INTRS_INC_USD, ERN_TOT_INC_INTRS_INC_GEL, ERN_TOT_INC_INTRS_INC_EUR, ERN_TOT_INC_CNV, ERN_TOT_INC_CMSN, ERN_TOT_INC, ERN_TOT_DEPO_RVN, ERN_TOT_DEPO_PMT, CM_KPI_WGHT, BNS_Y_TOTAL, BNS_Y_NPS_VAL, BNS_Y_NPS, BNS_Y_IAS_VAL, BNS_Y_IAS_NPS_LEFTOVER_PCT, BNS_Y_IAS, BNS_Y_FLF_CORR, BNS_Y_FINAL, BNS_Y, BNS_SHR, BNS_OVDU_CORR_AMT_PROD_4, BNS_OVDU_CORR_AMT_PROD_3, BNS_OVDU_CORR_AMT_PROD_2, BNS_OVDU_CORR_AMT_PROD_1, BNS_NOAGRO, BNS_M_TOTAL, BNS_M_PROJ, BNS_M_NPS_VAL, BNS_M_NPS, BNS_M_IAS_VAL, BNS_M_IAS_NPS_LEFTOVER_PCT, BNS_M_IAS, BNS_M_FINAL, BNS_M, BNS_GRP_CUMLTD, BNS_CUTOVER, BNS_AFTER_Y_FLF_CORR, BNS_AFTER_SC_CORR, BNS_AFTER_OVDU_CORR, BNS_AFTER_GRPFLF_CORR, BNS_AFTER_FLF_CORR, OVDU_PCT, CARD_Y_FLF, CARD_OP_KPI, CARD_SME_KPI, CARD_PB_KPI, CARD_CM_KPI, ROLE_TP, TOT_INC_GRP, ERN_TOT_INC_INTRS_INC_GEL_STP2, ERN_TOT_INC_INTRS_INC_USD_STP2, ERN_TOT_INC_INTRS_INC_EUR_STP2, ERN_TOT_INC_STP2, HEAD_SHR, BNS_AFTER_TAX, TOT_FND,bns_cutover_y#(lf)from MDB_BI_BNS_FACT#(lf)where RLS_GRP in ('CM') and snap_date >= '2023-08-31'#(lf)and del_flag = 0;\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dimension - Employee",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "EMP_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d453a5ad-84bb-43f7-b8b9-26e66aec5594",
            "sourceColumn": "EMP_ID",
            "summarizeBy": "none"
          },
          {
            "name": "IMG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "ff672d90-a660-42c0-a98d-fa77ca78fe1b",
            "sourceColumn": "IMG",
            "summarizeBy": "none"
          },
          {
            "name": "EMP_ORDER_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7018ff26-df42-4408-98c5-684da2164aa4",
            "sourceColumn": "EMP_ORDER_ID",
            "summarizeBy": "none"
          },
          {
            "name": "EMP_DESCR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "164b6de7-5e53-49f1-883e-3ee635b16365",
            "sortByColumn": "EMP_ORDER_ID",
            "sourceColumn": "EMP_DESCR",
            "summarizeBy": "none"
          },
          {
            "name": "EMP_PST_DESCR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "52f62be7-4049-48a8-aa5a-b75f79dddd73",
            "sourceColumn": "EMP_PST_DESCR",
            "summarizeBy": "none"
          },
          {
            "name": "ROLE_DESCR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "172c4d54-5453-4eb8-8217-e0c4762e559e",
            "sourceColumn": "ROLE_DESCR",
            "summarizeBy": "none"
          },
          {
            "name": "ORDR_ROLE_DESCR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "03adc782-9706-4709-88ed-f82cd48c9b60",
            "sourceColumn": "ORDR_ROLE_DESCR",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9ddcfd38-a888-4a19-9b8d-6293ccf675f3",
        "measures": [
          {
            "name": "EMP_RLS_COLOR",
            "expression": "IF( max( 'Fact - Employee Hierarchy'[RSL_GRP]) = \"CMH\", \"#E6E6E6\",\"#FFFFFF\") //\"#FFFFD0\",",
            "lineageTag": "86ac2fc6-c100-4a46-bd8f-ddc0c42bf1e8"
          }
        ],
        "partitions": [
          {
            "name": "Dimension - Employee-8f2be07b-f264-44cc-91ba-b2e8802cc209",
            "mode": "import",
            "queryGroup": "Employee",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"drop table if exists #XX;#(lf)select E.EMP_ID, E.EMP_NAME, E.EMP_PST_DESCR, E.PHOTO,#(lf)                row_number() over (partition by 1 order by#(lf)                case#(lf)                    when E.EMP_PST_DESCR = 'CPH' then 1#(lf)                    when E.EMP_PST_DESCR = 'PB' then 3#(lf)                    when E.EMP_PST_DESCR = 'CM' then 4#(lf)                    when E.EMP_PST_DESCR = 'CMH' then 2#(lf)                    end ) EMP_ORDER_ID,#(lf)                case#(lf)                    when E.EMP_PST_DESCR = 'CPH' then N'პრემიუმ და საკრედიტო განყოფილება'#(lf)                    when E.EMP_PST_DESCR = 'PB' then N'პრემიუმ ბანკირები'#(lf)                    when E.EMP_PST_DESCR = 'CM' then N'საკრედიტო მენეჯერები'#(lf)                    when E.EMP_PST_DESCR = 'CMH' then N'საკრედიტო მენეჯერების ჯგუფის უფროსი'#(lf)                    end ROLE_DESCR,#(lf) case#(lf)                    when E.EMP_PST_DESCR = 'CPH' then 1#(lf)                    when E.EMP_PST_DESCR = 'PB' then 3#(lf)                    when E.EMP_PST_DESCR = 'CM' then 4#(lf)                    when E.EMP_PST_DESCR = 'CMH' then 2#(lf)                    end ORDR_ROLE_DESCR#(lf)into #XX#(lf)from (select distinct E.EMP_ID, E.EMP_NAME, E.EMP_PST_DESCR, (select max(PH) from TMP_H)  PHOTO#(lf)from MDB_BI_EMP_HIER_FACT HRH#(lf)join MDB_BI_EMP E on E.EMP_ID = HRH.EMP_ID#(lf)where SNAP_DATE >= '2023-08-31' and#(lf)      HRH.RPT_ID = 3#(lf)and hrh.del_flag = 0)E;#(lf)#(lf)#(lf)#(lf)select EMP_ID, N'თანამშრომელი ' +  cast(ROW_NUMBER() over (partition by 1 order by  EMP_ID) as nvarchar(max)) EMP_NAME, EMP_PST_DESCR, PHOTO, EMP_ORDER_ID, ROLE_DESCR, ORDR_ROLE_DESCR#(lf)from #XX;\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"PHOTO\", type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"IMG\", each \"data:image/png;base64,\"&[PHOTO]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"IMG\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"PHOTO\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"EMP_NAME\", \"EMP_DESCR\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"EMP_ID\", Int64.Type}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact - Bonus Plan",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PLN_PER_FRQ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57a7b6b3-f916-46ae-8fe9-b09c93781177",
            "sourceColumn": "PLN_PER_FRQ",
            "summarizeBy": "none"
          },
          {
            "name": "PLN_TP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6b16bcf-fba1-4bf6-bddd-5acf9df24dae",
            "sourceColumn": "PLN_TP",
            "summarizeBy": "none"
          },
          {
            "name": "FCT_VAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "254e0305-79fa-4116-b109-3a8b13bba77d",
            "sourceColumn": "FCT_VAL",
            "summarizeBy": "sum"
          },
          {
            "name": "PLN_VAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d8aa26ce-3a7b-4b8c-932f-e344658e2785",
            "sourceColumn": "PLN_VAL",
            "summarizeBy": "sum"
          },
          {
            "name": "PCT_FLF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "588df65e-8ef8-4ee9-ba23-81adf183f896",
            "sourceColumn": "PCT_FLF",
            "summarizeBy": "sum"
          },
          {
            "name": "PCT_FLF_RNG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3cd2e484-fcf3-4915-bb7f-a4a29462cc8b",
            "sourceColumn": "PCT_FLF_RNG",
            "summarizeBy": "sum"
          },
          {
            "name": "PCT_FLF_RNG_WGHT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3b0a8c9a-390f-4c6c-9f78-1bc2fb164a36",
            "sourceColumn": "PCT_FLF_RNG_WGHT",
            "summarizeBy": "sum"
          },
          {
            "name": "PLN_PER_FRQ_GEO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF('Fact - Bonus Plan'[PLN_PER_FRQ] = \"M\", \"ყოველთვიური\", \"წლიური\")",
            "isDataTypeInferred": true,
            "lineageTag": "89812a6a-f006-4d5b-ae08-cd79f8eb70bb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "KPI_WGHT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8319a067-727c-45b8-98c2-ddb31421122f",
            "sourceColumn": "KPI_WGHT",
            "summarizeBy": "sum"
          },
          {
            "name": "DW_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16d393c3-559a-45a4-82b7-b637ce5c7318",
            "sourceColumn": "DW_ID",
            "summarizeBy": "none"
          },
          {
            "name": "RSL_GRP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2935af7-894a-4e84-95df-34fe9bec04f7",
            "sourceColumn": "RSL_GRP",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "230783a2-57d3-4d9e-853a-6e1e8e4b0b45",
        "partitions": [
          {
            "name": "Fact - Bonus Plan-28b0f07c-2cbe-46c6-9084-43f6762f332c",
            "mode": "import",
            "queryGroup": "Bonus",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"select DW_ID,RSL_GRP,#(lf)       PLN_PER_FRQ,#(lf)       PLN_TP,#(lf)       FCT_VAL,#(lf)       PLN_VAL,#(lf)       PCT_FLF,#(lf)       PCT_FLF_RNG,#(lf)       PCT_FLF_RNG_WGHT,#(lf)       KPI_WGHT#(lf)from MDB_BI_PLN_DATA_FACT#(lf)where RSL_GRP in ('CM')#(lf)  and snap_date >= '2023-08-31'#(lf)and del_flag = 0;#(lf)#(lf)\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"PLN_VAL\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact - Employee Hierarchy",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "EMP_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dc9193e6-f8db-4d8e-af94-071af5c8679c",
            "sourceColumn": "EMP_ID",
            "summarizeBy": "none"
          },
          {
            "name": "PRNT_EMP_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6c4ce3d7-fc97-4675-a8a2-2c4356e1b407",
            "sourceColumn": "PRNT_EMP_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DW_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9cf9e8f5-e960-425f-b6dd-43f82ebd43b5",
            "sourceColumn": "DW_ID",
            "summarizeBy": "none"
          },
          {
            "name": "SNAP_DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mmmm yyyy",
            "lineageTag": "30921548-481e-40e1-87d3-414c7cb919df",
            "sourceColumn": "SNAP_DATE",
            "summarizeBy": "none"
          },
          {
            "name": "HEAD_FLAG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8364908e-8a5e-46f2-8e5e-4eea3f52154a",
            "sourceColumn": "HEAD_FLAG",
            "summarizeBy": "sum"
          },
          {
            "name": "POS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "444cb677-94f6-4550-a892-e761fdc7f927",
            "sourceColumn": "POS",
            "summarizeBy": "none"
          },
          {
            "name": "SC_TP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3f8304be-3e7b-472d-9f35-387bb915e34a",
            "sourceColumn": "SC_TP",
            "summarizeBy": "none"
          },
          {
            "name": "SC_CAT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2d52b3a-deed-4457-bf8d-d5e8d74240f5",
            "sourceColumn": "SC_CAT",
            "summarizeBy": "none"
          },
          {
            "name": "POS_DESCR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              " IF('Fact - Employee Hierarchy'[MAIN_FLAG] = 0 && 'Fact - Employee Hierarchy'[RSL_GRP] in {\"SB\", \"SSB\"}, \"SME ბანკირები\", ",
              "IF('Fact - Employee Hierarchy'[MAIN_FLAG] = 1 && 'Fact - Employee Hierarchy'[RSL_GRP] = \"CM\", \"კრედიტ მენეჯერები\", ",
              "IF('Fact - Employee Hierarchy'[MAIN_FLAG] = 1 && 'Fact - Employee Hierarchy'[RSL_GRP] = \"OP\", \"ოპერატორები\", ",
              "IF('Fact - Employee Hierarchy'[MAIN_FLAG] = 1 && 'Fact - Employee Hierarchy'[RSL_GRP] = \"PB\", \"პრემიუმ ბანკირები\", ",
              "IF('Fact - Employee Hierarchy'[MAIN_FLAG] = 1 && 'Fact - Employee Hierarchy'[RSL_GRP] = \"PS\", \"ფილიალები\",\"NA\")))))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "ccf52c75-13ad-4e45-9ab8-8c95f617e686",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "DW_ID2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f0cfef9-5e81-498d-94ce-49d0ca7cf09e",
            "sourceColumn": "DW_ID2",
            "summarizeBy": "none"
          },
          {
            "name": "SC_WGHT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2129ab5b-051e-4790-bd98-d98d082f99f5",
            "sourceColumn": "SC_WGHT",
            "summarizeBy": "sum"
          },
          {
            "name": "POS_BNS_TREE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF('Fact - Employee Hierarchy'[SC_TP]= 1,\"#A\",IF('Fact - Employee Hierarchy'[SC_TP]= 2,\"#B\",IF('Fact - Employee Hierarchy'[SC_TP]= 3,\"#C\"))) & \" - \" & 'Fact - Employee Hierarchy'[SC_WGHT]*100 & \"%\"",
              "& \" - \" & 'Fact - Employee Hierarchy'[SC_CAT] & \" - \"& 'Fact - Employee Hierarchy'[POS]"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "ace941ba-2fd9-4acb-979c-566cf3f70a44",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "RSL_GRP_GEO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF('Fact - Employee Hierarchy'[RSL_GRP] = \"SB\", \"SME ბანკირი\", IF('Fact - Employee Hierarchy'[RSL_GRP] = \"SSB\", \"უფროსი SME ბანკირი\"))",
            "isDataTypeInferred": true,
            "lineageTag": "7d921e63-5f3c-4f99-b526-a85b2691b578",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "BRANCH_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f2d777a6-0b1a-4530-9439-06bcd61ff74f",
            "sourceColumn": "BRANCH_ID",
            "summarizeBy": "count"
          },
          {
            "name": "RLS_MAIL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "427b20a5-7e99-4050-b8a2-602314b8d111",
            "sourceColumn": "RLS_MAIL",
            "summarizeBy": "none"
          },
          {
            "name": "MAIN_FLAG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "50280a2e-4c89-442e-aed5-1d3f8138c93c",
            "sourceColumn": "MAIN_FLAG",
            "summarizeBy": "sum"
          },
          {
            "name": "RSL_GRP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b8141f7-300f-40fa-bf76-80b2fe9de956",
            "sourceColumn": "RSL_GRP",
            "summarizeBy": "none"
          },
          {
            "name": "LVL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "24889b58-0af9-4c65-a038-c8a6e9e2b616",
            "sourceColumn": "LVL",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "448d485c-0f33-46ca-a632-4614cb7dd9c2",
        "partitions": [
          {
            "name": "Fact - Employee Hierarchy-acdf1519-a7e6-45fe-a458-2f725680fcbb",
            "mode": "import",
            "queryGroup": "Hierarchy",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"select SNAP_DATE, DW_ID, DW_ID2, PRNT_EMP_ID, EMP_ID, RLS_MAIL, RPT_ID, RLS_GRP, HEAD_FLAG, POS, SC_TP, SC_CAT, SC_WGHT, BRANCH_ID, LVL#(lf)from MDB_BI_EMP_HIER_FACT HRH#(lf)where HRH.RPT_ID = 3#(lf)  and HRH.SNAP_DATE >= '2023-08-31'#(lf)and hrh.del_flag = 0;\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"EMP_ID\", Int64.Type}, {\"PRNT_EMP_ID\", Int64.Type}, {\"SNAP_DATE\", type datetime}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"RPT_ID\", \"MAIN_FLAG\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"MAIN_FLAG\", Int64.Type}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type1\",{{\"RLS_GRP\", \"RSL_GRP\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"BRANCH_ID\", Int64.Type}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type2\",\"XNA\",\"\",Replacer.ReplaceText,{\"SC_WGHT\"}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"SC_WGHT\", type number}, {\"SC_TP\", Int64.Type}})",
                "in",
                "    #\"Changed Type3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dimension - Calendar",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "6fb746a3f0f0460d9e497251ba8682e2"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "m/d/yyyy",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0fa9ce01-0a36-430b-9a57-ef42e21ec762",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_fdedc1cd-39c2-441d-8541-0b5f03e5e557"
                },
                "isDefault": true,
                "relationship": "e6d25fbd-bb08-493b-903d-fea8d9dc9c94"
              }
            ]
          },
          {
            "name": "End of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "expression": "ENDOFMONTH('Dimension - Calendar'[Date])",
            "formatString": "mmmm yyyy",
            "isDataTypeInferred": true,
            "lineageTag": "346ca10b-4451-424b-8a53-a710c6fa9a8b",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_90cc4c3a-556c-4348-b92e-22a9c3eaf1ef"
                },
                "isDefault": true,
                "relationship": "901c0c08-fef3-46db-a39d-1e574eaa106b"
              }
            ]
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Dimension - Calendar'[Date],\"mmmm\")",
            "isDataTypeInferred": true,
            "lineageTag": "974f2f0b-420a-4faf-9b57-d688b3b61f6e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "be66f6d5-950b-4d99-9e48-366febd10c6c",
        "partitions": [
          {
            "name": "Dimension - Calendar-c8f4571c-866c-4d13-a04e-7af8fc1cb4c7",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(MIN('Fact - Employee Hierarchy'[SNAP_DATE]), MAX('Fact - Employee Hierarchy'[SNAP_DATE]))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_90cc4c3a-556c-4348-b92e-22a9c3eaf1ef",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7eccdf85-0c80-4a56-ba65-6e7af8a68f07",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d2c53498-7464-4b57-8dbd-7c693f70a68b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "97ade50c-c57e-4539-a033-fa501b870ad5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9d20fdc9-3893-4f07-ab4e-c8e70ea3924c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d77cd08d-433d-4a20-b4f9-b173f442c26d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6b5c0d91-ee0e-4157-b619-22ccb80025b0",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "907ecad2-10f8-4037-8c05-14639dd09949",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b72dbab1-589a-4210-859c-16755a7a21d5",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9d964a5b-86c2-4fb7-bf60-a4b338fd8923",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d7107ebc-6dac-479b-9c0d-e9c654d178bf",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "56a3c244-d686-4555-bbad-d3ad891bc863",
                "ordinal": 3
              }
            ],
            "lineageTag": "e56250dc-ef3e-4f99-9423-d2b056601829"
          }
        ],
        "isHidden": true,
        "lineageTag": "35508301-17c5-46b2-b58b-5ece3fb258f1",
        "partitions": [
          {
            "name": "LocalDateTable_90cc4c3a-556c-4348-b92e-22a9c3eaf1ef-af173893-b610-4566-948a-5de5173e48a8",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dimension - Calendar'[End of Month])), 1, 1), Date(Year(MAX('Dimension - Calendar'[End of Month])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Dimension - Employee Secondary",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "EMP_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8e7ee425-104c-40c2-9258-e220036ec322",
            "sourceColumn": "EMP_ID",
            "summarizeBy": "none"
          },
          {
            "name": "IMG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "217e3398-be9e-40a5-9113-fa240ad2f2db",
            "sourceColumn": "IMG",
            "summarizeBy": "none"
          },
          {
            "name": "EMP_ORDER_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a58ad689-02b9-4eae-be16-6a037428e755",
            "sourceColumn": "EMP_ORDER_ID",
            "summarizeBy": "none"
          },
          {
            "name": "EMP_DESCR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6252f9f-d836-4775-a4b8-fa53a52fd42c",
            "sourceColumn": "EMP_DESCR",
            "summarizeBy": "none"
          },
          {
            "name": "EMP_PST_DESCR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4dcd13eb-974a-47b2-8a9f-507e714e045a",
            "sourceColumn": "EMP_PST_DESCR",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0f7c0506-34ba-433c-9e64-5cfa15ad531d",
        "measures": [
          {
            "name": "EMP_DESCR_HEAD",
            "expression": "CALCULATE(max('Dimension - Employee Secondary'[EMP_DESCR]) , FILTER('Fact - Employee Hierarchy', 'Fact - Employee Hierarchy'[RSL_GRP] = \"CM\" && 'Fact - Employee Hierarchy'[HEAD_FLAG] = 1))",
            "lineageTag": "79528e99-bcb8-477d-985e-00ff355e1f7a"
          },
          {
            "name": "EMP_DESCR_HEAD_SSM",
            "expression": "CALCULATE(max('Dimension - Employee Secondary'[EMP_DESCR]) , FILTER('Fact - Employee Hierarchy', 'Fact - Employee Hierarchy'[MAIN_FLAG] = 4 && 'Fact - Employee Hierarchy'[HEAD_FLAG] = 1))",
            "lineageTag": "ee6ec4c9-a73b-44ae-89ef-c35c7c52a116"
          },
          {
            "name": "EMP_DESCR_HEAD_CMH",
            "expression": "CALCULATE(max('Dimension - Employee'[EMP_DESCR]) , FILTER('Fact - Employee Hierarchy',  'Fact - Employee Hierarchy'[RSL_GRP] = \"CMH\"))",
            "lineageTag": "bab844aa-c953-4c18-92c5-9dd63b32e37e"
          }
        ],
        "partitions": [
          {
            "name": "Dimension - Employee Secondary-5ca0e821-8d61-423b-b990-363644801eb7",
            "mode": "import",
            "queryGroup": "Employee",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"drop table if exists #XX;#(lf)select distinct E.EMP_ID, E.EMP_NAME, E.EMP_PST_DESCR,  (select max(PH) from TMP_H) PHOTO, E.EMP_ORDER_ID#(lf)into #XX#(lf)from MDB_BI_EMP_HIER_FACT HRH#(lf)join MDB_BI_EMP E on E.EMP_ID = HRH.PRNT_EMP_ID#(lf)where SNAP_DATE >= '2023-08-31' and#(lf)      HRH.RPT_ID = 3#(lf)and hrh.del_flag = 0;#(lf)#(lf)#(lf)#(lf)select EMP_ID, N'თანამშრომელი ' +  cast(ROW_NUMBER() over (partition by 1 order by  EMP_ID) as nvarchar(max)) EMP_NAME, EMP_PST_DESCR, PHOTO, EMP_ORDER_ID#(lf)from #XX;\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"PHOTO\", type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"IMG\", each \"data:image/png;base64,\"&[PHOTO]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"IMG\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"PHOTO\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"EMP_NAME\", \"EMP_DESCR\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"EMP_ID\", Int64.Type}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dimension - SC_TP",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SC_TP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "24461784-6877-459a-a6ec-8fe50c692141",
            "sourceColumn": "SC_TP",
            "summarizeBy": "none"
          },
          {
            "name": "SC_TP_DESCR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c4312fd-40e9-46e5-b7b5-6e25642361fd",
            "sourceColumn": "SC_TP_DESCR",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fbe91a0b-ab57-4334-9929-4705eeda3fba",
        "partitions": [
          {
            "name": "Dimension - SC_TP-cb166cca-5a51-44b0-92ae-579ca94606ec",
            "mode": "import",
            "queryGroup": "Helper Dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUVJ2VIrViVYyAjGdwExjENNZKTYWAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [SC_TP = _t, SC_TP_DESCR = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"SC_TP\", Int64.Type}, {\"SC_TP_DESCR\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_fdedc1cd-39c2-441d-8541-0b5f03e5e557",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9559c1e1-65d8-4616-95f9-49545d52c712",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "231f4f5b-842a-488f-996f-f56700f0dfc9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ad9ca569-312a-443c-b0db-02259314cc14",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3c98a671-8f76-4b25-b716-188d5227c978",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "dd616d4f-0e82-4532-b994-f911feef52a3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d7340162-13d6-4a04-bda4-71b6964602f3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7c228b20-a71f-48d9-8e0f-023aa213571a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5bc74727-d4fe-48a8-a74a-3c3fa3e4ba7b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "cdcddde5-eaf7-4195-8240-1ef74c65c57a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8217ab02-990f-44df-a471-994972ecffb6",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "30a82154-1bf9-4003-83e4-7e44edf158ae",
                "ordinal": 3
              }
            ],
            "lineageTag": "d7f9c100-6f62-49b3-86cb-ef3daba8cb2d"
          }
        ],
        "isHidden": true,
        "lineageTag": "93761c07-789e-4b7c-8622-69be905e42cd",
        "partitions": [
          {
            "name": "LocalDateTable_fdedc1cd-39c2-441d-8541-0b5f03e5e557-c8fd9f0c-bba2-4608-8bbe-b71977df1a40",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dimension - Calendar'[Date])), 1, 1), Date(Year(MAX('Dimension - Calendar'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Fact - Employee Hierarchy Plan Bridge",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DW_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0971062-3755-4db2-949f-76436cfd5cfd",
            "sourceColumn": "DW_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DW_ID_PLAN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75e93cd3-5d20-4fc7-9201-c5575c3e14c0",
            "sourceColumn": "DW_ID_PLAN",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "759e7c0b-7ccb-4f18-ac4c-d77a459a77a4",
        "partitions": [
          {
            "name": "Fact - Employee Hierarchy Plan Bridge-f497d263-5c8d-4119-984e-314e362ed0d4",
            "mode": "import",
            "queryGroup": "Bridges",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"select A.DW_ID, DW_ID_PLN DW_ID_PLAN#(lf)from MDB_BI_PLN_DATA_BRG_FACT A#(lf)join MDB_BI_EMP_HIER_FACT MEH on A.DW_ID = MEH.DW_ID#(lf)where MEH.RPT_ID = 3#(lf)  and MEH.SNAP_DATE >= '2023-08-31'#(lf)  and meh.del_flag = 0;\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measures - Bonus",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47fecc0a-9c00-49db-8859-122e254e7bb2",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "baff1477-72f3-42b4-83a7-1e8775ac4b7c",
        "measures": [
          {
            "name": "FRST_BUCKT_FOND_FLF",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[FRST_BUCKT_FOND_FLF] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "a8a096c9-a6cf-4c60-8769-526e4b45960d"
          },
          {
            "name": "TOT_INC_PRPMT",
            "expression": [
              "/* First Bucket Fulfilment */",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[TOT_INC_PRPMT] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "dc02776c-a80b-4ac2-85d4-4508da6df4ad"
          },
          {
            "name": "TOT_INC_PNLT",
            "expression": [
              "/* First Bucket Fulfilment */",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[TOT_INC_PNLT] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "959cbadd-83ad-494e-93d0-803d94934553"
          },
          {
            "name": "TOT_INC_OPR_REV",
            "expression": [
              "/* First Bucket Fulfilment */",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[TOT_INC_OPR_REV] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "721a8a81-2580-4495-885b-304f92f46b02"
          },
          {
            "name": "TOT_INC_INTRS_INC_USD",
            "expression": [
              "/* First Bucket Fulfilment */",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[TOT_INC_INTRS_INC_USD] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "e002bab3-9139-4b06-bf58-6f6064adab29"
          },
          {
            "name": "TOT_INC_INTRS_INC_GEL",
            "expression": [
              "/* First Bucket Fulfilment */",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[TOT_INC_INTRS_INC_GEL] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "829c0bd2-735e-4ff3-a7b8-5a300cbfeaed"
          },
          {
            "name": "TOT_INC_INTRS_INC_EUR",
            "expression": [
              "/* First Bucket Fulfilment */",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[TOT_INC_INTRS_INC_EUR] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "150ecd63-d9d6-4b8e-b8c1-0d828baf79bd"
          },
          {
            "name": "TOT_INC_CNV",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[TOT_INC_CNV] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "1fa88530-ef89-444a-bb3e-2ce5c6b64d96"
          },
          {
            "name": "TOT_INC_CMSN",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[TOT_INC_CMSN] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "bf139464-77ce-4a26-abe2-b677fdfe95b1"
          },
          {
            "name": "TOT_INC",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[TOT_INC] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "7f6c7c86-2965-467a-9004-ff34e4c7bfd5"
          },
          {
            "name": "TOT_FOND",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[TOT_FOND] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "651f0318-688a-4b0e-baf2-0dd976456bea"
          },
          {
            "name": "TOT_DEPO_RVN",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[TOT_DEPO_RVN] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "9bb61678-7641-4f65-a9cd-d835f9bccae0"
          },
          {
            "name": "TOT_DEPO_PMT",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[TOT_DEPO_PMT] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "92c9ddbc-3375-4766-9007-3a823525d7e0"
          },
          {
            "name": "SCND_BUCKT_FOND_WGHT",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[SCND_BUCKT_FOND_WGHT] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "892bfb67-1e56-4348-bb9a-6d6530fd7334"
          },
          {
            "name": "SCND_BUCKT_FOND_FLF",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[SCND_BUCKT_FOND_FLF] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "999a6cf4-6061-4e2f-9627-499646be9547"
          },
          {
            "name": "SCND_BUCKT_FOND",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[SCND_BUCKT_FOND] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "afaac9fa-0a81-4649-b0f8-c9d307357eea"
          },
          {
            "name": "SC_NOCORR",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[SC_NOCORR] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "1393ae49-a8dd-46bc-b675-95065eb0585a"
          },
          {
            "name": "SC_CORR",
            "expression": [
              "",
              "VAR res =",
              "",
              "        SUM ( 'Fact - Bonus'[SC_CORR] )",
              "",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "9c8c01c4-198a-481f-a9d8-7ff2931ab751"
          },
          {
            "name": "SC_CORR_FLF",
            "expression": [
              "",
              "VAR res =",
              "",
              "        SUM ( 'Fact - Bonus'[SC_FLF] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "1ddd5243-46b2-42d1-86ca-e89f5c4739f2"
          },
          {
            "name": "FRST_BUCKT_FOND_WGHT",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[FRST_BUCKT_FOND_WGHT] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "c355cde4-4c51-4287-9741-90b527b54370"
          },
          {
            "name": "FRST_BUCKT_FOND",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[FRST_BUCKT_FOND] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "362c6c8e-530d-4af8-b6bb-fb43a0031f5b"
          },
          {
            "name": "ERN_TOT_INC_PRPMT",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[ERN_TOT_INC_PRPMT] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "02fffac7-41ee-453b-afc8-6fdde7ed7dfa"
          },
          {
            "name": "ERN_TOT_INC_PNLT",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[ERN_TOT_INC_PNLT] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "90b4c17b-bc5b-4c40-a265-ec2bde0e13bf"
          },
          {
            "name": "ERN_TOT_INC_OPR_REV",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[ERN_TOT_INC_OPR_REV] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "9b978387-885b-44b4-b55d-9af46e50e86a"
          },
          {
            "name": "ERN_TOT_INC_INTRS_INC_USD",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[ERN_TOT_INC_INTRS_INC_USD] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "ca87710e-0a35-4ece-bd30-3b494555eab4"
          },
          {
            "name": "ERN_TOT_INC_INTRS_INC_GEL",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[ERN_TOT_INC_INTRS_INC_GEL] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "51466c89-3b73-4a2c-9fb9-3ec96234e154"
          },
          {
            "name": "ERN_TOT_INC_INTRS_INC_EUR",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[ERN_TOT_INC_INTRS_INC_EUR] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "e07973ce-e0d5-4ccd-86be-7ba901887703"
          },
          {
            "name": "ERN_TOT_INC_CNV",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[ERN_TOT_INC_CNV] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "e638af23-6c77-41d5-a6c3-9de5e0d8fa00"
          },
          {
            "name": "ERN_TOT_INC_CMSN",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[ERN_TOT_INC_CMSN] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "e9756393-f0b1-48c6-977f-b3be97845750"
          },
          {
            "name": "ERN_TOT_INC",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[ERN_TOT_INC] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "f5f1da46-9af4-4e86-9522-e45675f91a45"
          },
          {
            "name": "ERN_TOT_DEPO_RVN",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[ERN_TOT_DEPO_RVN] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "64a54666-4f82-4e11-a001-e73ba8f5a7f5"
          },
          {
            "name": "ERN_TOT_DEPO_PMT",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[ERN_TOT_DEPO_PMT] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "b4f9e4ee-43d4-4b6e-840f-2ed9f6aa447c"
          },
          {
            "name": "BNS_Y_TOTAL",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_Y_TOTAL] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "e5c379c2-daa9-4f71-9099-d0d48fa694a0"
          },
          {
            "name": "BNS_Y_FLF_CORR",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_Y_FLF_CORR] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "f4cb7246-fa36-488a-808a-1ebe569fa722"
          },
          {
            "name": "BNS_Y",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_Y] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "0e0fdd96-3a9b-449f-b401-d80fb7f3d1f7"
          },
          {
            "name": "BNS_SHR",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_SHR] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "da27db91-195d-44ad-83dd-5fb4fc3fb4b9"
          },
          {
            "name": "BNS_OVDU_CORR_AMT_PROD_4",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_OVDU_CORR_AMT_PROD_4] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "dd49ba19-e524-4b09-b56f-11255a847e0f"
          },
          {
            "name": "BNS_OVDU_CORR_AMT_PROD_3",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_OVDU_CORR_AMT_PROD_3] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "7c951da5-d5bb-4a05-85e6-e64dcd32b64c"
          },
          {
            "name": "BNS_OVDU_CORR_AMT_PROD_2",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_OVDU_CORR_AMT_PROD_2] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "ca0262fa-a641-4881-a456-3eef78ad5a09"
          },
          {
            "name": "BNS_OVDU_CORR_AMT_PROD_1",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_OVDU_CORR_AMT_PROD_1] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "98017a49-303d-4b5e-b4b5-5c5a3f94e59a"
          },
          {
            "name": "BNS_OVDU_CORR_AMT",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_OVDU_CORR_AMT_PROD_1] ) + SUM ( 'Fact - Bonus'[BNS_OVDU_CORR_AMT_PROD_2] ) + SUM ( 'Fact - Bonus'[BNS_OVDU_CORR_AMT_PROD_3] ) + SUM ( 'Fact - Bonus'[BNS_OVDU_CORR_AMT_PROD_4] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "56d60646-7385-4858-8944-e1e7dc12dadf"
          },
          {
            "name": "BNS_M_TOTAL",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_M_TOTAL] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "d1495b03-a852-4dd3-89bb-07ffb006fd8f"
          },
          {
            "name": "BNS_M_PROJ",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_M_PROJ] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "42b894a3-a9e6-4ad7-a303-679f96ecd5ff"
          },
          {
            "name": "BNS_M_NPS_VAL",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_M_NPS_VAL] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0%\" ) )",
              "    )"
            ],
            "lineageTag": "ab97e2c5-2671-40aa-851a-c3a19132ffb9"
          },
          {
            "name": "BNS_M_NPS",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_M_NPS] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "8e64207a-e644-4467-801b-ebddcf857836"
          },
          {
            "name": "BNS_M_IAS",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_M_IAS] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "c17be514-f183-48e8-a26d-2a882eae1839"
          },
          {
            "name": "BNS_M_IAS_VAL",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_M_IAS_VAL] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0%\" ) )",
              "    )"
            ],
            "lineageTag": "19ef0860-c510-46b6-8645-941a4049f7af"
          },
          {
            "name": "BNS_M_IAS_NPS_LEFTOVER_PCT",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_M_IAS_NPS_LEFTOVER_PCT] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "59371b8b-db5f-44cc-86db-ce9db6241df6"
          },
          {
            "name": "BNS_M",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_M] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "de1d0da6-823e-41a6-8d86-3f18ee9b3180"
          },
          {
            "name": "BNS_GRP_CUMLTD",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_GRP_CUMLTD] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "89b3c312-808d-41f3-9c8b-aaf79140cc3e"
          },
          {
            "name": "BNS_CUTOVER",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_CUTOVER] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "4ac25dc7-ca5d-474e-a775-f77beac609ff"
          },
          {
            "name": "BNS_AFTER_FLF_CORR",
            "expression": [
              "",
              "VAR res = SUM ( 'Fact - Bonus'[BNS_AFTER_FLF_CORR] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "b4bd4134-dbb9-4c23-96ad-7830c641458a"
          },
          {
            "name": "BNS_AFTER_GRPFLF_CORR",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_AFTER_GRPFLF_CORR] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "8bf28473-be66-49b2-9d23-2658783a1537"
          },
          {
            "name": "BNS_AFTER_OVDU_CORR",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_AFTER_OVDU_CORR] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "04c3632f-ed6b-453c-89fb-5cbd1817887a"
          },
          {
            "name": "BNS_AFTER_SC_CORR",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_AFTER_SC_CORR] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "076ade0d-2ca4-456c-9c04-9848577e7a83"
          },
          {
            "name": "KPI_SME_WGHT",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[SME_KPI_WGHT] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0%\" ) )",
              "    )"
            ],
            "lineageTag": "1582efc6-1f68-4a53-aac2-b0a0d697a34e"
          },
          {
            "name": "KPI_PB_WGHT",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[PB_KPI_WGHT] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0%\" ) )",
              "    )"
            ],
            "lineageTag": "227a4f0e-075f-4e8e-b739-6673285075d2"
          },
          {
            "name": "KPI_CM_WGHT",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[CM_KPI_WGHT] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0%\" ) )",
              "    )"
            ],
            "lineageTag": "a3a80888-4ec6-4427-bf95-3581ada6446a"
          },
          {
            "name": "KPI_OP_WGHT",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[OP_KPI_WGHT] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0%\" ) )",
              "    )"
            ],
            "lineageTag": "3cb3a379-c877-410b-8c1d-39b59a442d6e"
          },
          {
            "name": "TOT_FLF",
            "expression": [
              "",
              "VAR res = SUM ( 'Fact - Bonus'[TOT_FLF] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0.0%\" ) )",
              "    )"
            ],
            "lineageTag": "c2af62c2-bc52-40c3-802d-f970a82ff678"
          },
          {
            "name": "BNS_M_AVG",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_M_FINAL] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "87049261-6632-4779-b81d-b3c7e05d32f8"
          },
          {
            "name": "BNS_Y_AVG",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_Y_FINAL] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "7e52e107-489f-4fcf-9c72-a55a224bb544"
          },
          {
            "name": "Measure",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "f6eea499-49b5-4d38-9c9b-b5fd7cf2dc19"
          },
          {
            "name": "OVDU_PCT",
            "expression": [
              "",
              "VAR res = SUM ( 'Fact - Bonus'[OVDU_PCT] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0.0%\" ) )",
              "    )"
            ],
            "lineageTag": "76e19d67-b76e-439a-813e-dcb1ec4a216b"
          },
          {
            "name": "BNS_NOAGRO",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_NOAGRO] )",
              "RETURN",
              "    res"
            ],
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "8be896bb-6c4b-4bba-8bf8-325d6bfad27f"
          },
          {
            "name": "BNS_AFTER_Y_FLF_CORR",
            "expression": [
              "",
              "VAR res = SUM ( 'Fact - Bonus'[BNS_AFTER_Y_FLF_CORR] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "093d998a-6902-44c1-9c41-422320d53190"
          },
          {
            "name": "BNS_Y_IAS",
            "expression": [
              "",
              "VAR res =",
              "",
              "        SUM ( 'Fact - Bonus'[BNS_Y_IAS] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "ae1d571b-a38a-4f7a-af83-bf9569765596"
          },
          {
            "name": "BNS_Y_IAS_NPS_LEFTOVER_PCT",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_Y_IAS_NPS_LEFTOVER_PCT] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "46a3e152-e417-43b4-894f-d5727e0c6d5b"
          },
          {
            "name": "BNS_Y_IAS_VAL",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_Y_IAS_VAL] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0%\" ) )",
              "    )"
            ],
            "lineageTag": "aa658a6a-28be-4065-a24f-5e643a05b6cc"
          },
          {
            "name": "BNS_Y_NPS",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_Y_NPS] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "f3ad17ac-1866-4d2d-bbb5-82fd5e3314d0"
          },
          {
            "name": "BNS_Y_NPS_VAL",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_Y_NPS_VAL] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0%\" ) )",
              "    )"
            ],
            "lineageTag": "f725aaba-42d7-41c8-8e90-e8ec5700c7d6"
          },
          {
            "name": "BNS_CUTOVER_PCT",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_CUTOVER] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0.00%\" ) )",
              "    )"
            ],
            "lineageTag": "4ba39284-a4e9-4a4f-9f2d-0951692efc64"
          },
          {
            "name": "CARD_OP_KPI",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[CARD_OP_KPI] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0.00%\" ) )",
              "    )"
            ],
            "lineageTag": "ee4b09e4-d56c-4d7d-a8e8-4699dadd7abf"
          },
          {
            "name": "CARD_CM_KPI",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[CARD_CM_KPI] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0.00%\" ) )",
              "    )"
            ],
            "lineageTag": "0a1a1c3e-f848-4daa-b662-b6088e02da76"
          },
          {
            "name": "CARD_PB_KPI",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[CARD_PB_KPI] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0.00%\" ) )",
              "    )"
            ],
            "lineageTag": "1db6eda1-0f49-4855-9f88-450b47298a3e"
          },
          {
            "name": "CARD_SME_KPI",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[CARD_SME_KPI] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0.00%\" ) )",
              "    )"
            ],
            "lineageTag": "a9824444-25b0-4bb7-b897-f12d6cf7c824"
          },
          {
            "name": "CARD_Y_FLF",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[CARD_Y_FLF] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0%\" ) )",
              "    )"
            ],
            "lineageTag": "20363f33-604d-4803-bd9e-a9e087453fbd"
          },
          {
            "name": "BNS_Y_FINAL",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[BNS_Y_FINAL] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "44ad61dc-88ae-42b8-9d32-1f30dd78e344"
          },
          {
            "name": "BNS_CUTOVER_Y",
            "expression": [
              "",
              "VAR res =",
              "        SUM ( 'Fact - Bonus'[bns_cutover_y] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "ce79b4c7-0b92-4869-b54b-64be78326d8a"
          }
        ],
        "partitions": [
          {
            "name": "Measures - Bonus-537f2716-37e8-4b7b-8b5b-fa635175b7fe",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measures - Bonus Plan",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e90ce934-c49e-4534-9f7c-3a96846e6b33",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0270d22a-a7b8-4d4a-a15f-074874dec6cd",
        "measures": [
          {
            "name": "PCT_FLF_RNG_WGHT",
            "expression": [
              "",
              "VAR res = SUM ( 'Fact - Bonus Plan'[PCT_FLF_RNG_WGHT] )",
              "RETURN ",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0.0%\" ) )",
              "    )"
            ],
            "lineageTag": "4ef149b5-b863-44d6-b6d3-9f50acd63114"
          },
          {
            "name": "BT_FCT_VAL სხვა",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[FCT_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"OP/Other Bucket 2/M\",",
              "      \"PS/Other Bucket 2/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "056a08d0-f1be-4c38-9128-39ff81f7e9e1"
          },
          {
            "name": "BT_PLN_VAL",
            "expression": [
              "var res = sum('Fact - Bonus Plan'[PLN_VAL])",
              "return if( MAX('Dimension - Plan'[PLN_GRP]) in {\"პირველი კალათა\", \"მეორე კალათა\"}, BLANK(), res) "
            ],
            "formatString": "#,0",
            "lineageTag": "993c325b-88db-4c86-b45d-d889aa756f32"
          },
          {
            "name": "BT_FLF_RNG",
            "expression": [
              "var res = sum('Fact - Bonus Plan'[PCT_FLF_RNG])",
              "return if( MAX('Dimension - Plan'[PLN_GRP]) in {\"პირველი კალათა\", \"მეორე კალათა\"}, BLANK(), res) "
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "54fd3457-80e0-42ea-acd8-611aa7a16e9a"
          },
          {
            "name": "BT_PCT_FLF_RNG_WGHT",
            "expression": [
              "var res = sum('Fact - Bonus Plan'[PCT_FLF_RNG_WGHT])",
              "return if( MAX('Dimension - Plan'[PLN_GRP]) in {\"პირველი კალათა\", \"მეორე კალათა\"}, res,  BLANK()) "
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "93afd6fb-3168-4383-97dc-9f2decbaa72e"
          },
          {
            "name": "BT_FCT_VAL მოთხოვნამდე",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[FCT_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"OP/Demand Bucket 1/M\",",
              "      \"PS/Demand Bucket 1/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "c2b31f2a-ffbb-4b77-8b9a-26819984405a"
          },
          {
            "name": "BT_FCT_VAL ვადიანი და მოთხოვნამდე",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[FCT_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"OP/Time and Demand Bucket 1/M\",",
              "      \"PS/Time and Demand Bucket 1/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "23338baf-b207-4317-b2b7-a585d2ffd90d"
          },
          {
            "name": "BT_FCT_VAL ვადიანი",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[FCT_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"OP/Time Bucket 1/M\",",
              "      \"PS/Time Bucket 1/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "0de2f443-1c79-426b-9c8f-a54c091e30e3"
          },
          {
            "name": "BT_PLN_VAL ვადიანი",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PLN_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"OP/Time Bucket 1/M\",",
              "      \"PS/Time Bucket 1/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "7287fe10-eb3e-4399-922c-a569cdce8a7a"
          },
          {
            "name": "BT_PLN_VAL ვადიანი და მოთხოვნამდე",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PLN_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"OP/Time and Demand Bucket 1/M\",",
              "      \"PS/Time and Demand Bucket 1/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "3d5334e5-cb1c-4163-9a20-94fdfd57a362"
          },
          {
            "name": "BT_PLN_VAL მოთხოვნამდე",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PLN_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"OP/Demand Bucket 1/M\",",
              "      \"PS/Demand Bucket 1/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "b744754e-99de-4eb9-a267-ef16c43c5bc2"
          },
          {
            "name": "BT_PLN_VAL სხვა",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PLN_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"OP/Other Bucket 2/M\",",
              "      \"PS/Other Bucket 2/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "4f0e7052-8fc6-4934-82d0-b31a58b56a9e"
          },
          {
            "name": "BT_PCT_FLF_RNG ვადიანი",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"OP/Time Bucket 1/M\",",
              "      \"PS/Time Bucket 1/Q\"} ))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ccfd61c4-767c-4031-be19-d9baed2d1c1c"
          },
          {
            "name": "BT_PCT_FLF_RNG ვადიანი და მოთხოვნამდე",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"OP/Time and Demand Bucket 1/M\",",
              "      \"PS/Time and Demand Bucket 1/Q\"} ))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b7986b69-d326-4ec8-868f-169e81da0e43"
          },
          {
            "name": "BT_PCT_FLF_RNG მოთხოვნამდე",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"OP/Demand Bucket 1/M\",",
              "      \"PS/Demand Bucket 1/Q\"} ))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2741483c-2bbb-4aa3-a663-013bb28bdcb9"
          },
          {
            "name": "BT_PCT_FLF_RNG სხვა",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"OP/Other Bucket 2/M\",",
              "      \"PS/Other Bucket 2/Q\"} ))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b90c9ca5-c345-40a6-8556-b261148119f9"
          },
          {
            "name": "BT_PCT_FLF_RNG_WGHT პირველი კალათა",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG_WGHT]), FILTER('Dimension - Plan', 'Dimension - Plan'[PLN_GRP_ID] = 7))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "971d0bc4-f05d-47ae-90a1-8b5af449f759"
          },
          {
            "name": "BT_PCT_FLF_RNG_WGHT მეორე კალათა",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG_WGHT]), FILTER('Dimension - Plan', 'Dimension - Plan'[PLN_GRP_ID] = 11))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f856e1fb-59ba-4812-bfbd-1588fb70d51b"
          },
          {
            "name": "BT_PCT_FLF_RNG_WGHT ჯამური",
            "expression": [
              "",
              "var res = ",
              "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG_WGHT]), FILTER('Dimension - Plan', 'Dimension - Plan'[PLN_GRP_ID] in {7,11}))",
              "return IF(res < 0.6, 0, IF(res > 1, 1 , res))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "02c2506f-7406-4d24-a939-858f3bc84768"
          },
          {
            "name": "PCT_FLF_RNG",
            "expression": [
              "",
              "VAR res = SUM ( 'Fact - Bonus Plan'[PCT_FLF_RNG] )",
              "RETURN ",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0.00%\" ) )",
              "    )"
            ],
            "lineageTag": "548518b9-8284-4364-8f2c-e5b180ecde62"
          },
          {
            "name": "PLN_VAL",
            "expression": [
              "",
              "VAR res = SUM ( 'Fact - Bonus Plan'[PLN_VAL] )",
              "RETURN ",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,###\" ) )",
              "    )"
            ],
            "lineageTag": "74c1dd14-bce5-4560-8282-937db0e519e7"
          },
          {
            "name": "FCT_VAL",
            "expression": [
              "",
              "VAR res = SUM ( 'Fact - Bonus Plan'[FCT_VAL] )",
              "RETURN ",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,###\" ) )",
              "    )"
            ],
            "lineageTag": "6a749280-04f5-4056-a199-e9dc45a62c8c"
          },
          {
            "name": "BS_FCT_VAL",
            "expression": [
              "",
              " SUM ( 'Fact - Bonus Plan'[FCT_VAL] )"
            ],
            "formatString": "#,0",
            "lineageTag": "0f30ed0a-0881-4d64-a4c5-1a2b52768186"
          },
          {
            "name": "BS_PCT_FLF_RNG",
            "expression": "SUM ( 'Fact - Bonus Plan'[PCT_FLF_RNG] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f2b30a2f-26da-4460-89e8-cfd187675d2c"
          },
          {
            "name": "BS_PLN_VAL",
            "expression": "SUM ( 'Fact - Bonus Plan'[PLN_VAL] )",
            "formatString": "#,0",
            "lineageTag": "482e459a-7158-41ec-aa55-62b264b776ae"
          },
          {
            "name": "KPI_WGHT",
            "expression": [
              "",
              "VAR res = SUM ( 'Fact - Bonus Plan'[KPI_WGHT] )",
              "RETURN ",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0.00%\" ) )",
              "    )"
            ],
            "lineageTag": "b99d2742-36dd-4664-b388-c0b227e81e32"
          },
          {
            "name": "SB_OP_KPI",
            "expression": "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG_WGHT]), FILTER('Dimension - Plan', 'Dimension - Plan'[PLN_GRP_ID] in {4,5,6,10}))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "476b1de4-5a71-462a-8c0a-1afa6c1025a5"
          },
          {
            "name": "SB_PB_KPI",
            "expression": "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG_WGHT]), FILTER('Dimension - Plan', 'Dimension - Plan'[PLN_GRP_ID] in {1,8}))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2e7ad5ef-9864-42b3-af76-a9963d8bef62"
          },
          {
            "name": "SB_CM_KPI",
            "expression": "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG_WGHT]), FILTER('Dimension - Plan', 'Dimension - Plan'[PLN_GRP_ID] in {2,3}))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "81a3a6c2-47a2-4954-8e0b-950f566f4888"
          },
          {
            "name": "SB_SM_KPI",
            "expression": "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG_WGHT]), FILTER('Dimension - Plan', 'Dimension - Plan'[PLN_GRP_ID] in {9}))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f5450fcb-e3c8-4a9d-b44e-fefa7a114f49"
          },
          {
            "name": "SB_FCT_VAL ახალი კლიენტი",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[FCT_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"PB/New Clients/M\",",
              "      \"PB/New Clients/Y\",",
              "      \"PS/New Clients/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "7f354d45-b93b-4638-8b84-c77eab6ced88"
          },
          {
            "name": "SB_FCT_VAL დეპოზიტების პორტფელის ზრდა",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[FCT_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"PB/Depo Portfolio Growth/M\",",
              "      \"PB/Depo Portfolio Growth/Y\",",
              "      \"PS/Depo Portfolio Growth PB/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "79f0e69b-3b33-417a-9f0f-3a61b4212170"
          },
          {
            "name": "SB_FCT_VAL პორტფელის ზრდა",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[FCT_VAL]), FILTER('Fact - Bonus Plan', 'Fact - Bonus Plan'[PLN_TP] in {\"CM/Portfolio Growth/M\",\"CM/Portfolio Growth/Y\",\"PS/Portfolio Growth CM/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "1f9bb3ff-fd98-4782-93bc-d737bad23704"
          },
          {
            "name": "SB_FCT_VAL სესხების პორტფელის ზრდა SME",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[FCT_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"SB/Loan Portfolio Growth/M\",",
              "      \"SB/Loan Portfolio Growth/Y\",",
              "      \"SSB/Loan Portfolio Growth/M\",",
              "      \"SSB/Loan Portfolio Growth/Y\",",
              "      \"PS/Loan Portfolio Growth SME/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "8a236346-2a0d-41d4-b66c-4dea524f0fa8"
          },
          {
            "name": "SB_PLN_VAL ახალი კლიენტი",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PLN_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"PB/New Clients/M\",",
              "      \"PB/New Clients/Y\",",
              "      \"PS/New Clients/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "4568f32e-735e-4ffe-9ef1-b9266f61bf39"
          },
          {
            "name": "SB_PLN_VAL დეპოზიტების პორტფელის ზრდა",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PLN_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"PB/Depo Portfolio Growth/M\",",
              "      \"PB/Depo Portfolio Growth/Y\",",
              "      \"PS/Depo Portfolio Growth PB/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "fc21da2a-c7c7-426b-8030-2595c7bd4581"
          },
          {
            "name": "SB_PLN_VAL პორტფელის ზრდა",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PLN_VAL]), FILTER('Fact - Bonus Plan', 'Fact - Bonus Plan'[PLN_TP] in",
              " {\"CM/Portfolio Growth/M\",",
              " \"CM/Portfolio Growth/Y\",",
              " \"PS/Portfolio Growth CM/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "710c6594-1cf9-4d10-8ce2-0a4bdedb1019"
          },
          {
            "name": "SB_PLN_VAL სესხების პორტფელის ზრდა SME",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PLN_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"SB/Loan Portfolio Growth/M\",",
              "      \"SB/Loan Portfolio Growth/Y\",",
              "      \"SSB/Loan Portfolio Growth/M\",",
              "      \"SSB/Loan Portfolio Growth/Y\",",
              "      \"PS/Loan Portfolio Growth SME/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "f792d93b-8751-44d8-b95d-c424296b1885"
          },
          {
            "name": "SB_PCT_FLF_RNG ახალი კლიენტი",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"PB/New Clients/M\",",
              "      \"PB/New Clients/Y\",",
              "      \"PS/New Clients/Q\"} ))"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "17c03dbc-f1a2-4101-ac8d-bf6e86f455d7"
          },
          {
            "name": "SB_PCT_FLF_RNG დეპოზიტების პორტფელის ზრდა",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"PB/Depo Portfolio Growth/M\",",
              "      \"PB/Depo Portfolio Growth/Y\",",
              "      \"PS/Depo Portfolio Growth PB/Q\"} ))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f59a292d-e17c-4da3-83d0-bf4914c0f199"
          },
          {
            "name": "SB_PCT_FLF_RNG პორტფელის ზრდა",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG]), FILTER('Fact - Bonus Plan', 'Fact - Bonus Plan'[PLN_TP] in {\"CM/Portfolio Growth/M\",\"CM/Portfolio Growth/Y\",\"PS/Portfolio Growth CM/Q\"} ))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4ddafaa1-79ec-46b8-b69e-9332eb897061"
          },
          {
            "name": "SB_PCT_FLF_RNG სესხების პორტფელის ზრდა SME",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"SB/Loan Portfolio Growth/M\",",
              "      \"SB/Loan Portfolio Growth/Y\",",
              "      \"SSB/Loan Portfolio Growth/M\",",
              "      \"SSB/Loan Portfolio Growth/Y\",",
              "      \"PS/Loan Portfolio Growth SME/Q\"} ))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7556eb3e-dbf0-40cc-a28d-fafe750a4c5b"
          },
          {
            "name": "SB_FCT_VAL სესხების პორტფელის ზრდა PB",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[FCT_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"PB/Loan Portfolio Growth/M\",",
              "      \"PB/Loan Portfolio Growth/Y\",",
              "      \"PS/Loan Portfolio Growth PB/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "671b06de-4f15-42c2-9ad0-4ac3d18b8922"
          },
          {
            "name": "SB_PCT_FLF_RNG სესხების პორტფელის ზრდა PB",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"PB/Loan Portfolio Growth/M\",",
              "      \"PB/Loan Portfolio Growth/Y\",",
              "      \"PS/Loan Portfolio Growth PB/Q\"} ))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b6e259bd-93ba-43c5-b971-41f1e2a1c000"
          },
          {
            "name": "SB_PLN_VAL სესხების პორტფელის ზრდა PB",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PLN_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"PB/Loan Portfolio Growth/M\",",
              "      \"PB/Loan Portfolio Growth/Y\",",
              "      \"PS/Loan Portfolio Growth PB/Q\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "5b434170-5442-461c-8f99-a4b73d99d238"
          },
          {
            "name": "SB_PLN_VAL სესხების პორტფელის ზრდა - წლიური - PS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PLN_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"PS/Loan Portfolio Growth/Y\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "31dab37e-251a-42e6-bdd1-e66deae62627"
          },
          {
            "name": "SB_PLN_VAL დეპოზიტების პორტფელის ზრდა - წლიური - PS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PLN_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"PS/Depo Portfolio Growth/Y\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "6f4515a3-b052-478b-82f6-38617f377b30"
          },
          {
            "name": "SB_PCT_FLF_RNG პორტფელის ზრდა - წლიური - PS",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG_WGHT]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"PS/Depo Portfolio Growth/Y\",\"PS/Loan Portfolio Growth/Y\"} ))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "bda94e51-8303-434c-b750-59b9361363b6"
          },
          {
            "name": "SB_PCT_FLF_RNG სესხების პორტფელის ზრდა - წლიური - PS",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"PS/Loan Portfolio Growth/Y\"} ))"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "86dd0f72-6de9-4933-be94-31f8f532eab4"
          },
          {
            "name": "SB_PCT_FLF_RNG დეპოზიტების პორტფელის ზრდა - წლიური - PS",
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF_RNG]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"PS/Depo Portfolio Growth/Y\"} ))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b8350189-b4dd-417a-9c2a-8f9e855325d0"
          },
          {
            "name": "SB_FCT_VAL დეპოზიტების პორტფელის ზრდა - წლიური - PS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[FCT_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"PS/Depo Portfolio Growth/Y\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "3605be47-7580-4a80-bc49-9a8adacdff45"
          },
          {
            "name": "SB_FCT_VAL სესხების პორტფელის ზრდა - წლიური - PS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(sum('Fact - Bonus Plan'[FCT_VAL]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"PS/Loan Portfolio Growth/Y\"} ))"
            ],
            "formatString": "#,0",
            "lineageTag": "b547bfe0-be9a-4f36-88f1-609a65902319"
          },
          {
            "name": "MSB_CM_KPI",
            "expression": [
              "var res =  SUM ( 'Fact - Bonus'[CARD_CM_KPI] )",
              "return IF(ISBLANK(res), 0.000001, IF( res =  MAX('Fact - Bonus'[CM_KPI_WGHT]) , MAX('Fact - Bonus'[CM_KPI_WGHT]) + 0.0000001, res))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "dcb79278-1c15-4e81-b213-c43e64cb7e43"
          },
          {
            "name": "MSB_SM_KPI",
            "expression": [
              "var res =  SUM ( 'Fact - Bonus'[CARD_SME_KPI] )",
              "return IF(ISBLANK(res), 0.0000001, IF( res =  MAX('Fact - Bonus'[SME_KPI_WGHT]) , MAX('Fact - Bonus'[SME_KPI_WGHT]) + 0.0000001, res))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e9dfeb16-a718-4ede-9c09-a7de12f54846"
          },
          {
            "name": "MSB_PB_KPI",
            "expression": [
              "var res =  SUM ( 'Fact - Bonus'[CARD_PB_KPI] )",
              "return IF(ISBLANK(res), 0.0000001, IF( res = MAX('Fact - Bonus'[PB_KPI_WGHT]) , MAX('Fact - Bonus'[PB_KPI_WGHT]) +0.0000001, res))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "dc2d36bf-3c15-4833-b6fa-e08c16493e3e"
          },
          {
            "name": "MSB_OP_KPI",
            "expression": [
              "var res =  SUM ( 'Fact - Bonus'[CARD_OP_KPI] )",
              "return IF(ISBLANK(res), 0.000001, IF( res =  MAX('Fact - Bonus'[OP_KPI_WGHT]) , MAX('Fact - Bonus'[OP_KPI_WGHT]) + 0.0000001, res))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a7f73d1c-e46d-40f8-ac9c-e7f53ab484cb"
          },
          {
            "name": "PLN_VAL_DEMAND",
            "expression": [
              "",
              "VAR res = CALCULATE(SUM ( 'Fact - Bonus Plan'[PLN_VAL] ), FILTER('Fact - Bonus Plan', 'Fact - Bonus Plan'[PLN_TP] = \"OP/Demand Bucket 1/M\"))",
              "RETURN ",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,###\" ) )",
              "    )"
            ],
            "lineageTag": "6d4ade53-9483-4f9f-9a9a-13573193972a"
          },
          {
            "name": "FCT_VAL_DEMAND",
            "expression": [
              "",
              "VAR res = CALCULATE(SUM ( 'Fact - Bonus Plan'[FCT_VAL] ), FILTER('Fact - Bonus Plan', 'Fact - Bonus Plan'[PLN_TP] = \"OP/Demand Bucket 1/M\"))",
              "RETURN ",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,###\" ) )",
              "    )"
            ],
            "lineageTag": "a941f969-767c-4a35-ad4e-01e6bbfd0ceb"
          },
          {
            "name": "PCT_FLF_RNG_DEMAND",
            "expression": [
              "",
              "VAR res = CALCULATE(SUM ( 'Fact - Bonus Plan'[PCT_FLF_RNG] ), FILTER('Fact - Bonus Plan', 'Fact - Bonus Plan'[PLN_TP] = \"OP/Demand Bucket 1/M\"))",
              "RETURN ",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0.00%\" ) )",
              "    )"
            ],
            "lineageTag": "7dac6bdf-55cd-4f8d-85ec-6b8eb1473c69"
          },
          {
            "name": "PCT_FLF_RNG_WGHT_DEMAND",
            "expression": [
              "",
              "VAR res = CALCULATE(SUM ( 'Fact - Bonus Plan'[PCT_FLF_RNG_WGHT] ), FILTER('Fact - Bonus Plan', 'Fact - Bonus Plan'[PLN_TP] = \"OP/Demand Bucket 1/M\"))",
              "RETURN ",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0.00%\" ) )",
              "    )"
            ],
            "lineageTag": "2d8bf2b2-1a2c-463e-bf45-d9ee8f8ffd80"
          },
          {
            "name": "PCT_FLF_RNG_WGHT_TIME",
            "expression": [
              "",
              "VAR res = CALCULATE(SUM ( 'Fact - Bonus Plan'[PCT_FLF_RNG_WGHT] ), FILTER('Fact - Bonus Plan', 'Fact - Bonus Plan'[PLN_TP] = \"OP/Time Bucket 1/M\"))",
              "RETURN ",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0.00%\" ) )",
              "    )"
            ],
            "lineageTag": "a56aebd4-ab7b-480f-b2fb-6ff36dd840f4"
          },
          {
            "name": "PCT_FLF",
            "expression": [
              "",
              "VAR res = SUM ( 'Fact - Bonus Plan'[PCT_FLF] )",
              "RETURN ",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0.00%\" ) )",
              "    )"
            ],
            "lineageTag": "4fc181b3-731c-4245-98f2-ace98381f119"
          },
          {
            "name": "KPI დეპოზიტები",
            "expression": [
              "var res =",
              "CALCULATE(sum('Fact - Bonus Plan'[PCT_FLF]),",
              " FILTER('Fact - Bonus Plan', ",
              " 'Fact - Bonus Plan'[PLN_TP]",
              "  in {\"CPH/Portfolio Growth CM/M\", \"CPH/Depo Portfolio Growth PB/M\", \"CPH/Depo Portfolio Growth PB/Y\", \"CPH/Loan Portfolio Growth PB/M\", \"CPH/Loan Portfolio Growth PB/Y\", \"CPH/New Clients PB/M\", \"CPH/Portfolio Growth CM/Y\"} ))",
              "      return IF(ISBLANK(res), 0.000001, IF( res =  0.6 , res + 0.0000001,",
              "       IF( res =  1.3 , res + 0.0000001,",
              "       res)))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d21c8704-ec2f-403e-9cae-954a935426fc"
          },
          {
            "name": "PCT_FLF_RNG_WGHT_",
            "expression": "SUM ( 'Fact - Bonus Plan'[PCT_FLF_RNG_WGHT] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4b22a41b-9bd1-4a29-845e-0f023cecf9a4"
          },
          {
            "name": "BS_PCT_FLF",
            "expression": "SUM ( 'Fact - Bonus Plan'[PCT_FLF] )",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "cb6b11d8-3536-48c1-9e06-74d7509e27fa"
          },
          {
            "name": "BS_PCT_FLF_RNG_ICON",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM ( 'Fact - Bonus Plan'[PCT_FLF_RNG] )",
            "lineageTag": "d26af095-14dc-409f-8ced-151878ddb4ac"
          },
          {
            "name": "BS_PCT_FLF_RNG_WGHT",
            "expression": "SUM ( 'Fact - Bonus Plan'[PCT_FLF_RNG_WGHT] )",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0c5e0460-f655-4414-8517-d5cce22d35bf"
          },
          {
            "name": "PCT_FLF_RNG_Y",
            "expression": "calculate(sum('Fact - Bonus Plan'[PCT_FLF_RNG_WGHT]), FILTER('Fact - Bonus Plan','Fact - Bonus Plan'[PLN_PER_FRQ] = \"Y\") )",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0a1c0dab-5f7c-4c6d-a2ac-fb592ad72b9d"
          },
          {
            "name": "PCT_FLF_RNG_M",
            "expression": "calculate(sum('Fact - Bonus Plan'[PCT_FLF_RNG_WGHT]), FILTER('Fact - Bonus Plan','Fact - Bonus Plan'[PLN_PER_FRQ] = \"M\" && 'Fact - Bonus Plan'[PLN_TP] <> \"UBH/Total Income GH/M\") )",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "33f88c84-f261-4ac5-87ae-b00b9fb70479"
          },
          {
            "name": "PCT_FLF_RNG_M_GH",
            "expression": "calculate(sum('Fact - Bonus Plan'[PCT_FLF_RNG_WGHT]), FILTER('Fact - Bonus Plan','Fact - Bonus Plan'[PLN_PER_FRQ] = \"M\" && 'Fact - Bonus Plan'[PLN_TP] = \"UBH/Total Income GH/M\") )",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5aa38563-e680-460b-9948-3272d3ffc427"
          },
          {
            "name": "Measure 2",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "f75675df-476f-4d3a-9911-6559bf134469"
          }
        ],
        "partitions": [
          {
            "name": "Measures - Bonus Plan-0156de97-2304-4906-b2b7-c20510759ce8",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measures - Employee Hierarchy",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09b84a72-6f9f-4f00-86e2-120abd0c26a7",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5ec1af60-28bf-4c87-bec8-c216df0445f3",
        "measures": [
          {
            "name": "SC_WGHT",
            "expression": [
              "",
              "VAR res = SUM ( 'Fact - Employee Hierarchy'[SC_WGHT] )",
              "RETURN ",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"0%\" ) )",
              "    )"
            ],
            "lineageTag": "16a16167-24a1-4814-99bc-8ff71b124b65"
          }
        ],
        "partitions": [
          {
            "name": "Measures - Employee Hierarchy-7187c48f-f08c-4bbb-bf46-f38c82e622f8",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measures - General",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1ad904c-b8ff-4411-8569-39368f5be91f",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3ad0cb55-25c8-4482-bd4c-de605edbf0d4",
        "measures": [
          {
            "name": "Plan Text SC 3",
            "expression": "IF(MAX('Fact - Employee Hierarchy'[SC_TP]) = 3, \"ვადიანი და მოთხოვნამდე დეპოზიტები მინიმუმ 1000 ლარი\",  \"ვადიანი დეპოზიტები მინიმუმ 1000 ლარი\") ",
            "lineageTag": "a7cbe1e1-8353-4db5-9f48-1b7be80f3f50"
          },
          {
            "name": "Transparent Bonus Card text",
            "expression": "IF(MAX('Fact - Employee Hierarchy'[SC_TP]) <> 3, \"#333333\",  \"#FFFFFF00\") ",
            "lineageTag": "c2ecc5ce-ede9-4eca-a935-3ec933e22366"
          },
          {
            "name": "Transparent Bonus Weight Text",
            "expression": "IF(max('Fact - Employee Hierarchy'[SC_TP]) <> 3, \"#FFFFFF\",  \"#FFFFFF00\") ",
            "lineageTag": "25a60b06-bab9-459a-88f3-477285cabf00"
          },
          {
            "name": "Transparent SC",
            "expression": "IF(max('Fact - Employee Hierarchy'[SC_TP]) = 3, \"#dfddde\",  \"#FFFFFF00\") ",
            "lineageTag": "17760c07-e31f-4c0e-a790-552e09140d29"
          },
          {
            "name": "Transparent Bonus Weight background",
            "expression": "IF(max('Fact - Employee Hierarchy'[SC_TP]) <> 3, \"#2F3543\",  \"#FFFFFF00\") ",
            "lineageTag": "58890b1e-d95f-4f16-bdb9-d7cb5731a3f3"
          },
          {
            "name": "Transparent Bonus Card Background",
            "expression": "IF(max('Fact - Employee Hierarchy'[SC_TP]) <> 3, \"#F8F8FA\",  \"#FFFFFF00\") ",
            "lineageTag": "b42a3589-20ee-40cc-b4a0-17a0cf88fcc7"
          },
          {
            "name": "Transparent Bonus Background",
            "expression": "IF(max('Fact - Employee Hierarchy'[SC_TP]) <> 3, \"#CCCACB\",  \"#FFFFFF00\") ",
            "lineageTag": "de5044ff-4633-496c-bf85-17d7a63474c0"
          },
          {
            "name": "Transparent Bonus Arrow",
            "expression": "IF(max('Fact - Employee Hierarchy'[SC_TP]) <> 3, \"#0266B1\",  \"#FFFFFF00\") ",
            "lineageTag": "6d319d00-1a53-4bf1-9063-eff8280774e8"
          },
          {
            "name": "SC Operators Detail",
            "expression": "IF(MAX('Fact - Employee Hierarchy'[SC_TP]) = 3, \"SC - #C\", \"Bonus - SC - #AB\")",
            "lineageTag": "aaed67e7-793a-4b31-b8f8-0d563e8c5424"
          },
          {
            "name": "Subordinates Plan Text",
            "expression": "\"გეგმები - \" & MAX('Fact - Employee Hierarchy'[POS_DESCR])",
            "lineageTag": "67168684-c127-41e7-bfc0-48203a1cd9da"
          },
          {
            "name": "SME Background Cell Color Yelllow",
            "expression": "IF( ISBLANK(SUM ( 'Fact - Bonus Plan'[PCT_FLF_RNG] )), \"#ffffff\" , \"#FAE99F\")",
            "lineageTag": "7b3abb9a-2932-4f0e-a528-0ae7203c5ee4"
          },
          {
            "name": "SC Background Cell Color Yelllow",
            "expression": "IF( MAX('Fact - Employee Hierarchy'[POS_DESCR]) = \"ფილიალები\", \"#FAE99F\",\"#ffffff\")",
            "lineageTag": "cafd5a6c-9848-4485-a0a9-4e8e302a8f90"
          },
          {
            "name": "Subordinates Depo Text",
            "expression": "\"დეპოზიტები - \" & MAX('Fact - Employee Hierarchy'[POS_DESCR])",
            "lineageTag": "30ece87e-b228-4d02-bdf6-f9e01d85c0bb"
          },
          {
            "name": "Subordinates Loan Text",
            "expression": "\"სესხები - \" & MAX('Fact - Employee Hierarchy'[POS_DESCR])",
            "lineageTag": "753adf38-ee9c-46fa-abbc-99947df3ed7a"
          },
          {
            "name": "KPI Target",
            "expression": "1",
            "formatString": "0%;-0%;0%",
            "lineageTag": "85f8c262-9d83-4cd6-bb34-f53ff4f2d0fd"
          },
          {
            "name": "HM_LOAN_END_AMT_CHNG Color",
            "expression": [
              "",
              "var M = [LOAN_END_AMT_CHNG]",
              "var Y = [LOAN_END_AMT_CHNG_Y]",
              "var res = IF(MAX('Dimension - Delta Type'[Column1]) = \"წინა თვესთან\", M,Y)",
              "return if(res >=0 , \"#01B8AA\", \"#FD625E\")"
            ],
            "lineageTag": "879de01e-7e4c-425a-820b-1072ae8125e4"
          },
          {
            "name": "HM_DEPO_END_AMT_CHNG Color",
            "expression": [
              "",
              "var M = [DEPO_END_AMT_CHNG]",
              "var Y = [DEPO_END_AMT_CHNG_Y]",
              "var res = IF(MAX('Dimension - Delta Type'[Column1]) = \"წინა თვესთან\", M,Y)",
              "return if(res >=0 , \"#01B8AA\", \"#FD625E\")"
            ],
            "lineageTag": "a7a9137a-7f27-41cb-b2cb-2346da52d582"
          },
          {
            "name": "CARD_VAL_PCT",
            "expression": "FORMAT(MAX('Dimension - Bonus Tree'[CARD_VAL]), \"0%\")",
            "lineageTag": "ef9609c8-1780-4eb5-a61e-d145b0d70db8"
          },
          {
            "name": "Target Maximum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "1.3",
            "lineageTag": "aa0eea4a-8c9e-4a5b-b429-445c21720d76"
          },
          {
            "name": "Target Minimum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "0.6",
            "lineageTag": "240f0a8a-088f-4c1d-9315-90b1b1cf406c"
          },
          {
            "name": "Report Date",
            "expression": [
              "\"კალკულაციის თარიღი: \" & IF(MAX('Dimension - Calendar'[End of Month]) = CALCULATE(MAX('Dimension - Calendar'[End of Month]), ALL('Dimension - Calendar'[End of Month])),",
              "MAX('Update Date'[DT]), MAX('Dimension - Calendar'[End of Month]))"
            ],
            "lineageTag": "0f772250-8a8a-4446-bbdd-9df41675bf5d"
          },
          {
            "name": "CARD_VAL_PCT MORE PRECISE",
            "expression": "FORMAT(MAX('Dimension - Bonus Tree'[CARD_VAL]), \"0.0%\")",
            "lineageTag": "d0d3a475-3185-4d9c-b848-5cfe4513b3e3"
          },
          {
            "name": "Blank Card",
            "expression": "\"-\"",
            "lineageTag": "0f904229-3c94-4b68-b490-eabac37ede0e"
          },
          {
            "name": "FORMAT_DPD_CONS_LOAN",
            "expression": [
              "if(",
              "                        CALCULATE([LOAN_OVDU_AMT_PCT],'Dimension - Loan Product'[PROD_DESCR] = \"სამომხმარებლო სესხი\")>CALCULATE(MAX('Dimension - Bonus Tree'[CARD_VAL]),'Dimension - Bonus Tree'[ID] = 57),",
              "                        \"#fd625e\",",
              "                        \"#180018\")"
            ],
            "lineageTag": "11d29af2-0955-4d32-bfa0-b0f292c7b6ff"
          },
          {
            "name": "FORMAT_DPD_CREDIT_CARD",
            "expression": [
              "if(",
              "                        CALCULATE([LOAN_OVDU_AMT_PCT],'Dimension - Loan Product'[PROD_DESCR] = \"საკრედიტო ბარათი\")>CALCULATE(MAX('Dimension - Bonus Tree'[CARD_VAL]),'Dimension - Bonus Tree'[ID] = 56),",
              "                        \"#fd625e\",",
              "                        \"#180018\")"
            ],
            "lineageTag": "87b3a8d0-89ca-4185-9345-0b4a1d9cfecd"
          },
          {
            "name": "FORMAT_DPD_DEP_LOAN",
            "expression": [
              "if(",
              "                        CALCULATE([LOAN_OVDU_AMT_PCT],'Dimension - Loan Product'[PROD_DESCR] = \"დეპოზიტური სესხი\")>CALCULATE(MAX('Dimension - Bonus Tree'[CARD_VAL]),'Dimension - Bonus Tree'[ID] = 55),",
              "                        \"#fd625e\",",
              "                        \"#180018\")"
            ],
            "lineageTag": "6e6989b7-61ce-466c-8fbc-3901961d6a29"
          },
          {
            "name": "FORMAT_DPD_MORTGAGE",
            "expression": [
              "if(",
              "                        CALCULATE([LOAN_OVDU_AMT_PCT],'Dimension - Loan Product'[PROD_DESCR] = \"იპოთეკური სესხი\")>CALCULATE(MAX('Dimension - Bonus Tree'[CARD_VAL]),'Dimension - Bonus Tree'[ID] = 54),",
              "                        \"#fd625e\",",
              "                        \"#180018\")"
            ],
            "lineageTag": "d409f88a-91a3-435e-8a73-3c1ae24aab3d"
          }
        ],
        "partitions": [
          {
            "name": "Measures - General-f53a093f-048c-43a2-a529-b706c0a865d3",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact - Loans",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DW_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "286e374d-523f-44e0-9c69-6aae4462dcef",
            "sourceColumn": "DW_ID",
            "summarizeBy": "none"
          },
          {
            "name": "ROLE_TP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "7be54265-4cac-4e22-ae10-bd9bfd1c0f1c",
            "sortByColumn": "ROLE_TP_ID",
            "sourceColumn": "ROLE_TP",
            "summarizeBy": "none"
          },
          {
            "name": "PORTF_TP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c20c676-a2ee-4821-aee6-e69928d2f74f",
            "sourceColumn": "PORTF_TP",
            "summarizeBy": "none"
          },
          {
            "name": "CCY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "183d367a-fd6f-462e-8049-2c04a73c49d4",
            "sourceColumn": "CCY",
            "summarizeBy": "none"
          },
          {
            "name": "PROD_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "94e9922c-e1a5-4e02-9b11-59c53256bd0b",
            "sourceColumn": "PROD_ID",
            "summarizeBy": "none"
          },
          {
            "name": "LOAN_CNT_END",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "1bc8d175-e9ea-4260-b824-ee093b42ad52",
            "sourceColumn": "LOAN_CNT_END",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_CNT_START",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "9e541e9c-ab1d-4900-b771-219e18361ca0",
            "sourceColumn": "LOAN_CNT_START",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_CNT_START_Y",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "cd2c6f08-85a6-42a0-9d8d-56cf86ed10b3",
            "sourceColumn": "LOAN_CNT_START_Y",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_CURRMM_AMT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "dataType": "double",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "5bacd5b6-5e13-472e-bd47-ff4184147cbc",
            "sourceColumn": "LOAN_CURRMM_AMT",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_DISB_AMT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "dataType": "double",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "57f1bbcd-b1be-4d8c-ac25-71d1154464ed",
            "sourceColumn": "LOAN_DISB_AMT",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_DISB_IRR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "4f9afac8-3cee-4c21-98b1-64d04bfc78d2",
            "sourceColumn": "LOAN_DISB_IRR",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_DISB_TRS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "fe80764a-4338-4480-850e-1d6d44ee67ee",
            "sourceColumn": "LOAN_DISB_TRS",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_DISB_CNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "8d1b9377-d10d-462a-9d07-337421dd2348",
            "sourceColumn": "LOAN_DISB_CNT",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_END_AMT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "7c083d99-6d6f-4ab1-b530-3a75212eb77f",
            "sourceColumn": "LOAN_END_AMT",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_END_AMT_CHNG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "ac86a4ff-dbd7-4a5d-803d-21281171e8f3",
            "sourceColumn": "LOAN_END_AMT_CHNG",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_END_AMT_CHNG_Y",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "844940cf-01ca-4526-bb81-c2cd34d6fc92",
            "sourceColumn": "LOAN_END_AMT_CHNG_Y",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_END_AMT_CHNG_FX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "e9310579-0bb7-4f24-a2de-8e50b9d3eb2e",
            "sourceColumn": "LOAN_END_AMT_CHNG_FX",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_END_AMT_CHNG_FX_Y",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "6e36bd81-e4c5-4edc-8d1d-02cc78e0a242",
            "sourceColumn": "LOAN_END_AMT_CHNG_FX_Y",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_END_AMT_FX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "a1b40b06-e101-4574-98ac-ecb0b3e5a4c0",
            "sourceColumn": "LOAN_END_AMT_FX",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_END_AMT_IRR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "cc25a2be-a9e8-4f88-b36f-7a2475e12791",
            "sourceColumn": "LOAN_END_AMT_IRR",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_END_AMT_IRR_FX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "de0b9a35-135d-4fb2-99ec-fcbd926e0653",
            "sourceColumn": "LOAN_END_AMT_IRR_FX",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_END_AMT_TRS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "cb8ac8a7-86a5-4739-a44e-59becb8fc572",
            "sourceColumn": "LOAN_END_AMT_TRS",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_END_AMT_TRS_FX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "2c148ce0-8e20-48ac-a160-04b2f9608ab3",
            "sourceColumn": "LOAN_END_AMT_TRS_FX",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_NXTMM_PMT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "8ecf0d88-01f4-405e-b635-e4d83dbdf354",
            "sourceColumn": "LOAN_NXTMM_PMT",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_OVDU_AMT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "ed1c4e59-1d61-41e0-bafe-250b98f72976",
            "sourceColumn": "LOAN_OVDU_AMT",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_OVDU_AMT_PCT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "90992ad7-88f7-468d-990c-47a630486b8d",
            "sourceColumn": "LOAN_OVDU_AMT_PCT",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_PT_CNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6791b807-ce1b-4311-b840-fc6de648950e",
            "sourceColumn": "LOAN_PT_CNT",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_PT_CNT_NEW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e9dd0faa-2ea8-4408-b81b-c568446d177c",
            "sourceColumn": "LOAN_PT_CNT_NEW",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_START_AMT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "05543779-7051-4d58-b13f-0b97f827da96",
            "sourceColumn": "LOAN_START_AMT",
            "summarizeBy": "sum"
          },
          {
            "name": "LOAN_START_AMT_Y",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "f27f7306-f1c2-4a8a-8633-54c36908d405",
            "sourceColumn": "LOAN_START_AMT_Y",
            "summarizeBy": "sum"
          },
          {
            "name": "ROLE_TP_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "44494444-b1f5-4589-a515-4b6c7519b751",
            "sourceColumn": "ROLE_TP_ID",
            "summarizeBy": "count"
          },
          {
            "name": "ROLE_GRP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9737e45f-6fdb-4309-93b1-08a6d1269dd1",
            "sourceColumn": "ROLE_GRP",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d1c9eca8-194a-4d2d-b862-7349d27ac659",
        "partitions": [
          {
            "name": "Fact - Loans-d981b59d-2f04-4193-bf1d-2b6e6ee716a4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"select distinct DW_ID,#(lf)       ROLE_TP,#(lf)       PORTF_TP,#(lf)       CCY,#(lf)       PROD_ID,#(lf)       LOAN_CNT_END,#(lf)       LOAN_CNT_START,#(lf)       LOAN_CNT_START_Y,#(lf)       LOAN_CURRMM_AMT,#(lf)       LOAN_DISB_AMT,#(lf)       LOAN_DISB_IRR,#(lf)       LOAN_DISB_TRS,#(lf)       LOAN_DISB_CNT,#(lf)       LOAN_END_AMT,#(lf)       LOAN_END_AMT_CHNG,#(lf)       LOAN_END_AMT_CHNG_Y,#(lf)       LOAN_END_AMT_CHNG_FX,#(lf)       LOAN_END_AMT_CHNG_FX_Y,#(lf)       LOAN_END_AMT_FX,#(lf)       LOAN_END_AMT_IRR,#(lf)       LOAN_END_AMT_IRR_FX,#(lf)       LOAN_END_AMT_TRS,#(lf)       LOAN_END_AMT_TRS_FX,#(lf)       LOAN_NXTMM_PMT,#(lf)       LOAN_OVDU_AMT,#(lf)       LOAN_OVDU_AMT_PCT,#(lf)       LOAN_PT_CNT,#(lf)       LOAN_PT_CNT_NEW,#(lf)       LOAN_START_AMT,#(lf)       LOAN_START_AMT_Y,#(lf)                case when ROLE_TP = N'პრემიუმ ბანკირები' then 2 when ROLE_TP = N'ჯამურად' then 1 when ROLE_TP = N'საკრედიტო მენეჯერები' then 3 else 4 end ROLE_TP_ID,#(lf)                case when ROLE_TP = N'პრემიუმ ბანკირები' then N'პრემიუმ ბანკირები' when ROLE_TP = N'საკრედიტო მენეჯერები' then N'საკრედიტო მენეჯერები'#(lf)                    when RLS_GRP = 'PB' then N'პრემიუმ ბანკირები' when RLS_GRP = 'CM' then N'საკრედიტო მენეჯერები'#(lf)                    end ROLE_GRP#(lf)from WRK_MDB_BI_LOAN_DATA_FACT#(lf)where RLS_GRP in ('CM') AND snap_date >= '2023-08-31'#(lf)--and del_flag = 0#(lf)--and src_sys_id like '%0';\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact - Loans Hierarchy Bridge",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DW_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd9dec92-6c21-4d4d-9ffb-0ba1134b60b4",
            "sourceColumn": "DW_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DW_ID_LOAN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07747c29-89cb-4324-abcd-b7a7d72b2fb2",
            "sourceColumn": "DW_ID_LOAN",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "42d8e704-f96d-4087-b7fa-6edc15d884a8",
        "partitions": [
          {
            "name": "Fact - Loans Hierarchy Bridge-08b05505-529f-4cef-9da4-3c88850b03d7",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"select A.DW_ID, DW_ID_DEPO DW_ID_LOAN#(lf)from WRK_MDB_BI_LOAN_DATA_BRG_FACT A#(lf)join MDB_BI_EMP_HIER_FACT MEH on A.DW_ID = MEH.DW_ID#(lf)where MEH.RPT_ID = 3#(lf)  and MEH.SNAP_DATE >= '2023-08-31'#(lf)and meh.del_flag = 0;\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact - Depos Hierarchy Bridge",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DW_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1d26a9c-45ac-43e7-952e-f9f12746a3d5",
            "sourceColumn": "DW_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DW_ID_DEPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fdfd3069-210b-4cf1-823c-6a9bbd599640",
            "sourceColumn": "DW_ID_DEPO",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "72227b7e-ef9d-427f-8d88-dcdbbf9c8870",
        "partitions": [
          {
            "name": "Fact - Depos Hierarchy Bridge-b62f1266-5dad-4dfd-a8dd-7438eb67e2fa",
            "mode": "import",
            "queryGroup": "Bridges",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"select A.DW_ID, DW_ID_DEPO#(lf)from WRK_MDB_BI_DEPO_DATA_BRG_FACT A#(lf)join MDB_BI_EMP_HIER_FACT MEH on A.DW_ID = MEH.DW_ID#(lf)where MEH.RPT_ID = 3#(lf)  and MEH.SNAP_DATE >= '2023-08-31'#(lf)and meh.del_flag = 0;\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact - Depos",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DW_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4f5d94d-9689-4be7-9bef-7b512114f767",
            "sourceColumn": "DW_ID",
            "summarizeBy": "none"
          },
          {
            "name": "ROLE_TP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "f803be34-895c-44d6-812f-050120135806",
            "sortByColumn": "ROLE_TP_ID",
            "sourceColumn": "ROLE_TP",
            "summarizeBy": "none"
          },
          {
            "name": "CCY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0bf9cd1a-f160-4650-aa87-fb5a718bf481",
            "sourceColumn": "CCY",
            "summarizeBy": "none"
          },
          {
            "name": "PROD_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7e7c34c6-3cab-436e-b9f4-d07d044ea420",
            "sourceColumn": "PROD_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DEPO_CNT_END",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5fe6e5de-0b9f-446a-b04d-d94f621e3736",
            "sourceColumn": "DEPO_CNT_END",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_CNT_START",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "52de9e24-909a-4286-91ea-2ce51dfbd79c",
            "sourceColumn": "DEPO_CNT_START",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_CNT_START_Y",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4ac7cf11-24dd-43d3-a60f-a005282b8753",
            "sourceColumn": "DEPO_CNT_START_Y",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_CURRMM_PMT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "499798ec-9c06-4f9b-97e2-2aab593b39af",
            "sourceColumn": "DEPO_CURRMM_PMT",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_AMT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "a2a56f0e-b504-4cd8-aa92-443daba94320",
            "sourceColumn": "DEPO_DISB_AMT",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_AMT_IRR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "c6bad760-dfd3-44c7-970a-0dc0896d9bed",
            "sourceColumn": "DEPO_DISB_AMT_IRR",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_AMT_IRR_NC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "1f5839c8-8963-4b07-b864-5bc8e02f0fd7",
            "sourceColumn": "DEPO_DISB_AMT_IRR_NC",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_AMT_IRR_NM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "13a01c1c-ae93-4881-a105-f9c4fd2665b8",
            "sourceColumn": "DEPO_DISB_AMT_IRR_NM",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_AMT_NC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "5206da5c-dd83-46da-aae5-35367302b2db",
            "sourceColumn": "DEPO_DISB_AMT_NC",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_AMT_NM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "709be172-aaf1-45c0-8072-e6b998509e7b",
            "sourceColumn": "DEPO_DISB_AMT_NM",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_AMT_TRS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "3ef88b3d-8543-4876-89ad-1c8d97983ecd",
            "sourceColumn": "DEPO_DISB_AMT_TRS",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_AMT_TRS_NC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "26ef0179-1b3e-4717-8d60-3b78ef5fb97d",
            "sourceColumn": "DEPO_DISB_AMT_TRS_NC",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_AMT_TRS_NM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "144cec78-d775-457d-a7c3-7bbbb3df8f80",
            "sourceColumn": "DEPO_DISB_AMT_TRS_NM",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_CNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "66363d38-3868-47d6-8527-529832f0522c",
            "sourceColumn": "DEPO_DISB_CNT",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_CNT_NC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "49f04d7f-528a-49a0-8626-925df4a8a737",
            "sourceColumn": "DEPO_DISB_CNT_NC",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_CNT_NM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "31c430ef-f46e-4cfa-961f-fc4dc0cf11df",
            "sourceColumn": "DEPO_DISB_CNT_NM",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_END_AMT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "312e30e9-b378-4821-8e36-80235d41db3d",
            "sourceColumn": "DEPO_END_AMT",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_END_AMT_CHNG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "15daf87d-0d1f-4cfa-97e8-a6ce3c375b1c",
            "sourceColumn": "DEPO_END_AMT_CHNG",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_END_AMT_CHNG_Y",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "5fadaad8-0f6c-451f-adab-b0b562021841",
            "sourceColumn": "DEPO_END_AMT_CHNG_Y",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_END_AMT_CHNG_FX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "d895aae9-9356-4e61-9514-a0345597655c",
            "sourceColumn": "DEPO_END_AMT_CHNG_FX",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_END_AMT_CHNG_FX_Y",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "d2ba949e-481f-40d5-bcb0-ba4015868ff2",
            "sourceColumn": "DEPO_END_AMT_CHNG_FX_Y",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_END_AMT_FX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "f6ab63b2-33c9-4d7d-972b-d4fab24daec0",
            "sourceColumn": "DEPO_END_AMT_FX",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_END_AMT_IRR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "25017cd0-dbb3-4404-8d79-1ae15aef75b3",
            "sourceColumn": "DEPO_END_AMT_IRR",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_END_AMT_IRR_FX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "fa247ae2-d37d-47ef-9478-2cd4b3cbb9e9",
            "sourceColumn": "DEPO_END_AMT_IRR_FX",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_END_AMT_TRS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "de47f043-81d5-4bbe-a828-565acc863d53",
            "sourceColumn": "DEPO_END_AMT_TRS",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_END_AMT_TRS_FX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "986413ce-d906-49aa-bb0b-88e816a7f2a0",
            "sourceColumn": "DEPO_END_AMT_TRS_FX",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_NXTMM_PMT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "b1be40bd-2ccc-4b43-8c19-20aa93c79a6f",
            "sourceColumn": "DEPO_NXTMM_PMT",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_PT_CNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a3c3849d-630e-4e7e-b51a-40b6ccc04c9b",
            "sourceColumn": "DEPO_PT_CNT",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_PT_CNT_NEW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c1cd806d-14fe-41d1-8ae5-077d06426db3",
            "sourceColumn": "DEPO_PT_CNT_NEW",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_START_AMT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "afebc8f9-ce92-4975-bfca-39f925939a05",
            "sourceColumn": "DEPO_START_AMT",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_START_AMT_Y",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "ca8a1916-3a04-4625-97fe-416002db9859",
            "sourceColumn": "DEPO_START_AMT_Y",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_AMT_NO_TRS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2568f4d7-5234-4a2d-9297-f27e30dc9ca4",
            "sourceColumn": "DEPO_DISB_AMT_NO_TRS",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_AMT_NO_IRR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "22a62dfc-3e39-4bdc-ba67-9b76d8cab389",
            "sourceColumn": "DEPO_DISB_AMT_NO_IRR",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_END_AMT_NO_TRS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6ee83104-bd48-4eee-9eed-4d3ea940a0eb",
            "sourceColumn": "DEPO_END_AMT_NO_TRS",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_END_AMT_NO_IRR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "25bac9f5-6e11-4913-9756-5cb72325f117",
            "sourceColumn": "DEPO_END_AMT_NO_IRR",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_END_AMT_NO_TRS_FX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ed44395f-bcf0-4802-b4d5-346ee46ee103",
            "sourceColumn": "DEPO_END_AMT_NO_TRS_FX",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_END_AMT_NO_IRR_FX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "96051e93-abb3-4eb0-a01a-debc8f6234b1",
            "sourceColumn": "DEPO_END_AMT_NO_IRR_FX",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_AMT_NO_TRS_NC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "32f6ff93-8256-4b8a-bf95-f3c89bfb8523",
            "sourceColumn": "DEPO_DISB_AMT_NO_TRS_NC",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_AMT_NO_TRS_NM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f5c5b6f7-847f-408b-beb9-965557b1c7ba",
            "sourceColumn": "DEPO_DISB_AMT_NO_TRS_NM",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_AMT_NO_IRR_NC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0cd2827d-f868-4d7d-90d6-db02a35d3ba0",
            "sourceColumn": "DEPO_DISB_AMT_NO_IRR_NC",
            "summarizeBy": "sum"
          },
          {
            "name": "DEPO_DISB_AMT_NO_IRR_NM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "04034b89-889a-4e99-9f82-21b658d8830f",
            "sourceColumn": "DEPO_DISB_AMT_NO_IRR_NM",
            "summarizeBy": "sum"
          },
          {
            "name": "ROLE_TP_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2aac7590-de19-42ba-a109-9d5b560c1132",
            "sourceColumn": "ROLE_TP_ID",
            "summarizeBy": "count"
          },
          {
            "name": "ROLE_GRP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d746e08e-55a7-4717-b180-e7de1a080ff1",
            "sourceColumn": "ROLE_GRP",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "39380215-dbb1-4585-808e-9675c9dc30e1",
        "partitions": [
          {
            "name": "Fact - Depos-5c572ab5-b434-4f18-a27e-c2f1c66db2d8",
            "mode": "import",
            "queryGroup": "Portflolios",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"select DW_ID,#(lf)       ROLE_TP,#(lf)       CCY,#(lf)       PROD_ID,#(lf)       DEPO_CNT_END,#(lf)       DEPO_CNT_START,#(lf)       DEPO_CNT_START_Y,#(lf)       DEPO_CURRMM_PMT,#(lf)       DEPO_DISB_AMT,#(lf)       DEPO_DISB_AMT_NO_TRS,#(lf)       DEPO_DISB_AMT_NO_IRR,#(lf)       DEPO_DISB_AMT_IRR,#(lf)       DEPO_DISB_AMT_IRR_NC,#(lf)       DEPO_DISB_AMT_IRR_NM,#(lf)       DEPO_DISB_AMT_NC,#(lf)       DEPO_DISB_AMT_NM,#(lf)       DEPO_DISB_AMT_TRS,#(lf)       DEPO_DISB_AMT_TRS_NC,#(lf)       DEPO_DISB_AMT_TRS_NM,#(lf)       DEPO_DISB_CNT,#(lf)       DEPO_DISB_CNT_NC,#(lf)       DEPO_DISB_CNT_NM,#(lf)       DEPO_END_AMT,#(lf)       DEPO_END_AMT_NO_TRS,#(lf)       DEPO_END_AMT_NO_IRR,#(lf)       DEPO_END_AMT_CHNG,#(lf)       DEPO_END_AMT_CHNG_Y,#(lf)       DEPO_END_AMT_CHNG_FX,#(lf)       DEPO_END_AMT_CHNG_FX_Y,#(lf)       DEPO_END_AMT_FX,#(lf)       DEPO_END_AMT_IRR,#(lf)       DEPO_END_AMT_IRR_FX,#(lf)       DEPO_END_AMT_TRS,#(lf)       DEPO_END_AMT_TRS_FX,#(lf)       DEPO_NXTMM_PMT,#(lf)       DEPO_PT_CNT,#(lf)       DEPO_PT_CNT_NEW,#(lf)       DEPO_START_AMT,#(lf)       DEPO_START_AMT_Y,#(lf)       DEPO_END_AMT_NO_TRS_FX,#(lf)       DEPO_END_AMT_NO_IRR_FX,#(lf)       DEPO_DISB_AMT_NO_TRS_NC,#(lf)       DEPO_DISB_AMT_NO_TRS_NM,#(lf)       DEPO_DISB_AMT_NO_IRR_NC,#(lf)       DEPO_DISB_AMT_NO_IRR_NM,#(lf)       case#(lf)           when ROLE_TP = N'პრემიუმ ბანკირები' then 2#(lf)           when ROLE_TP = N'ჯამურად' then 1#(lf)           when ROLE_TP = N'საკრედიტო მენეჯერები' then 3#(lf)           else 4 end ROLE_TP_ID,#(lf)                case when ROLE_TP = N'პრემიუმ ბანკირები' then N'პრემიუმ ბანკირები' when ROLE_TP = N'საკრედიტო მენეჯერები' then N'საკრედიტო მენეჯერები'#(lf)                    when RSL_GRP = 'PB' then N'პრემიუმ ბანკირები' when RSL_GRP = 'CM' then N'საკრედიტო მენეჯერები'#(lf)                    end ROLE_GRP#(lf)from WRK_MDB_BI_DEPO_DATA_FACT#(lf)where RSL_GRP in ('CM') AND snap_date >= '2023-08-31'#(lf)--and DEL_FLAG = 0#(lf)--and SRC_SYS_ID like '%0'#(lf)--and del_flag = 0;\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Subordinates Plan",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "936579020f46496b9b13b681c515250f"
          }
        ],
        "columns": [
          {
            "name": "Subordinates Plan",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "c007edfa-934e-4a87-885d-e3b02c22e860",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Subordinates Plan Fields"
                }
              ]
            },
            "sortByColumn": "Subordinates Plan Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Subordinates Plan Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "06879c7a-a37c-465f-8592-2d7324a9903d",
            "sortByColumn": "Subordinates Plan Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Subordinates Plan Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "ac1fa88e-80ab-48f0-9334-f0de7a51058d",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "KPI_GRP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF('Subordinates Plan'[Subordinates Plan Order] in {0,1,2,3,4,5,6,7,8,9}, \"პრემიუმ ბანკირების KPI\",",
              "IF('Subordinates Plan'[Subordinates Plan Order] in {10,11,12,13}, \"საკრედიტო მენეჯერების KPI\",",
              "IF('Subordinates Plan'[Subordinates Plan Order] in {14,15,16,17}, \"SME ბანკირების KPI\",",
              " IF('Subordinates Plan'[Subordinates Plan Order] in {18,19,20,21,22,23,24,25,26,27,28,29,30,31,32}, \"საოპერაციო KPI\", \"წლიური შესრულება\"))))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "d6634815-93fb-41aa-bdfe-35cbbd8de3f4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "KPI_TP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF('Subordinates Plan'[Subordinates Plan Order] in {0,10,14,18,33}, \"KPI\",",
              "IF('Subordinates Plan'[Subordinates Plan Order] in {19,29}, \"კალათა\",",
              "IF('Subordinates Plan'[Subordinates Plan Order] in {3,6,9,13,17,22,25,28,32,36,39}, \"შესრულება\",\"გეგმა-ფაქტი\"",
              ")))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "cc495a1b-7660-4539-bd42-5894ce3c64ab",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "b49d2504-1322-4d8d-b24e-6ed00ecddabe",
        "partitions": [
          {
            "name": "Subordinates Plan-86e1d4ea-ad98-4a8b-b726-580a4e0792e3",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"პრემიუმ ბანკირების KPI\", NAMEOF('Measures - Bonus Plan'[SB_PB_KPI]), 0),",
                "    (\"ახალი კლიენტი - ფაქტი\", NAMEOF('Measures - Bonus Plan'[SB_FCT_VAL ახალი კლიენტი]), 1),",
                "    (\"ახალი კლიენტი - გეგმა\", NAMEOF('Measures - Bonus Plan'[SB_PLN_VAL ახალი კლიენტი]), 2),",
                "    (\"ახალი კლიენტი - შესრულება min/max რეინჯში\", NAMEOF('Measures - Bonus Plan'[SB_PCT_FLF_RNG ახალი კლიენტი]), 3),",
                "    (\"დეპოზიტების პორტფელის ზრდა PB - ფაქტი\", NAMEOF('Measures - Bonus Plan'[SB_FCT_VAL დეპოზიტების პორტფელის ზრდა]), 4),",
                "    (\"დეპოზიტების პორტფელის ზრდა PB - გეგმა\", NAMEOF('Measures - Bonus Plan'[SB_PLN_VAL დეპოზიტების პორტფელის ზრდა]), 5),",
                "    (\"დეპოზიტების პორტფელის ზრდა PB - შესრულება min/max რეინჯში\", NAMEOF('Measures - Bonus Plan'[SB_PCT_FLF_RNG დეპოზიტების პორტფელის ზრდა]), 6),",
                "    (\"სესხების პორტფელის ზრდა PB- ფაქტი\", NAMEOF('Measures - Bonus Plan'[SB_FCT_VAL სესხების პორტფელის ზრდა PB]), 7),",
                "    (\"სესხების პორტფელის ზრდა PB- გეგმა\", NAMEOF('Measures - Bonus Plan'[SB_PLN_VAL სესხების პორტფელის ზრდა PB]), 8),",
                "    (\"სესხების პორტფელის ზრდა PB- შესრულება min/max რეინჯში\", NAMEOF('Measures - Bonus Plan'[SB_PCT_FLF_RNG სესხების პორტფელის ზრდა PB]), 9),",
                "    (\"საკრედიტო მენეჯერების KPI\", NAMEOF('Measures - Bonus Plan'[SB_CM_KPI]), 10),",
                "    (\"პორტფელის ზრდა - ფაქტი\", NAMEOF('Measures - Bonus Plan'[SB_FCT_VAL პორტფელის ზრდა]), 11),",
                "    (\"პორტფელის ზრდა - გეგმა\", NAMEOF('Measures - Bonus Plan'[SB_PLN_VAL პორტფელის ზრდა]), 12),",
                "    (\"პორტფელის ზრდა - შესრულება min/max რეინჯში\", NAMEOF('Measures - Bonus Plan'[SB_PCT_FLF_RNG პორტფელის ზრდა]), 13),",
                "    (\"SME ბანკირების KPI\", NAMEOF('Measures - Bonus Plan'[SB_SM_KPI]), 14),",
                "    (\"სესხების პორტფელის ზრდა SME- ფაქტი\", NAMEOF('Measures - Bonus Plan'[SB_FCT_VAL სესხების პორტფელის ზრდა SME]), 15),",
                "    (\"სესხების პორტფელის ზრდა SME- გეგმა\", NAMEOF('Measures - Bonus Plan'[SB_PLN_VAL სესხების პორტფელის ზრდა SME]), 16),",
                "    (\"სესხების პორტფელის ზრდა SME- შესრულება min/max რეინჯში\", NAMEOF('Measures - Bonus Plan'[SB_PCT_FLF_RNG სესხების პორტფელის ზრდა SME]), 17),",
                "    (\"საოპერაციო KPI\", NAMEOF('Measures - Bonus Plan'[SB_OP_KPI]), 18),",
                "    (\"პირველი კალათა\", NAMEOF('Measures - Bonus Plan'[BT_PCT_FLF_RNG_WGHT პირველი კალათა]), 19),",
                "    (\"ვადიანი და მოთხოვნამდე - ფაქტი\", NAMEOF('Measures - Bonus Plan'[BT_FCT_VAL ვადიანი და მოთხოვნამდე]), 20),",
                "    (\"ვადიანი და მოთხოვნამდე - გეგმა\", NAMEOF('Measures - Bonus Plan'[BT_PLN_VAL ვადიანი და მოთხოვნამდე]), 21),",
                "    (\"ვადიანი და მოთხოვნამდე - შესრულება min/max რეინჯში\", NAMEOF('Measures - Bonus Plan'[BT_PCT_FLF_RNG ვადიანი და მოთხოვნამდე]), 22),",
                "    (\"ვადიანი - ფაქტი\", NAMEOF('Measures - Bonus Plan'[BT_FCT_VAL ვადიანი]), 23),",
                "    (\"ვადიანი - გეგმა\", NAMEOF('Measures - Bonus Plan'[BT_PLN_VAL ვადიანი]), 24),",
                "    (\"ვადიანი - შესრულება min/max რეინჯში\", NAMEOF('Measures - Bonus Plan'[BT_PCT_FLF_RNG ვადიანი]), 25),",
                "    (\"მოთხოვნამდე - ფაქტი\", NAMEOF('Measures - Bonus Plan'[BT_FCT_VAL მოთხოვნამდე]), 26),",
                "    (\"მოთხოვნამდე - გეგმა\", NAMEOF('Measures - Bonus Plan'[BT_PLN_VAL მოთხოვნამდე]), 27),",
                "    (\"მოთხოვნამდე - შესრულება min/max რეინჯში\", NAMEOF('Measures - Bonus Plan'[BT_PCT_FLF_RNG მოთხოვნამდე]), 28),",
                "    (\"მეორე კალათა\", NAMEOF('Measures - Bonus Plan'[BT_PCT_FLF_RNG_WGHT მეორე კალათა]), 29),",
                "    (\"სხვა - ფაქტი\", NAMEOF('Measures - Bonus Plan'[BT_FCT_VAL სხვა]), 30),",
                "    (\"სხვა - გეგმა\", NAMEOF('Measures - Bonus Plan'[BT_PLN_VAL სხვა]), 31),",
                "    (\"სხვა - შესრულება min/max რეინჯში\", NAMEOF('Measures - Bonus Plan'[BT_PCT_FLF_RNG სხვა]), 32),",
                "    (\"წლიური გეგმის შესრულება\", NAMEOF('Measures - Bonus Plan'[SB_PCT_FLF_RNG პორტფელის ზრდა - წლიური - PS]), 33),",
                "    (\"დეპოზიტების პორტფელის ზრდა - ფაქტი\", NAMEOF('Measures - Bonus Plan'[SB_FCT_VAL დეპოზიტების პორტფელის ზრდა - წლიური - PS]), 34),",
                "    (\"დეპოზიტების პორტფელის ზრდა - გეგმა\", NAMEOF('Measures - Bonus Plan'[SB_PLN_VAL დეპოზიტების პორტფელის ზრდა - წლიური - PS]), 35),",
                "    (\"დეპოზიტების პორტფელის ზრდა - შესრულება\", NAMEOF('Measures - Bonus Plan'[SB_PCT_FLF_RNG დეპოზიტების პორტფელის ზრდა - წლიური - PS]), 36),",
                "    (\"სესხების პორტფელის ზრდა - ფაქტი\", NAMEOF('Measures - Bonus Plan'[SB_FCT_VAL სესხების პორტფელის ზრდა - წლიური - PS]), 37),",
                "    (\"სესხების პორტფელის ზრდა - გეგმა\", NAMEOF('Measures - Bonus Plan'[SB_PLN_VAL სესხების პორტფელის ზრდა - წლიური - PS]), 38),",
                "    (\"სესხების პორტფელის ზრდა - შესრულება\", NAMEOF('Measures - Bonus Plan'[SB_PCT_FLF_RNG სესხების პორტფელის ზრდა - წლიური - PS]), 39)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Subordinates Operations",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ab191a8dd412479da08f4f53aad4b94f"
          }
        ],
        "columns": [
          {
            "name": "Subordinates Operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "a152a575-da69-4c86-9519-152686de2128",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Subordinates Operations Fields"
                }
              ]
            },
            "sortByColumn": "Subordinates Operations Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Subordinates Operations Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "7db2245d-4fa0-4529-b56f-326a0791b3b0",
            "sortByColumn": "Subordinates Operations Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Subordinates Operations Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "8dbffb89-2871-4a32-96f3-e3fd388a7da0",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "KPI_GRP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF('Subordinates Operations'[Subordinates Operations Order] in {0,2,4,6},\"არასაბონუსე პარამეტრი\",",
              "IF('Subordinates Operations'[Subordinates Operations Order] < 14,  ",
              "IF('Subordinates Operations'[Subordinates Operations Order] in {2,3,6,7}, \"საბონუსე პარამეტრი - პირველი კალათა\", \"საბონუსე პარამეტრი - მეორე კალათა\"),",
              "\"არასაბონუსე პარამეტრი\"))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "24f51280-46e9-4158-a9d2-58be6fb72ea4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "KPI_TP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF('Subordinates Operations'[Subordinates Operations Order] in {0,2,4,6,19,21,23,25,27,29} , \"მოცულობა\", \"რაოდენობა\")",
            "isDataTypeInferred": true,
            "lineageTag": "5fb5ed7b-c0c8-4b25-9d9d-7bec8161b8e6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "254219ca-ff71-410b-9b28-cd9d6c87f282",
        "partitions": [
          {
            "name": "Subordinates Operations-c78870f1-29f5-4b4d-8767-218927ebd108",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"მოთხოვნამდე 100 - მოცულობა\", NAMEOF('Measures - Opers'[DEM_DEP_100_AMT]), 0),",
                "    (\"მოთხოვნამდე 100 - რაოდენობა\", NAMEOF('Measures - Opers'[DEM_DEP_100_CNT]), 1),",
                "    (\"მოთხოვნამდე 1000 - მოცულობა\", NAMEOF('Measures - Opers'[DEM_DEP_1000_AMT]), 2),",
                "    (\"მოთხოვნამდე 1000 - რაოდენობა\", NAMEOF('Measures - Opers'[DEM_DEP_1000_CNT]), 3),",
                "    (\"ვადიანი 100 - მოცულობა\", NAMEOF('Measures - Opers'[TIME_DEP_100_AMT]), 4),",
                "    (\"ვადიანი 100 - რაოდენობა\", NAMEOF('Measures - Opers'[TIME_DEP_100_CNT]), 5),",
                "    (\"ვადიანი 1000 - მოცულობა\", NAMEOF('Measures - Opers'[TIME_DEP_1000_AMT]), 6),",
                "    (\"ვადიანი 1000 - რაოდენობა\", NAMEOF('Measures - Opers'[TIME_DEP_1000_CNT]), 7),",
                "    (\"სადებეტო ბარათის გაცემა\", NAMEOF('Measures - Opers'[DB_CARD_CNT]), 8),",
                "    (\"საკრედიტო ბარათის გაცემა\", NAMEOF('Measures - Opers'[CR_CARD_CNT]), 9),",
                "    (\"პაკეტური სერვისის ცვლილება\", NAMEOF('Measures - Opers'[CHNG_PCKG_CNT]), 10),",
                "    (\"დაზღვევა\", NAMEOF('Measures - Opers'[INSRNS_CNT]), 11),",
                "    (\"პაკეტური შეთავაზება\", NAMEOF('Measures - Opers'[PCKG_CNT]), 12),",
                "    (\"ტოკენის გაყიდვა\", NAMEOF('Measures - Opers'[TOKEN_CNT]), 13),",
                "    (\"ახალი კლიენტი\", NAMEOF('Measures - Opers'[NEW_PT_CNT]), 14),",
                "    (\"ინტერნეტ ბანკის რეგისტრაცია\", NAMEOF('Measures - Opers'[INT_BANK_REG_CNT]), 15),",
                "    (\"ანგარიშის დახურვა\", NAMEOF('Measures - Opers'[ACC_CLOS_CNT]), 16),",
                "    (\"ბარათის აქტივაცია\", NAMEOF('Measures - Opers'[CARD_ACT_CNT]), 17),",
                "    (\"ბარათის აქტივაცია - სახელფასო\", NAMEOF('Measures - Opers'[SLRY_CARD_ACT_CNT]), 18),",
                "    (\"სავალუტო გადარიცხვა\", NAMEOF('Measures - Opers'[CCY_TRANSFER_AMT]), 19),",
                "    (\"სავალუტო გადარიცხვა - რაოდენობა\", NAMEOF('Measures - Opers'[CCY_TRANSFER_CNT]), 20),",
                "    (\"სალარე გადარიცხვა\", NAMEOF('Measures - Opers'[SLRY_TRANSFER_AMT]), 21),",
                "    (\"სალარე გადარიცხვა - რაოდენობა\", NAMEOF('Measures - Opers'[SLRY_TRANSFER_CNT]), 22),",
                "    (\"შემოსავლები სალაროში\", NAMEOF('Measures - Opers'[INN_SLRY_AMT]), 23),",
                "    (\"შემოსავლები სალაროში - რაოდენობა\", NAMEOF('Measures - Opers'[INN_SLRY_CNT]), 24),",
                "    (\"გასავლები სალაროდან\", NAMEOF('Measures - Opers'[OUT_SLRY_AMT]), 25),",
                "    (\"გასავლები სალაროდან - რაოდენობა\", NAMEOF('Measures - Opers'[OUT_SLRY_CNT]), 26),",
                "    (\"კონვერტაცია ნაღდი ფულით\", NAMEOF('Measures - Opers'[CONV_CASH_AMT]), 27),",
                "    (\"კონვერტაცია ნაღდი ფულით - რაოდენობა\", NAMEOF('Measures - Opers'[CONV_CASH_CNT]), 28),",
                "    (\"კონვერტაცია უნაღდო\", NAMEOF('Measures - Opers'[CONV_NOCASH_AMT]), 29),",
                "    (\"კონვერტაცია უნაღდო - რაოდენობა\", NAMEOF('Measures - Opers'[CONV_NOCASH_CNT]), 30)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Measures - Opers",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "294ded44-bdac-409c-92e9-ad3becb5848c",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c24be640-3821-424b-8416-21cd9ee8fb86",
        "measures": [
          {
            "name": "TOKEN_CNT",
            "expression": "SUM('Fact - Opers'[TOKEN_CNT])",
            "formatString": "#,0",
            "lineageTag": "1b2c6eb5-8d73-48fc-99e6-bfb8202c67e5"
          },
          {
            "name": "TIME_DEP_100_CNT",
            "expression": "sum('Fact - Opers'[TIME_DEP_100_CNT]) ",
            "formatString": "#,0",
            "lineageTag": "7c310a7b-316a-48cd-acc5-1b535fed042e"
          },
          {
            "name": "TIME_DEP_1000_CNT",
            "expression": "sum('Fact - Opers'[TIME_DEP_1000_CNT]) ",
            "formatString": "#,0",
            "lineageTag": "19a37212-4128-42f8-9ed9-ffaa0ac023c4"
          },
          {
            "name": "TIME_DEP_100_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "sum('Fact - Opers'[TIME_DEP_100_AMT]) ",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "6a37f84e-0136-49d7-89fd-f4b3130e48e1"
          },
          {
            "name": "TIME_DEP_1000_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "sum('Fact - Opers'[TIME_DEP_1000_AMT]) ",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "5cdcdaeb-10c6-4af6-816d-476deffac45a"
          },
          {
            "name": "SLRY_TRANSFER_CNT",
            "expression": "sum('Fact - Opers'[SLRY_TRANSFER_CNT])",
            "formatString": "#,0",
            "lineageTag": "9221b684-c111-4b64-93ba-cc96fdd04e4b"
          },
          {
            "name": "SLRY_TRANSFER_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "SUM('Fact - Opers'[SLRY_TRANSFER_AMT])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "8b13a415-e4a7-4474-b542-10b83b6aedcc"
          },
          {
            "name": "SLRY_CARD_ACT_CNT",
            "expression": "SUM('Fact - Opers'[SLRY_CARD_ACT_CNT])",
            "formatString": "#,0",
            "lineageTag": "e9c41876-8de0-4269-a610-36592c4db521"
          },
          {
            "name": "PCKG_CNT",
            "expression": "SUM('Fact - Opers'[PCKG_CNT])",
            "formatString": "#,0",
            "lineageTag": "9562478b-3c3d-4f63-aa70-50ebb7a12b0e"
          },
          {
            "name": "OUT_SLRY_CNT",
            "expression": "SUM('Fact - Opers'[OUT_SLRY_CNT])",
            "formatString": "#,0",
            "lineageTag": "d787ca2d-bc74-4dff-a7fb-f6b5b6a83175"
          },
          {
            "name": "OUT_SLRY_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "SUM('Fact - Opers'[OUT_SLRY_AMT])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "e9aad8d1-3b3d-4bf9-8e43-17c388dbe822"
          },
          {
            "name": "NEW_PT_CNT",
            "expression": "SUM('Fact - Opers'[NEW_PT_CNT])",
            "formatString": "#,0",
            "lineageTag": "e77f22e4-9d69-41be-ac1e-cd431a4f8784"
          },
          {
            "name": "INT_BANK_REG_CNT",
            "expression": "SUM('Fact - Opers'[INT_BANK_REG_CNT])",
            "formatString": "#,0",
            "lineageTag": "94d1fbbd-9e0c-4f33-91ff-c63f06ee281f"
          },
          {
            "name": "INSRNS_CNT",
            "expression": "SUM('Fact - Opers'[INSRNS_CNT])",
            "formatString": "#,0",
            "lineageTag": "b14669de-2d9c-4b9b-a3f3-84224f3bb783"
          },
          {
            "name": "INN_SLRY_CNT",
            "expression": "SUM('Fact - Opers'[INN_SLRY_CNT])",
            "formatString": "#,0",
            "lineageTag": "a8ec5306-26a5-4638-b3bb-31a0c324454d"
          },
          {
            "name": "INN_SLRY_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "SUM('Fact - Opers'[INN_SLRY_AMT])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "7a01b05a-caa3-49a3-84cc-34dc06c52f7b"
          },
          {
            "name": "DEM_DEP_1000_CNT",
            "expression": "SUM('Fact - Opers'[DEM_DEP_1000_CNT])",
            "formatString": "#,0",
            "lineageTag": "02ac3234-9aaa-42c3-8af4-add1d1409846"
          },
          {
            "name": "DEM_DEP_1000_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "SUM('Fact - Opers'[DEM_DEP_1000_AMT])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "3aad32cf-95df-4452-9538-38c3391dff9a"
          },
          {
            "name": "DEM_DEP_100_CNT",
            "expression": "SUM('Fact - Opers'[DEM_DEP_100_CNT])",
            "formatString": "#,0",
            "lineageTag": "68951b98-6067-4982-ab85-b583f40e42c5"
          },
          {
            "name": "DEM_DEP_100_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "SUM('Fact - Opers'[DEM_DEP_100_AMT])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "24c49ab2-431a-42a6-ae08-75602c0e4cf8"
          },
          {
            "name": "DB_CARD_CNT",
            "expression": "SUM('Fact - Opers'[DB_CARD_CNT])",
            "formatString": "#,0",
            "lineageTag": "71760690-d633-4b93-9484-a54c5107f466"
          },
          {
            "name": "CR_CARD_CNT",
            "expression": "SUM('Fact - Opers'[CR_CARD_CNT])",
            "formatString": "#,0",
            "lineageTag": "20f38853-132d-4067-950a-abad8c5bcf22"
          },
          {
            "name": "CONV_NOCASH_CNT",
            "expression": "SUM('Fact - Opers'[CONV_NOCASH_CNT])",
            "formatString": "#,0",
            "lineageTag": "9acefaf0-68d4-469e-816c-18a5d95176f8"
          },
          {
            "name": "CONV_NOCASH_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "SUM('Fact - Opers'[CONV_NOCASH_AMT])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "c4b01d83-7bcf-4a09-a845-50fa39de042c"
          },
          {
            "name": "CONV_CASH_CNT",
            "expression": "SUM('Fact - Opers'[CONV_CASH_CNT])",
            "formatString": "#,0",
            "lineageTag": "5a68e903-a6d2-40ff-a35f-16c7edb17608"
          },
          {
            "name": "CONV_CASH_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "SUM('Fact - Opers'[CONV_CASH_AMT])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "e1e45bb2-a63c-45fa-811a-2f34fc18be1a"
          },
          {
            "name": "CHNG_PCKG_CNT",
            "expression": "SUM('Fact - Opers'[CHNG_PCKG_CNT])",
            "formatString": "#,0",
            "lineageTag": "c7f7deec-e4b3-4af4-bf85-78947747e803"
          },
          {
            "name": "CCY_TRANSFER_CNT",
            "expression": "SUM('Fact - Opers'[CCY_TRANSFER_CNT])",
            "formatString": "#,0",
            "lineageTag": "6551869c-37e9-404a-a1ed-22f3616bccc0"
          },
          {
            "name": "CCY_TRANSFER_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "sum('Fact - Opers'[CCY_TRANSFER_AMT])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "3a5ef7ad-b8f7-406b-b685-f540e57875cf"
          },
          {
            "name": "CARD_ACT_CNT",
            "expression": "SUM('Fact - Opers'[CARD_ACT_CNT])",
            "formatString": "#,0",
            "lineageTag": "fbd11d44-26ca-47e3-ad0f-801efdbbe9b3"
          },
          {
            "name": "ACC_CLOS_CNT",
            "expression": "SUM('Fact - Opers'[ACC_CLOS_CNT])",
            "formatString": "#,0",
            "lineageTag": "f14a1acc-d492-4c41-9fa2-c2a57736509c"
          }
        ],
        "partitions": [
          {
            "name": "Measures - Opers-c629bae4-51c7-48ec-ba1b-7c297a272432",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dimension - FX",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a7a65368-212b-4a5a-87f0-f8a70b915600",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "FX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "42b4d792-443a-4c09-a24c-f8e46f9f8161",
            "sortByColumn": "ID",
            "sourceColumn": "FX",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "22f89cd6-a730-4961-9e88-5281510ab626",
        "partitions": [
          {
            "name": "Dimension - FX-5e44a896-fc48-474d-a969-22335aa40489",
            "mode": "import",
            "queryGroup": "Helper Dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUXrYPPNh8+KHzQseNi982DwDSCo8bF71sHnqw+ZZYD6QnPKweSJcbtLD5glg5UDRFUBSKVYnWskIbNJssCIgORnMmANXqYBhy3Sl2FgA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, FX = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"ID\", Int64.Type}, {\"FX\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measures - Loans",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f510ed4-72db-45c9-bb73-5ead86d804e7",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1aaf8105-9393-4342-a16a-309c418528b7",
        "measures": [
          {
            "name": "LOAN_CNT_END",
            "expression": "SUM('Fact - Loans'[LOAN_CNT_END])",
            "formatString": "#,0",
            "lineageTag": "a845e772-9d20-4539-b28e-86e1554fc4ac"
          },
          {
            "name": "LOAN_CNT_START",
            "expression": "SUM('Fact - Loans'[LOAN_CNT_START])",
            "formatString": "#,0",
            "lineageTag": "03307c22-f8d5-4445-b3c7-300955854c76"
          },
          {
            "name": "LOAN_CNT_START_Y",
            "expression": "SUM('Fact - Loans'[LOAN_CNT_START_Y])",
            "formatString": "#,0",
            "lineageTag": "36f72f81-017b-4e97-a954-dca7cbb2a7fe"
          },
          {
            "name": "LOAN_CURRMM_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "SUM('Fact - Loans'[LOAN_CURRMM_AMT])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "ce17bd4f-ac7e-45a3-951d-ba19aec30f47"
          },
          {
            "name": "LOAN_DISB_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "SUM('Fact - Loans'[LOAN_DISB_AMT])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "f5714128-38e1-443d-925c-8d476de62cfd"
          },
          {
            "name": "LOAN_DISB_CNT",
            "expression": "sum('Fact - Loans'[LOAN_DISB_CNT])",
            "formatString": "#,0",
            "lineageTag": "04dd668c-5a2c-44d1-95e6-3dbd7d8ae38d"
          },
          {
            "name": "LOAN_DISB_IRR",
            "expression": [
              "",
              "var RES =  SUM('Fact - Loans'[LOAN_DISB_IRR])",
              "var AR = SUM('Fact - Loans'[LOAN_DISB_AMT])",
              "",
              "return IF(AR = 0 && OR(res = 0, not(res = BLANK())),BLANK(),res/AR)",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "1df3035d-5778-4521-9906-4361691b55d2"
          },
          {
            "name": "LOAN_DISB_TRS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "var RES =  SUM('Fact - Loans'[LOAN_DISB_TRS])",
              "",
              "var AR = SUM('Fact - Loans'[LOAN_DISB_AMT])",
              "",
              "return IF(AR = 0 && OR(res = 0, not(res = BLANK())),BLANK(),res/AR)"
            ],
            "lineageTag": "b25f25c7-4c76-44b2-90b5-c80053d2516e"
          },
          {
            "name": "LOAN_END_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": [
              "",
              "var res_fx = SUM('Fact - Loans'[LOAN_END_AMT_FX])",
              "var res = SUM('Fact - Loans'[LOAN_END_AMT])",
              "return IF(MAX('Dimension - FX'[ID]) = 1, res_fx,res)"
            ],
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "1cbf3986-d10a-4f4e-a042-c277e2f52644"
          },
          {
            "name": "LOAN_END_AMT_CHNG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": [
              "",
              "var res_fx = SUM('Fact - Loans'[LOAN_END_AMT_CHNG_FX])",
              "var res = SUM('Fact - Loans'[LOAN_END_AMT_CHNG])",
              "return IF(MAX('Dimension - FX'[ID]) = 1, res_fx,res)"
            ],
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "f075ef80-39e4-412f-bee5-7aeee4348639"
          },
          {
            "name": "LOAN_END_AMT_CHNG_Y",
            "expression": [
              "",
              "var res_fx = SUM('Fact - Loans'[LOAN_END_AMT_CHNG_FX_Y])",
              "var res = SUM('Fact - Loans'[LOAN_END_AMT_CHNG_Y])",
              "return IF(MAX('Dimension - FX'[ID]) = 1, res_fx,res)"
            ],
            "formatString": "0",
            "lineageTag": "1795eaf1-9262-4d29-afa9-eb638453e3c7"
          },
          {
            "name": "LOAN_END_AMT_IRR",
            "expression": [
              "",
              "",
              "var ares_fx = SUM('Fact - Loans'[LOAN_END_AMT_FX])",
              "var ares = SUM('Fact - Loans'[LOAN_END_AMT])",
              "var ar =  IF(MAX('Dimension - FX'[ID]) = 1, ares_fx,ares)",
              "",
              "var res_fx = SUM('Fact - Loans'[LOAN_END_AMT_IRR_FX])",
              "var res = SUM('Fact - Loans'[LOAN_END_AMT_IRR])",
              "return IF(MAX('Dimension - FX'[ID]) = 1, res_fx,res) / ar"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "929078ce-5e94-4993-9132-16f6946c357a"
          },
          {
            "name": "LOAN_END_AMT_TRS",
            "expression": [
              "",
              "",
              "var ares_fx = SUM('Fact - Loans'[LOAN_END_AMT_FX])",
              "var ares = SUM('Fact - Loans'[LOAN_END_AMT])",
              "var ar =  IF(MAX('Dimension - FX'[ID]) = 1, ares_fx,ares)",
              "",
              "var res_fx = SUM('Fact - Loans'[LOAN_END_AMT_TRS_FX])",
              "var res = SUM('Fact - Loans'[LOAN_END_AMT_TRS])",
              "return IF(MAX('Dimension - FX'[ID]) = 1, res_fx,res) / ar"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "85f0f91e-4ed9-4029-97cd-a6eeafb81ff2"
          },
          {
            "name": "LOAN_NXTMM_PMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "sum('Fact - Loans'[LOAN_NXTMM_PMT])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "dd5d4b6e-07c0-4dd0-8ccf-ea7295de712c"
          },
          {
            "name": "LOAN_OVDU_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "SUM('Fact - Loans'[LOAN_OVDU_AMT])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "f9a9c9d4-22e6-45c6-9ea5-499cac6aedcb"
          },
          {
            "name": "LOAN_OVDU_AMT_PCT",
            "expression": "SUM('Fact - Loans'[LOAN_OVDU_AMT_PCT]) / SUM('Fact - Loans'[LOAN_END_AMT])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "922bad81-a6e7-4ac1-94c7-f09b994ddf74"
          },
          {
            "name": "LOAN_PT_CNT",
            "expression": "SUM('Fact - Loans'[LOAN_PT_CNT])",
            "formatString": "#,0",
            "lineageTag": "856baff0-2d07-4120-9a01-c09e809d5199"
          },
          {
            "name": "LOAN_PT_CNT_NEW",
            "expression": "SUM('Fact - Loans'[LOAN_PT_CNT_NEW])",
            "formatString": "#,0",
            "lineageTag": "d925a30f-df1e-4cd2-9b98-01e0b7fcc59c"
          },
          {
            "name": "LOAN_START_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "SUM('Fact - Loans'[LOAN_START_AMT])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "5243aa94-2521-4dae-8c92-d828f000aa2f"
          },
          {
            "name": "LOAN_START_AMT_Y",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "SUM('Fact - Loans'[LOAN_START_AMT_Y])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "e52f075e-7060-4157-a67d-380d4a291343"
          }
        ],
        "partitions": [
          {
            "name": "Measures - Loans-fd389808-1699-43d0-b872-e9afd1c22b9f",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Subordinates - Loans",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ce322918f1194ae587ab7a6e79fd8317"
          }
        ],
        "columns": [
          {
            "name": "Measures - Loans",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "8f71acef-2436-4944-b363-4237f4b8cc90",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Measures - Loans Fields"
                }
              ]
            },
            "sortByColumn": "Measures - Loans Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Measures - Loans Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "816b8b8e-619c-417c-8454-709bce52f1a3",
            "sortByColumn": "Measures - Loans Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Measures - Loans Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "80b42eda-c051-4a62-93a2-0578ea9e2372",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "8ab70086-be8a-46d0-9254-26e86f222765",
        "partitions": [
          {
            "name": "Subordinates - Loans-26e0905d-b51a-41b4-8be8-3fd4a84ad317",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"მიმდინარე პორტფელი\", NAMEOF('Measures - Loans'[LOAN_END_AMT]), 0),",
                "    (\"მიმდინარე პორტფელი - რაოდენობა\", NAMEOF('Measures - Loans'[LOAN_CNT_END]), 1),",
                "    (\"მიმდინარე პორტფელი - სატრანსფერო განაკვეთი\", NAMEOF('Measures - Loans'[LOAN_END_AMT_TRS]), 2),",
                "    (\"მიმდინარე პორტფელი - ეფექტური პროცენტი\", NAMEOF('Measures - Loans'[LOAN_END_AMT_IRR]), 3),",
                "    (\"საწყისი მოცულობა - წლის\", NAMEOF('Measures - Loans'[LOAN_START_AMT_Y]), 4),",
                "    (\"საწყისი რაოდენობა - წლის\", NAMEOF('Measures - Loans'[LOAN_CNT_START_Y]), 5),",
                "    (\"ცვლილება - წლის\", NAMEOF('Measures - Loans'[LOAN_END_AMT_CHNG_Y]), 6),",
                "    (\"საწყისი მოცულობა - თვის\", NAMEOF('Measures - Loans'[LOAN_START_AMT]), 7),",
                "    (\"საწყისი რაოდენობა - თვის\", NAMEOF('Measures - Loans'[LOAN_CNT_START]), 8),",
                "    (\"ცვლილება - თვის\", NAMEOF('Measures - Loans'[LOAN_END_AMT_CHNG]), 9),",
                "    (\"ვადაგადაცილება\", NAMEOF('Measures - Loans'[LOAN_OVDU_AMT]), 10),",
                "    (\"% ვადაგადაცილება\", NAMEOF('Measures - Loans'[LOAN_OVDU_AMT_PCT]), 11),",
                "    (\"მიმდინარე თვის დაფარვები\", NAMEOF('Measures - Loans'[LOAN_CURRMM_AMT]), 12),",
                "    (\"მომდევნო თვის დაფარვები\", NAMEOF('Measures - Loans'[LOAN_NXTMM_PMT]), 13),",
                "    (\"მსესხებლები\", NAMEOF('Measures - Loans'[LOAN_PT_CNT]), 14),",
                "    (\"ახალი კლიენტი\", NAMEOF('Measures - Loans'[LOAN_PT_CNT_NEW]), 15),",
                "    (\"სესხის გაცემა\", NAMEOF('Measures - Loans'[LOAN_DISB_AMT]), 16),",
                "    (\"სესხის გაცემა - რაოდენობა\", NAMEOF('Measures - Loans'[LOAN_DISB_CNT]), 17),",
                "    (\"სესხის გაცემა - სატრანსფერო განაკვეთი\", NAMEOF('Measures - Loans'[LOAN_DISB_TRS]), 18),",
                "    (\"სესხის გაცემა - ეფექტური პროცენტი\", NAMEOF('Measures - Loans'[LOAN_DISB_IRR]), 19)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Measures - Depos",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5eed0388-b00c-4c7d-886b-452ca99ae00c",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "31e05be8-3d45-41dc-8d54-c3bf52cb5346",
        "measures": [
          {
            "name": "DEPO_CNT_END",
            "expression": "sum('Fact - Depos'[DEPO_CNT_END])",
            "formatString": "#,0",
            "lineageTag": "a3684e8b-cf33-4a4c-8a34-bcee544580c7"
          },
          {
            "name": "DEPO_CNT_START",
            "expression": "SUM('Fact - Depos'[DEPO_CNT_START])",
            "formatString": "#,0",
            "lineageTag": "9ee27d76-7efd-4577-b84b-b9919cb9a8f0"
          },
          {
            "name": "DEPO_CNT_START_Y",
            "expression": "SUM('Fact - Depos'[DEPO_CNT_START_Y])",
            "formatString": "#,0",
            "lineageTag": "433dd17a-4bea-4651-b146-1272116c9cd8"
          },
          {
            "name": "DEPO_CURRMM_PMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "SUM('Fact - Depos'[DEPO_CURRMM_PMT])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "ac2c0a87-498e-402a-b20a-a006e18ded31"
          },
          {
            "name": "DEPO_DISB_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": [
              "",
              "var TOT_DISB = SUM('Fact - Depos'[DEPO_DISB_AMT])",
              "var TOT_NM = SUM('Fact - Depos'[DEPO_DISB_AMT_NM])",
              "var TOT_NC = SUM('Fact - Depos'[DEPO_DISB_AMT_NC])",
              "var res = IF(MAX('Dimension - DEPO_DISB_TP'[ID]) = 1, TOT_DISB, IF(MAX('Dimension - DEPO_DISB_TP'[ID]) = 2 , TOT_NC, TOT_NM))",
              "return res"
            ],
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "0dfa9a8f-29f2-4c55-bb11-f776439823d2"
          },
          {
            "name": "DEPO_DISB_CNT",
            "expression": [
              "",
              "var TOT_DISB = SUM('Fact - Depos'[DEPO_DISB_CNT])",
              "var TOT_NM = SUM('Fact - Depos'[DEPO_DISB_CNT_NM])",
              "var TOT_NC = SUM('Fact - Depos'[DEPO_DISB_CNT_NC])",
              "var res = IF(MAX('Dimension - DEPO_DISB_TP'[ID]) = 1, TOT_DISB, IF(MAX('Dimension - DEPO_DISB_TP'[ID]) = 2 , TOT_NC, TOT_NM))",
              "return res"
            ],
            "formatString": "#,0",
            "lineageTag": "28c0addc-695e-4792-8942-e3b7a1955390"
          },
          {
            "name": "DEPO_DISB_IRR_AMT",
            "expression": [
              "",
              "var TOT_DISB_N = SUM('Fact - Depos'[DEPO_DISB_AMT_NO_IRR])",
              "var TOT_NM_N = SUM('Fact - Depos'[DEPO_DISB_AMT_NO_IRR_NM])",
              "var TOT_NC_N = SUM('Fact - Depos'[DEPO_DISB_AMT_NO_IRR_NC])",
              "var AR = IF(MAX('Dimension - DEPO_DISB_TP'[ID]) = 1, TOT_DISB_N, IF(MAX('Dimension - DEPO_DISB_TP'[ID]) = 2 , TOT_NC_N, TOT_NM_N))",
              "",
              "var TOT_DISB = SUM('Fact - Depos'[DEPO_DISB_AMT_IRR])",
              "var TOT_NM = SUM('Fact - Depos'[DEPO_DISB_AMT_IRR_NM])",
              "var TOT_NC = SUM('Fact - Depos'[DEPO_DISB_AMT_IRR_NC])",
              "var res = IF(MAX('Dimension - DEPO_DISB_TP'[ID]) = 1, TOT_DISB, IF(MAX('Dimension - DEPO_DISB_TP'[ID]) = 2 , TOT_NC, TOT_NM))",
              "return IF(AR = 0 && OR(res = 0, not(res = BLANK())),BLANK(),res/AR)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "58e0f543-67b9-4c74-9366-675e6d0a8b98"
          },
          {
            "name": "DEPO_DISB_TRS_AMT",
            "expression": [
              "",
              "var TOT_DISB_N = SUM('Fact - Depos'[DEPO_DISB_AMT_NO_TRS])",
              "var TOT_NM_N = SUM('Fact - Depos'[DEPO_DISB_AMT_NO_TRS_NM])",
              "var TOT_NC_N = SUM('Fact - Depos'[DEPO_DISB_AMT_NO_TRS_NC])",
              "var AR = IF(MAX('Dimension - DEPO_DISB_TP'[ID]) = 1, TOT_DISB_N, IF(MAX('Dimension - DEPO_DISB_TP'[ID]) = 2 , TOT_NC_N, TOT_NM_N))",
              "",
              "var TOT_DISB = SUM('Fact - Depos'[DEPO_DISB_AMT_TRS])",
              "var TOT_NM = SUM('Fact - Depos'[DEPO_DISB_AMT_TRS_NM])",
              "var TOT_NC = SUM('Fact - Depos'[DEPO_DISB_AMT_TRS_NC])",
              "var res = IF(MAX('Dimension - DEPO_DISB_TP'[ID]) = 1, TOT_DISB, IF(MAX('Dimension - DEPO_DISB_TP'[ID]) = 2 , TOT_NC, TOT_NM))",
              "return IF(OR(AR = 0, AR = BLANK()),BLANK(),res/AR)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "96c4141d-79e1-4454-8fac-66f13a4ab77e"
          },
          {
            "name": "DEPO_END_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": [
              "",
              "var res_fx = SUM('Fact - Depos'[DEPO_END_AMT_FX])",
              "var res = SUM('Fact - Depos'[DEPO_END_AMT])",
              "return IF(MAX('Dimension - FX'[ID]) = 1, res_fx,res)"
            ],
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "0cd03b56-57dd-43f8-81ac-1a1545a16399"
          },
          {
            "name": "DEPO_END_AMT_CHNG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": [
              "",
              "var res_fx = SUM('Fact - Depos'[DEPO_END_AMT_CHNG_FX])",
              "var res = SUM('Fact - Depos'[DEPO_END_AMT_CHNG])",
              "return IF(MAX('Dimension - FX'[ID]) = 1, res_fx,res)"
            ],
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "21e6848f-173f-4fd0-9b4d-1d787edd97e6"
          },
          {
            "name": "DEPO_END_AMT_CHNG_Y",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": [
              "",
              "var res_fx = SUM('Fact - Depos'[DEPO_END_AMT_CHNG_FX_Y])",
              "var res = SUM('Fact - Depos'[DEPO_END_AMT_CHNG_Y])",
              "return IF(MAX('Dimension - FX'[ID]) = 1, res_fx,res)"
            ],
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "06ef2ab6-0b32-4527-b833-627bd1d9a4a6"
          },
          {
            "name": "DEPO_END_AMT_IRR",
            "expression": [
              "",
              "",
              "var ares_fx = CALCULATE(SUM('Fact - Depos'[DEPO_END_AMT_NO_IRR_FX]), FILTER('Fact - Depos', 'Fact - Depos'[PROD_ID] <> 4))",
              "var ares = CALCULATE(SUM('Fact - Depos'[DEPO_END_AMT_NO_IRR]), FILTER('Fact - Depos', 'Fact - Depos'[PROD_ID] <> 4))",
              "var ar =  IF(MAX('Dimension - FX'[ID]) = 1, ares_fx,ares)",
              "",
              "var res_fx = SUM('Fact - Depos'[DEPO_END_AMT_IRR_FX])",
              "var res = SUM('Fact - Depos'[DEPO_END_AMT_IRR])",
              "return IF(OR(AR = 0, AR = BLANK()),BLANK(),IF(MAX('Dimension - FX'[ID]) = 1, res_fx,res) / ar)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "37650e2e-6f20-4db2-b262-72935616a95d"
          },
          {
            "name": "DEPO_END_AMT_TRS",
            "expression": [
              "",
              "",
              "var ares_fx = CALCULATE(SUM('Fact - Depos'[DEPO_END_AMT_NO_TRS_FX]), FILTER('Fact - Depos', 'Fact - Depos'[PROD_ID] <> 4))",
              "var ares = CALCULATE(SUM('Fact - Depos'[DEPO_END_AMT_NO_TRS]), FILTER('Fact - Depos', 'Fact - Depos'[PROD_ID] <> 4))",
              "var ar =  IF(MAX('Dimension - FX'[ID]) = 1, ares_fx,ares)",
              "",
              "var res_fx = SUM('Fact - Depos'[DEPO_END_AMT_TRS_FX])",
              "var res = SUM('Fact - Depos'[DEPO_END_AMT_TRS])",
              "return IF(OR(AR = 0, AR = BLANK()),BLANK(),IF(MAX('Dimension - FX'[ID]) = 1, res_fx,res) / ar)"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "8b5f4809-e66b-4911-9205-b02ab3b9e2df"
          },
          {
            "name": "DEPO_NXTMM_PMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "sum('Fact - Depos'[DEPO_NXTMM_PMT])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "503e7f96-4e07-480f-be70-858a86017146"
          },
          {
            "name": "DEPO_PT_CNT",
            "expression": "SUM('Fact - Depos'[DEPO_PT_CNT])",
            "formatString": "#,0",
            "lineageTag": "2834c781-bfa0-443c-8882-88179db98fe4"
          },
          {
            "name": "DEPO_PT_CNT_NEW",
            "expression": "SUM('Fact - Depos'[DEPO_PT_CNT_NEW])",
            "formatString": "#,0",
            "lineageTag": "3029f55d-92a9-4687-8d06-64da51af3e9c"
          },
          {
            "name": "DEPO_START_AMT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "SUM('Fact - Depos'[DEPO_START_AMT])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "a0b7cecf-406c-417d-b92e-b21b91626ead"
          },
          {
            "name": "DEPO_START_AMT_Y",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ka-GE\"}"
              }
            ],
            "expression": "SUM('Fact - Depos'[DEPO_START_AMT_Y])",
            "formatString": "#,0\\ \"₾\";-#,0\\ \"₾\";#,0\\ \"₾\"",
            "lineageTag": "cefc4fa5-f426-463f-b60d-8a9f183958f3"
          }
        ],
        "partitions": [
          {
            "name": "Measures - Depos-55f511b7-67d3-4319-b7b4-37e71535ec33",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dimension - DEPO_DISB_TP",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d6f0f990-94ea-487e-b2ac-e3df210f62a9",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "DISB_TP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "259d1cf2-ab34-444d-85cd-1a99a67c5af6",
            "sortByColumn": "ID",
            "sourceColumn": "DISB_TP",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cb8b04a5-9783-4548-9658-33adbaa58da2",
        "partitions": [
          {
            "name": "Dimension - DEPO_DISB_TP-360fd841-ac6b-430d-a3ac-01471b4af298",
            "mode": "import",
            "queryGroup": "Helper Dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUXrYvP5h84SHzbMfNi9+2LwAzJ6sFKsTrWQElgVy14HJWQ+bZyg8bJ75sHnuw+Y5D5sXwVQvBbNngPUYY9WzBGz2LLCiWAA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, DISB_TP = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"ID\", Int64.Type}, {\"DISB_TP\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Subordinates - Depos",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c86cfd56288e4f14a2bf6a28ae1b5b79"
          }
        ],
        "columns": [
          {
            "name": "Subordinates - Depos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "355bf752-0933-4916-b69f-0840fe590a26",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Subordinates - Depos Fields"
                }
              ]
            },
            "sortByColumn": "Subordinates - Depos Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Subordinates - Depos Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "87adcdc3-f0ff-472b-9bfb-a584dc90af61",
            "sortByColumn": "Subordinates - Depos Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Subordinates - Depos Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "f220d353-2027-42f8-9d64-e84350a120c7",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "836d3b7d-4398-4911-9d06-e338e0adbf3e",
        "partitions": [
          {
            "name": "Subordinates - Depos-23ebcf31-149a-4d40-a186-7a95277accd1",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"მიმდინარე პორტფელი\", NAMEOF('Measures - Depos'[DEPO_END_AMT]), 0),",
                "    (\"მიმდინარე პორტფელი - რაოდენობა\", NAMEOF('Measures - Depos'[DEPO_CNT_END]), 1),",
                "    (\"მიმდინარე პორტფელი - სატრანსფერო პროცენტი\", NAMEOF('Measures - Depos'[DEPO_END_AMT_TRS]), 2),",
                "    (\"მიმდინარე პორტფელი - ეფექტური პროცენტი\", NAMEOF('Measures - Depos'[DEPO_END_AMT_IRR]), 3),",
                "    (\"საწყისი მოცულობა - წლის\", NAMEOF('Measures - Depos'[DEPO_START_AMT_Y]), 4),",
                "    (\"საწყისი რაოდენობა - წლის\", NAMEOF('Measures - Depos'[DEPO_CNT_START_Y]), 5),",
                "    (\"ცვლილება - წლის\", NAMEOF('Measures - Depos'[DEPO_END_AMT_CHNG_Y]), 6),",
                "    (\"საწყისი მოცულობა - თვის\", NAMEOF('Measures - Depos'[DEPO_START_AMT]), 7),",
                "    (\"საწყისი რაოდენობა - თვის\", NAMEOF('Measures - Depos'[DEPO_CNT_START]), 8),",
                "    (\"ცვლილება - თვის\", NAMEOF('Measures - Depos'[DEPO_END_AMT_CHNG]), 9),",
                "    (\"ვადისგასვლა - მიმდინარე თვე\", NAMEOF('Measures - Depos'[DEPO_CURRMM_PMT]), 10),",
                "    (\"ვადისგასვლა - მომდევნო თვე\", NAMEOF('Measures - Depos'[DEPO_NXTMM_PMT]), 11),",
                "    (\"დეპოზიტარები\", NAMEOF('Measures - Depos'[DEPO_PT_CNT]), 12),",
                "    (\"ახალი კლიენტი\", NAMEOF('Measures - Depos'[DEPO_PT_CNT_NEW]), 13),",
                "    (\"გაცემის მოცულობა\", NAMEOF('Measures - Depos'[DEPO_DISB_AMT]), 14),",
                "    (\"გაცემის რაოდენობა\", NAMEOF('Measures - Depos'[DEPO_DISB_CNT]), 15),",
                "    (\"გაცემა - სატრანსფერო პროცენტი\", NAMEOF('Measures - Depos'[DEPO_DISB_TRS_AMT]), 16),",
                "    (\"გაცემა - ეფექტური პროცენტი\", NAMEOF('Measures - Depos'[DEPO_DISB_IRR_AMT]), 17)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dimension - Loan Product",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "LOAN_PROD_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3bf9bd02-4bff-42d2-b58a-866f4ce45f39",
            "sourceColumn": "LOAN_PROD_ID",
            "summarizeBy": "none"
          },
          {
            "name": "PROD_DESCR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8815798a-3603-465f-93d2-a51f4dde1b1f",
            "sourceColumn": "PROD_DESCR",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "eb387100-9988-4987-8daa-bc5681c6432b",
        "partitions": [
          {
            "name": "Dimension - Loan Product-726a0928-a8d0-415d-87fa-ae8624baa31c",
            "mode": "import",
            "queryGroup": "Helper Dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"drop table if exists #LOAN_PROD;#(lf)create table #LOAN_PROD (LOAN_PROD_ID int, PROD_DESCR nvarchar(max));#(lf)insert into #LOAN_PROD#(lf)exec dbo.BI_MDB_SCH_LOAN_PROD;#(lf)#(lf)insert into #LOAN_PROD#(lf)select 0 , N'ჯამურად';#(lf)#(lf)#(lf)select * from #LOAN_PROD\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dimension - Depo Product",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DEPO_PROD_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b3c9aecb-231c-4144-8f47-50b59e42791b",
            "sourceColumn": "DEPO_PROD_ID",
            "summarizeBy": "none"
          },
          {
            "name": "PROD_DESCR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b287e6a-80ee-42dc-ad0c-b844a46b2212",
            "sourceColumn": "PROD_DESCR",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "91003930-3327-436c-a778-40195cd1c974",
        "partitions": [
          {
            "name": "Dimension - Depo Product-d1419a9c-f780-4ca8-8110-66ee26cbbef7",
            "mode": "import",
            "queryGroup": "Helper Dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"drop table if exists #DEPO_PROD;#(lf)create table #DEPO_PROD (DEPO_PROD_ID int, PROD_DESCR nvarchar(max));#(lf)insert into #DEPO_PROD#(lf)exec dbo.BI_MDB_SCH_DEPO_PROD;#(lf)#(lf)insert into #DEPO_PROD#(lf)select 0 , N'ჯამურად';#(lf)#(lf)#(lf)select * from #DEPO_PROD\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measures - Home",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afb278e2-f9e0-430e-8ef9-3c396fa80771",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f8278f90-3392-4a2a-a8e6-1d3feddfd949",
        "measures": [
          {
            "name": "SSS",
            "expression": "\"1546 ₾ (6.69%)\"",
            "lineageTag": "0fd8aa14-c479-46fc-b7ef-08dac02b1773"
          },
          {
            "name": "SSSS",
            "expression": "\"+1546 ₾\"",
            "lineageTag": "751258a2-827b-43c1-a4e1-e6859b3a8e00"
          },
          {
            "name": "HM_LOAN_START_AMT",
            "expression": [
              "",
              "var M = [LOAN_START_AMT]",
              "var Y = [LOAN_START_AMT_Y]",
              "var res = IF(MAX('Dimension - Delta Type'[Column1]) = \"წინა თვესთან\", M,Y)",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,### ₾\")))"
            ],
            "lineageTag": "623eada9-4c59-42c7-abe5-e2b5ce5ba4e5"
          },
          {
            "name": "HM_LOAN_START_CNT",
            "expression": [
              "",
              "var M = [LOAN_CNT_START]",
              "var Y = [LOAN_CNT_START_Y]",
              "var res = IF(MAX('Dimension - Delta Type'[Column1]) = \"წინა თვესთან\", M,Y)",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,###\")))"
            ],
            "lineageTag": "77bce624-266a-464c-9601-a74e3ad8ee32"
          },
          {
            "name": "HM_LOAN_END_AMT",
            "expression": [
              "",
              " var res = [LOAN_END_AMT]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,### ₾\")))"
            ],
            "lineageTag": "019c2c3b-cdfd-4a04-abe1-472890aa7678"
          },
          {
            "name": "HM_LOAN_END_AMT_CHNG",
            "expression": [
              "",
              "var M = [LOAN_END_AMT_CHNG]",
              "var Y = [LOAN_END_AMT_CHNG_Y]",
              "var res = IF(MAX('Dimension - Delta Type'[Column1]) = \"წინა თვესთან\", M,Y)",
              "return IF(ISBLANK(res), \"-\", ",
              "IF(res=0,\"-\",",
              "IF(res > 0 , FORMAT(res, \"+###,###,### ₾\"),",
              "FORMAT(res, \"###,###,### ₾\"))))"
            ],
            "lineageTag": "df8054d4-158b-4f21-b2bd-1630623f501c"
          },
          {
            "name": "HM_LOAN_END_CNT",
            "expression": [
              "",
              " var res = [LOAN_CNT_END]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,###\")))"
            ],
            "lineageTag": "b769d4d2-3ed2-472b-999d-30f007bd3846"
          },
          {
            "name": "HM_LOAN_DISB_AMT",
            "expression": [
              "",
              " var res = [LOAN_DISB_AMT]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,### ₾\")))"
            ],
            "lineageTag": "918ef73d-3e42-4a3d-9330-70a41cba7123"
          },
          {
            "name": "HM_LOAN_DISB_CNT",
            "expression": [
              "",
              " var res = [LOAN_DISB_CNT]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,###\")))"
            ],
            "lineageTag": "07336b98-36cc-4fc4-92f4-3e709efc7b29"
          },
          {
            "name": "HM_DEPO_START_CNT",
            "expression": [
              "",
              "var M = [DEPO_CNT_START]",
              "var Y = [DEPO_CNT_START_Y]",
              "var res = IF(MAX('Dimension - Delta Type'[Column1]) = \"წინა თვესთან\", M,Y)",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,###\")))"
            ],
            "lineageTag": "4deacce2-0533-4215-9d25-e4288b48d1d6"
          },
          {
            "name": "HM_DEPO_START_AMT",
            "expression": [
              "",
              "var M = [DEPO_START_AMT]",
              "var Y = [DEPO_START_AMT_Y]",
              "var res = IF(MAX('Dimension - Delta Type'[Column1]) = \"წინა თვესთან\", M,Y)",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,### ₾\")))"
            ],
            "lineageTag": "f340bc15-aebb-43b9-8403-5f7dd3ecb3bf"
          },
          {
            "name": "HM_DEPO_END_CNT",
            "expression": [
              "",
              " var res = [DEPO_CNT_END]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,###\")))"
            ],
            "lineageTag": "070e8d36-67c2-4a99-9064-189d452fa1e6"
          },
          {
            "name": "HM_DEPO_END_AMT_CHNG",
            "expression": [
              "",
              "var M = [DEPO_END_AMT_CHNG]",
              "var Y = [DEPO_END_AMT_CHNG_Y]",
              "var res = IF(MAX('Dimension - Delta Type'[Column1]) = \"წინა თვესთან\", M,Y)",
              "return IF(ISBLANK(res), \"-\", ",
              "IF(res=0,\"-\",",
              "IF(res > 0 , FORMAT(res, \"+###,###,### ₾\"),",
              "FORMAT(res, \"###,###,### ₾\"))))"
            ],
            "lineageTag": "bcd21928-ad1c-41c2-982f-0333efb2169c"
          },
          {
            "name": "HM_DEPO_END_AMT",
            "expression": [
              "",
              " var res = [DEPO_END_AMT]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,### ₾\")))"
            ],
            "lineageTag": "1fdf03c6-f822-4dc9-a355-238906693c11"
          },
          {
            "name": "HM_DEPO_DISB_CNT",
            "expression": [
              "",
              " var res = [DEPO_DISB_CNT]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,###\")))"
            ],
            "lineageTag": "c80590fd-3963-4d2e-a9d7-0dc591ffc7d6"
          },
          {
            "name": "HM_DEPO_DISB_AMT",
            "expression": [
              "",
              " var res = [DEPO_DISB_AMT]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,### ₾\")))"
            ],
            "lineageTag": "db271b73-5bde-4265-9b09-934d3a3311d3"
          },
          {
            "name": "HM_LOAN_PT_CNT",
            "expression": [
              "",
              " var res = [LOAN_PT_CNT]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,###\")))"
            ],
            "lineageTag": "92234fc5-9676-4c7f-aa76-dab26521b7a3"
          },
          {
            "name": "HM_LOAN_PT_CNT_NEW",
            "expression": [
              "",
              " var res = [LOAN_PT_CNT_NEW]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,###\")))"
            ],
            "lineageTag": "4de2f2a2-3e80-4dad-861c-d828df86aa3e"
          },
          {
            "name": "HM_LOAN_CURRMM_AMT",
            "expression": [
              "",
              " var res = [LOAN_CURRMM_AMT]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,### ₾\")))"
            ],
            "lineageTag": "996ce0ec-6b5c-422c-b2cd-4f503f17b589"
          },
          {
            "name": "HM_LOAN_NXTMM_PMT",
            "expression": [
              "",
              " var res = [LOAN_NXTMM_PMT]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,### ₾\")))"
            ],
            "lineageTag": "a1361e3c-3395-440e-8a93-fdf366738bf5"
          },
          {
            "name": "HM_LOAN_DISB_IRR",
            "expression": [
              "",
              " var res = [LOAN_DISB_IRR]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"Percent\")))"
            ],
            "lineageTag": "5a9258be-a2e1-4fe4-9140-e20acefa4e21"
          },
          {
            "name": "HM_LOAN_DISB_TRS",
            "expression": [
              "",
              " var res = [LOAN_DISB_TRS]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"Percent\")))"
            ],
            "lineageTag": "b575a152-6e1c-41b8-addd-49ee94372cc7"
          },
          {
            "name": "HM_LOAN_END_AMT_IRR",
            "expression": [
              "",
              " var res = [LOAN_END_AMT_IRR]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"Percent\")))"
            ],
            "lineageTag": "305b418f-716a-4252-89ac-47f7a491ab27"
          },
          {
            "name": "HM_LOAN_END_AMT_TRS",
            "expression": [
              "",
              " var res = [LOAN_END_AMT_TRS]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"Percent\")))"
            ],
            "lineageTag": "55ff50fa-09a7-4fb9-a132-b0c6f8ca9340"
          },
          {
            "name": "HM_DEPO_CURRMM_AMT",
            "expression": [
              "",
              " var res = [DEPO_CURRMM_PMT]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,### ₾\")))"
            ],
            "lineageTag": "46f05280-2bd3-4db5-b795-869d3d7c426d"
          },
          {
            "name": "HM_DEPO_NXTMM_PMT",
            "expression": [
              "",
              " var res = [DEPO_NXTMM_PMT]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,### ₾\")))"
            ],
            "lineageTag": "57681638-90ba-4369-9c98-d8717d048c23"
          },
          {
            "name": "HM_DEPO_PT_CNT",
            "expression": [
              "",
              " var res = [DEPO_PT_CNT]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,###\")))"
            ],
            "lineageTag": "0920e92f-3663-4d2a-8123-14578ee5c825"
          },
          {
            "name": "HM_DEPO_PT_CNT_NEW",
            "expression": [
              "",
              " var res = [DEPO_PT_CNT_NEW]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"###,###,###\")))"
            ],
            "lineageTag": "9b05665a-d32a-421c-8bda-fc0f4a1b52cf"
          },
          {
            "name": "HM_DEPO_DISB_IRR",
            "expression": [
              "",
              " var res = [DEPO_DISB_IRR_AMT]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"Percent\")))"
            ],
            "lineageTag": "2fa270d4-fa55-4e2f-91f3-dbfc9f7a64ad"
          },
          {
            "name": "HM_DEPO_DISB_TRS_AMT",
            "expression": [
              "",
              " var res = [DEPO_DISB_TRS_AMT]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"Percent\")))"
            ],
            "lineageTag": "499dc11c-a925-4fc7-9ccc-42f861cd26f3"
          },
          {
            "name": "HM_DEPO_END_AMT_IRR",
            "expression": [
              "",
              " var res = [DEPO_END_AMT_IRR]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"Percent\")))"
            ],
            "lineageTag": "f14c150d-79ce-4fb9-aa6b-a79d3574b61c"
          },
          {
            "name": "HM_DEPO_END_AMT_TRS",
            "expression": [
              "",
              " var res = [DEPO_END_AMT_TRS]",
              "return IF(ISBLANK(res), \"-\", IF(res=0,\"-\",FORMAT(res, \"Percent\")))"
            ],
            "lineageTag": "fe676530-fc71-4298-a62c-587436e16b94"
          },
          {
            "name": "HM_LOAN_OVDU",
            "expression": [
              "",
              "var res_amt = [LOAN_OVDU_AMT]",
              "var res_pct = IF(ISBLANK([LOAN_OVDU_AMT_PCT]),0,[LOAN_OVDU_AMT_PCT])",
              "return IF(ISBLANK(res_amt), \"-\", IF(res_amt=0,\"-\",FORMAT(res_amt, \"###,###,### ₾\") & \" (\" & format(res_pct,\"0.0%\") & \")\"))"
            ],
            "lineageTag": "a77c36b6-152a-4485-b039-4ce641996b13"
          },
          {
            "name": "HM_LOAN_OVDU_TOTAL",
            "expression": [
              "",
              "var res_amt_BS = CALCULATE([LOAN_OVDU_AMT],'Dimension - Loan Product'[PROD_DESCR] = \"ჯამურად\")",
              "var res_PCT_BS = CALCULATE([LOAN_OVDU_AMT_PCT],'Dimension - Loan Product'[PROD_DESCR] = \"ჯამურად\")",
              "var res_pct = IF(ISBLANK(res_PCT_BS),0,res_PCT_BS)",
              "return IF(ISBLANK(res_amt_BS), \"-\", IF(res_amt_BS=0,\"-\",FORMAT(res_amt_BS, \"###,###,### ₾\") & \" (\" & format(res_pct,\"0.0%\") & \")\"))"
            ],
            "lineageTag": "14b5b96e-8ff0-44ab-b449-35634cc6cfa4"
          },
          {
            "name": "HM_LOAN_OVDU_CONS",
            "expression": [
              "",
              "var res_amt_BS = CALCULATE([LOAN_OVDU_AMT],'Dimension - Loan Product'[PROD_DESCR] = \"სამომხმარებლო სესხი\")",
              "var res_PCT_BS = CALCULATE([LOAN_OVDU_AMT_PCT],'Dimension - Loan Product'[PROD_DESCR] = \"სამომხმარებლო სესხი\")",
              "var res_pct = IF(ISBLANK(res_PCT_BS),0,res_PCT_BS)",
              "return IF(ISBLANK(res_amt_BS), \"-\", IF(res_amt_BS=0,\"-\",FORMAT(res_amt_BS, \"###,###,### ₾\") & \" (\" & format(res_pct,\"0.0%\") & \")\"))"
            ],
            "lineageTag": "80bf3167-8075-400f-95da-146e5bccac67"
          },
          {
            "name": "HM_LOAN_OVDU_CR_CARD",
            "expression": [
              "",
              "var res_amt_BS = CALCULATE([LOAN_OVDU_AMT],'Dimension - Loan Product'[PROD_DESCR] = \"საკრედიტო ბარათი\")",
              "var res_PCT_BS = CALCULATE([LOAN_OVDU_AMT_PCT],'Dimension - Loan Product'[PROD_DESCR] = \"საკრედიტო ბარათი\")",
              "var res_pct = IF(ISBLANK(res_PCT_BS),0,res_PCT_BS)",
              "return IF(ISBLANK(res_amt_BS), \"-\", IF(res_amt_BS=0,\"-\",FORMAT(res_amt_BS, \"###,###,### ₾\") & \" (\" & format(res_pct,\"0.0%\") & \")\"))"
            ],
            "lineageTag": "1b0a9c43-c56b-4052-af0e-c7535d7a9044"
          },
          {
            "name": "HM_LOAN_OVDU_DEP_LOAN",
            "expression": [
              "",
              "var res_amt_BS = CALCULATE([LOAN_OVDU_AMT],'Dimension - Loan Product'[PROD_DESCR] = \"დეპოზიტური სესხი\")",
              "var res_PCT_BS = CALCULATE([LOAN_OVDU_AMT_PCT],'Dimension - Loan Product'[PROD_DESCR] = \"დეპოზიტური სესხი\")",
              "var res_pct = IF(ISBLANK(res_PCT_BS),0,res_PCT_BS)",
              "return IF(ISBLANK(res_amt_BS), \"-\", IF(res_amt_BS=0,\"-\",FORMAT(res_amt_BS, \"###,###,### ₾\") & \" (\" & format(res_pct,\"0.0%\") & \")\"))"
            ],
            "lineageTag": "85a25593-6ded-4231-9ed3-d44c55479503"
          },
          {
            "name": "HM_LOAN_OVDU_MORT",
            "expression": [
              "",
              "var res_amt_BS = CALCULATE([LOAN_OVDU_AMT],'Dimension - Loan Product'[PROD_DESCR] = \"იპოთეკური სესხი\")",
              "var res_PCT_BS = CALCULATE([LOAN_OVDU_AMT_PCT],'Dimension - Loan Product'[PROD_DESCR] = \"იპოთეკური სესხი\")",
              "var res_pct = IF(ISBLANK(res_PCT_BS),0,res_PCT_BS)",
              "return IF(ISBLANK(res_amt_BS), \"-\", IF(res_amt_BS=0,\"-\",FORMAT(res_amt_BS, \"###,###,### ₾\") & \" (\" & format(res_pct,\"0.0%\") & \")\"))"
            ],
            "lineageTag": "eb026970-e639-4375-a475-3223c3d01275"
          }
        ],
        "partitions": [
          {
            "name": "Measures - Home-79283a1c-3b71-4701-bb1b-a808437f8396",
            "mode": "import",
            "queryGroup": "Measures",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dimension - Delta Type",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6eb89a7e-5989-4a38-b16e-86926e149f9a",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "753b8ec7-bd4a-4edc-9b19-00986970a116",
        "partitions": [
          {
            "name": "Dimension - Delta Type-8375e8bf-3d49-4783-a488-7d130c5816f3",
            "mode": "import",
            "queryGroup": "Helper Dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Weti85mHzjIfNcx42T1AAc6Y8bJ71sHk6kA8UVYrVwVADlJoKVrYQSVksAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact - Bonus Hierarchy Bridge",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DW_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78dda37d-0279-4eca-bc90-cbdad612d02c",
            "sourceColumn": "DW_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DW_ID_BNS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04cb17fc-0838-4453-80a4-58e053854230",
            "sourceColumn": "DW_ID_BNS",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fe5da24a-a93f-4904-a258-17bda0103109",
        "partitions": [
          {
            "name": "Fact - Bonus Hierarchy Bridge-6ddc092f-c3f4-4a66-af0b-87b0aaed21ac",
            "mode": "import",
            "queryGroup": "Bridges",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"select A.DW_ID, DW_ID_BNS#(lf)from MDB_BI_BNS_BRG_FACT A#(lf)join MDB_BI_EMP_HIER_FACT MEH on A.DW_ID = MEH.DW_ID#(lf)where MEH.RPT_ID = 3#(lf)  and MEH.SNAP_DATE >= '2023-08-31'#(lf)and meh.del_flag = 0;\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dimension - Currency",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CCY_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "60365dab-f2da-41f1-8202-2877d491b671",
            "sourceColumn": "CCY_ID",
            "summarizeBy": "count"
          },
          {
            "name": "CCY_DESCR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c9d05a0-7f83-4087-badc-21428f88fb85",
            "sortByColumn": "CCY_ID",
            "sourceColumn": "CCY_DESCR",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d6c507fe-93ac-4c49-9be9-fb7348050f42",
        "partitions": [
          {
            "name": "Dimension - Currency-6a1762bf-8677-406f-8ca2-5f9d9611c913",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUXJ39VGK1YlWMgKyQ4NdwGxjINs1NAjMNgGy/UsyUovAPAMgz9EHqCMWAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [CCY_ID = _t, CCY_DESCR = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"CCY_ID\", Int64.Type}, {\"CCY_DESCR\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dimension - Role Type",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ROLE_DESCR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "e85051e1-9f14-418b-844b-280b494e7b75",
            "sortByColumn": "ROLE_TP_ID",
            "sourceColumn": "ROLE_DESCR",
            "summarizeBy": "none"
          },
          {
            "name": "ROLE_TP_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7912b6e1-ab1c-4910-87e6-fd75a66cae97",
            "sourceColumn": "ROLE_TP_ID",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "516bc005-1eba-4dd9-a33a-c6dbd714d470",
        "partitions": [
          {
            "name": "Dimension - Role Type-ca5bf12c-b479-4897-89e8-4440b28ec362",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Weti8/mHzhIfNsx82L37YvADMnqyko2SoFKsDkl0IFpkJlpoClHrYPONh86KHzXMVwHqAQnPA5HowCVE0EagIaIQR2IhgX1cFsNAEsNKZYANQ1BlDrZoHE58NVgN0zmwCOk0Qjlz3sHkqUCVQ0FQpNhYA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ROLE_DESCR = _t, ROLE_TP_ID = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"ROLE_DESCR\", type text}, {\"ROLE_TP_ID\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dimension - Plan",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PLN_TP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1484aabe-74f8-4c20-85a9-6938f663a3fa",
            "sourceColumn": "PLN_TP",
            "summarizeBy": "none"
          },
          {
            "name": "PLN_GRP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "495d7c24-f48a-47d1-93c3-4b49f0fd28fa",
            "sourceColumn": "PLN_GRP",
            "summarizeBy": "none"
          },
          {
            "name": "PLN_GRP_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3985a3b6-7fb5-4488-b9c4-f2cf9a4c50b0",
            "sourceColumn": "PLN_GRP_ID",
            "summarizeBy": "count"
          },
          {
            "name": "PLN_CLASS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfede2a6-847c-4842-9e88-60b1835b6b34",
            "sourceColumn": "PLN_CLASS",
            "summarizeBy": "none"
          },
          {
            "name": "PLN_CLASS_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "caa95a1e-e7f4-4ced-8642-e29fb5389065",
            "sourceColumn": "PLN_CLASS_ID",
            "summarizeBy": "count"
          },
          {
            "name": "PLN_TP_GEO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8e7fa64-c6cb-44fe-9ad4-717fed9c4fde",
            "sourceColumn": "PLN_TP_GEO",
            "summarizeBy": "none"
          },
          {
            "name": "PLN_TP_GEO_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4318d63a-e1b6-4e6d-9e54-934f10df5a08",
            "sourceColumn": "PLN_TP_GEO_ID",
            "summarizeBy": "count"
          },
          {
            "name": "PCT_RNG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c95fd7b5-8133-4efe-ac6f-61e8752ee7c3",
            "sourceColumn": "PCT_RNG",
            "summarizeBy": "none"
          },
          {
            "name": "WGHT_PCT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "364820ee-bec1-4328-a59c-0746d37973ee",
            "sourceColumn": "WGHT_PCT",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "4257b9a8-6e10-4d4b-afb8-4c1ed0653767",
        "partitions": [
          {
            "name": "Dimension - Plan-078b2a15-e378-4da4-9cc6-428ced7fbd8a",
            "mode": "import",
            "queryGroup": "Helper Dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"SELECT * FROM MDB_EXT_PLAN_VAL; \"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dimension - Bonus Tree",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "45507a2b-0d7f-4186-b28b-73ab9aa00585",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "ROLE_TP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca87c150-c740-4e4f-a595-263b314d6c1e",
            "sourceColumn": "ROLE_TP",
            "summarizeBy": "none"
          },
          {
            "name": "CARD_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d1a43a2-6902-4b01-bbd8-4b90432aa19e",
            "sourceColumn": "CARD_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "CARD_VAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e23733c3-b613-40b3-9062-8b9322e530a7",
            "sourceColumn": "CARD_VAL",
            "summarizeBy": "sum"
          },
          {
            "name": "CARD_DESCR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ed44a89-3de8-48ab-883a-e392b58a95c9",
            "sourceColumn": "CARD_DESCR",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "569fe387-1b86-458c-abe5-6eced1760363",
        "partitions": [
          {
            "name": "Dimension - Bonus Tree-444944b4-079c-486f-bbef-ea093d98f652",
            "mode": "import",
            "queryGroup": "Helper Dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"SELECT * FROM MDB_EXT_BTREE_VAL; \"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"CARD_VAL\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Update Date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "46711838-a8b6-4d96-8a03-53a7ae357423",
            "sourceColumn": "DT",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_cfca3bbe-65e4-447b-88e2-c168447172aa"
                },
                "isDefault": true,
                "relationship": "e3693451-93f8-4578-9363-0fc630ebdf44"
              }
            ]
          }
        ],
        "lineageTag": "a27a267c-2915-43dc-a2b7-90d488ae6bb0",
        "partitions": [
          {
            "name": "Update Date-4ac5c3ba-f7ec-49ca-8758-78d7c106bc9d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"exec  dbo.BI_MDB_UPD_DT\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_cfca3bbe-65e4-447b-88e2-c168447172aa",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "933536da-6393-4d64-bce0-3436ab2878eb",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d7d4bc97-4d72-4e25-b0aa-d131a3082fb5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "96948930-e92f-432e-ba42-5c5abcaffd2b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6c2af60b-0ee3-403d-b109-384c93e3084c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "44b09046-f336-469e-8b79-4f099a6a4d73",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "84eecebf-8a48-4c9f-b15c-3ffb21cc9549",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a50a89fb-11a6-43b0-99a7-d98c95d0c068",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "36999d21-154a-469f-844d-d590b579ed46",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "fb0f1921-5875-4198-86b6-8dbf7efd73b4",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e2dff85a-f91f-43b9-954d-befd7864c956",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "005cb7da-d687-4985-a834-83db034d7cba",
                "ordinal": 3
              }
            ],
            "lineageTag": "2dc1611e-03e7-4f91-af46-b12e7c1e2856"
          }
        ],
        "isHidden": true,
        "lineageTag": "b019951a-84c3-4c69-972c-65013a79b45d",
        "partitions": [
          {
            "name": "LocalDateTable_cfca3bbe-65e4-447b-88e2-c168447172aa-8e923ff9-3d18-4a3b-b2a5-5c00408eb196",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Update Date'[DT])), 1, 1), Date(Year(MAX('Update Date'[DT])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "REPORTING",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ACCS_FLAG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1a477fd4-415b-482a-a8c8-8fc4309e3c64",
            "sourceColumn": "ACCS_FLAG",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "3684ca4a-e2cf-405e-a763-831670849d08",
        "measures": [
          {
            "name": "Filter page Navigation",
            "expression": "IF(max(REPORTING[ACCS_FLAG]) = 1, \"EMP_FILTER\")",
            "lineageTag": "471d7f68-1ce9-4272-99eb-122c55ecc130"
          },
          {
            "name": "Transparent Dark Background",
            "expression": "IF(max(REPORTING[ACCS_FLAG]) = 1, \"#F2C80F\",  \"#FFFFFF00\")",
            "lineageTag": "8582a313-6221-4802-8201-999748e46827"
          },
          {
            "name": "Transparent Light Background",
            "expression": "IF(max(REPORTING[ACCS_FLAG]) = 1, \"#FAE99F\",  \"#FFFFFF00\")",
            "lineageTag": "c3547a16-9a29-4555-9b51-9cff489c2d7a"
          },
          {
            "name": "Transparent Text",
            "expression": "IF(max(REPORTING[ACCS_FLAG]) = 1, \"#000000\",  \"#FFFFFF00\")",
            "lineageTag": "2b4a0def-7279-4e78-85e3-f58718c5e854"
          },
          {
            "name": "Filter page Navigation Simulation",
            "expression": "IF(max(REPORTING[ACCS_FLAG]) = 1, \"Bonus Simulation - CM\")",
            "lineageTag": "f720922c-00de-40fa-b8db-f49e9fdf1954"
          },
          {
            "name": "Transparent Light Background Simulation",
            "expression": "IF(max(REPORTING[ACCS_FLAG]) = 1, \"#555f77\",  \"#FFFFFF00\")",
            "lineageTag": "c71c0bce-baa2-4b64-b8cf-7b19eb9dabd8"
          }
        ],
        "partitions": [
          {
            "name": "REPORTING-00cd3d62-3e74-476a-9903-8c8f4250f6c7",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlSK1YlWMlCKjQUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ACCS_FLAG = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"ACCS_FLAG\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact - Ranking  Hierarchy Bridge",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DW_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "306076ad-d728-46f7-88f1-06b267ac5949",
            "sourceColumn": "DW_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DW_ID_RNK",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aef019ae-688d-493e-8e29-2d30c0f91044",
            "sourceColumn": "DW_ID_RNK",
            "summarizeBy": "none"
          },
          {
            "name": "EMP_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b6e52a7d-6378-4d7c-9b97-e128cb83425a",
            "sourceColumn": "EMP_ID",
            "summarizeBy": "count"
          },
          {
            "name": "RSL_GRP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e90aacbc-ece7-49f5-8cc3-aa3dddceaa09",
            "sourceColumn": "RSL_GRP",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b024d830-deee-4998-bd52-a68d6c6a1d15",
        "partitions": [
          {
            "name": "Fact - Ranking  Hierarchy Bridge-58512636-4689-4c8d-9014-e2e16c8bfcf8",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"select DW_ID, DW_ID_RNK, EMP_ID, RSL_GRP from MDB_BI_EMP_RANKING_BRG#(lf)where DEL_FLAG = 0 and SNAP_DATE >= '2023-08-31' and RSL_GRP = 'CM';#(lf)\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact - Ranking",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "DW_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c7bdb83-1914-4083-8228-02b6e8892500",
            "sourceColumn": "DW_ID",
            "summarizeBy": "none"
          },
          {
            "name": "KPI_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a3b8d02-d31e-455e-970e-77eb598fa354",
            "sourceColumn": "KPI_NAME",
            "summarizeBy": "none"
          },
          {
            "name": "KPI_VAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d51b92ce-a16f-46e5-9d07-26ba370739d9",
            "sourceColumn": "KPI_VAL",
            "summarizeBy": "none"
          },
          {
            "name": "PM_RNK_RN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3fdbe1a8-fcc5-4583-9762-3832d41d1fea",
            "sourceColumn": "PM_RNK_RN",
            "summarizeBy": "none"
          },
          {
            "name": "RANK",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d6414d4-da7c-4ec5-af4e-96c2fd2d809f",
            "sourceColumn": "RANK",
            "summarizeBy": "none"
          },
          {
            "name": "PREVIOUS_RANK",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfa41e92-8a09-438c-94b4-e5e0a5b4d613",
            "sourceColumn": "PREVIOUS_RANK",
            "summarizeBy": "none"
          },
          {
            "name": "MAX_KPI_VAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2c897c89-358e-4437-b039-938fa45bd22d",
            "sourceColumn": "MAX_KPI_VAL",
            "summarizeBy": "none"
          },
          {
            "name": "PER_FRQ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8731350-e5a1-4d7a-a8f1-040913c5942c",
            "sourceColumn": "PER_FRQ",
            "summarizeBy": "none"
          },
          {
            "name": "IS_PERCENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "704dd4a8-350d-49dd-affe-4a385c62fc39",
            "sourceColumn": "IS_PERCENT",
            "summarizeBy": "none"
          },
          {
            "name": "RANK_DESCR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "504af0ba-cfdf-4800-a7b4-30fe87443470",
            "sortByColumn": "RANK_DESCR_SHORT_ID",
            "sourceColumn": "RANK_DESCR",
            "summarizeBy": "none"
          },
          {
            "name": "RANK_DESCR_WGHT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "expression": "'Fact - Ranking'[RANK_DESCR] & \" - \" & FORMAT(max('Fact - Ranking'[RANK_WEIGHT]), \"0%\")",
            "lineageTag": "95368f1a-385c-46c0-8d1a-f829c5a495b7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "RANK_DESCR_SHORT_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "565b31bc-1d81-4cf8-acea-24b51248c99b",
            "sourceColumn": "RANK_DESCR_SHORT_ID",
            "summarizeBy": "none"
          },
          {
            "name": "WGHT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "e848c26b-1926-46f2-85fb-983568d5ac5a",
            "sourceColumn": "WGHT",
            "summarizeBy": "none"
          },
          {
            "name": "_RN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "abf26c85-701d-4100-973c-8b56163a52ab",
            "sourceColumn": "_RN",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d1216510-6c48-4f3e-ad5b-3df184dc153c",
        "measures": [
          {
            "name": "TOT_RANK",
            "expression": "CALCULATE(MAX('Fact - Ranking'[RANK]), FILTER('Fact - Ranking', 'Fact - Ranking'[KPI_NAME] = \"FINAL_RANK\"))",
            "lineageTag": "f6c51aca-46b4-4412-85af-4863fd809b11"
          },
          {
            "name": "KPI_VAL_FORMATED",
            "expression": [
              "var res = SUM('Fact - Ranking'[KPI_VAL])",
              "  return IF(max('Fact - Ranking'[IS_PERCENT]) = \"1\", FORMAT(res, \"0.0%\"),",
              "  ",
              "  IF(MAX('Fact - Ranking'[RANK_DESCR_SHORT_ID]) in {31,32}, FORMAT(res, \"###,###,###\"),",
              "  FORMAT ( res, \"###,###,### ₾\" ) ))"
            ],
            "lineageTag": "0985d18e-df4a-4e6c-9973-cd4127cf1828"
          },
          {
            "name": "MAX_KPI_VAL_FORMATED",
            "expression": [
              "var res = SUM('Fact - Ranking'[MAX_KPI_VAL])",
              "  return IF(max('Fact - Ranking'[IS_PERCENT]) = \"1\", FORMAT(res, \"0.0%\"),",
              "  ",
              "  IF(MAX('Fact - Ranking'[RANK_DESCR_SHORT_ID]) in {31,32}, FORMAT(res, \"###,###,###\"),",
              "  FORMAT ( res, \"###,###,### ₾\" ) ))"
            ],
            "lineageTag": "73a2ed0b-36bc-40a0-a278-fec365411028"
          }
        ],
        "partitions": [
          {
            "name": "Fact - Ranking-002443a2-c264-4ce9-880d-a4dd5241098e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"#(lf)select CONVERT(NVARCHAR, A.SNAP_DATE, 112) + '.' + cast(A.EMP_ID as nvarchar(max)) + '.' + A.RLS_GRP + '.' + A.KPI_NAME DW_ID,#(lf)       A.KPI_NAME,#(lf)       B.WGHT,#(lf)       A.KPI_VAL,#(lf)       A.PREV_M_CHG PM_RNK_RN,#(lf)       A.RANK,#(lf)       C.RANK PREVIOUS_RANK,#(lf)       A.MAX_KPI_VAL,#(lf)       case when A.KPI_NAME like '%_Y%' then N'წლიური გეგმა' else N'ყოველთვიური გეგმა' end  PER_FRQ,#(lf)       isnull(cast(BB.IS_PERCENT as nvarchar(max)), 0)                                       IS_PERCENT,#(lf)       BB.RANK_DESCR_SHORT RANK_DESCR,#(lf)      BB.RANK_DESCR_SHORT_ID,#(lf)      A._RN#(lf)#(lf)from MDB_BI_EMP_RANKING A#(lf)left join MDB_BI_RLS_RANKING_REL B on B.RANK_TYPE = A.KPI_NAME and B.RLS_GRP = 'CM'#(lf)left join MDB_BI_EMP_RANKING C on eomonth(dateadd(mm,1,C.SNAP_DATE)) = A.SNAP_DATE and#(lf)                                  C.EMP_ID = A.EMP_ID and#(lf)                                  C.RLS_GRP = A.RLS_GRP and#(lf)                                  C.DEL_FLAG = 0 and#(lf)                                  C.KPI_NAME = A.KPI_NAME#(lf)left join MDB_BI_RNK_TP BB on BB.RANK_TYPE = A.KPI_NAME#(lf)where A.RLS_GRP = 'CM' and#(lf)      A.SNAP_DATE >= '2023-08-31' and#(lf)      A.DEL_FLAG = 0;\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "BI_RLS_TST",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RLS_MAIL_TST",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4fbeaf54-8db2-4b40-8239-794a3560a33d",
            "sourceColumn": "RLS_MAIL_TST",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "62ce3f73-3a1f-49bc-a26c-7696b0185a1f",
        "measures": [
          {
            "name": "RLS_TST_MAIL",
            "expression": "MAX(BI_RLS_TST[RLS_MAIL_TST])",
            "lineageTag": "729a2750-d82d-4434-9750-cec2ff6b8004"
          },
          {
            "name": "SSRS_RLS_MAIL",
            "expression": "IF(upper(userprincipalname()) = \"TEST03@BSB.GE\", [RLS_TST_MAIL], max('Fact - Employee Hierarchy'[RLS_MAIL]))",
            "lineageTag": "baf89bf7-ebd5-43ff-9dbe-cd8a2f3b94de"
          }
        ],
        "partitions": [
          {
            "name": "BI_RLS_TST-e2618a75-2e8a-48e0-b94c-5d6c20fd7e9b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.152.155\", \"DWH\", [Query=\"exec MDB_GET_RLS_MAIL 'CM'\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"RLS_MAIL\", \"RLS_MAIL_TST\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Simulation",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17b1b5a7-c042-494e-b020-e23e534d6e1f",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "84c24e23-e273-4f1a-ae78-49c9a5bb85a0",
        "measures": [
          {
            "name": "C_BNS_AFTER_FLF_CORR_SIM",
            "expression": [
              "",
              "var res = [BNS_AFTER_FLF_CORR_SIM]",
              "",
              "RETURN  format(res,  \"###,###,### ₾\" )"
            ],
            "lineageTag": "9a958a3e-965b-4537-ac5d-eed1bba2631e"
          },
          {
            "name": "M_FLF_PCT_SIM",
            "expression": [
              "",
              "VAR res1 = SUM ( 'Fact - Bonus'[BNS_AFTER_OVDU_CORR] ) ",
              "var FLF_M_1 = divide( IF(max('Fact - Bonus Plan'[PLN_TP]) = \"CM/Portfolio Growth/M\", [PRMT_1_VAL],0) ,",
              " calculate(SUM ( 'Fact - Bonus Plan'[PLN_VAL] ), filter('Fact - Bonus Plan', 'Fact - Bonus Plan'[PLN_TP] = \"CM/Portfolio Growth/M\")))",
              "",
              "var FLF_M_2 = divide( IF(max('Fact - Bonus Plan'[PLN_TP]) = \"CM/Loan Disbursement Count/M\", [PRMT_2_VAL],0) ,",
              " calculate(SUM ( 'Fact - Bonus Plan'[PLN_VAL] ), filter('Fact - Bonus Plan', 'Fact - Bonus Plan'[PLN_TP] = \"CM/Loan Disbursement Count/M\")))",
              " ",
              "var res = IF(max('Fact - Bonus Plan'[PLN_TP]) = \"CM/Loan Disbursement Count/M\",FLF_M_2, ",
              "IF(max('Fact - Bonus Plan'[PLN_TP]) = \"CM/Portfolio Growth/M\",FLF_M_1)) ",
              "",
              "",
              "RETURN res"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0d90496b-b643-4296-9165-a0fa0a204137"
          },
          {
            "name": "M_FLF_VAL_SIM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "var res = IF(max('Fact - Bonus Plan'[PLN_TP]) = \"CM/Portfolio Growth/M\", [PRMT_1_VAL],",
              "IF(max('Fact - Bonus Plan'[PLN_TP]) = \"CM/Loan Disbursement Count/M\", [PRMT_2_VAL]))",
              "",
              "RETURN  res"
            ],
            "formatString": "#,0",
            "lineageTag": "4aa25275-ebe8-4a5f-89ce-1bbbe9a32d31"
          },
          {
            "name": "M_FLF_PCT_FLF_RNG_SIM",
            "expression": [
              "",
              "var FLF_M_1 = divide( [PRMT_1_VAL],",
              " calculate(SUM ( 'Fact - Bonus Plan'[PLN_VAL] ), filter('Fact - Bonus Plan', 'Fact - Bonus Plan'[PLN_TP] = \"CM/Portfolio Growth/M\")))",
              "",
              "var FLF_M_2 = divide( [PRMT_2_VAL],",
              " calculate(SUM ( 'Fact - Bonus Plan'[PLN_VAL] ), filter('Fact - Bonus Plan', 'Fact - Bonus Plan'[PLN_TP] = \"CM/Loan Disbursement Count/M\")))",
              "",
              "var LMT = IF(FLF_M_1 >= 0.6 && FLF_M_2 >= 0.6, 1,0)",
              "",
              "var FLF_M_1_UP = IF(FLF_M_1 < 0.6, 0, IF(LMT <> 1 && FLF_M_1 > 1.3, 1.3, FLF_M_1))",
              "",
              "var FLF_M_2_UP = IF(FLF_M_2 < 0.6, 0, IF(LMT <> 1 && FLF_M_2 > 1.3, 1.3, FLF_M_2))",
              "",
              "",
              "var res = FLF_M_1_UP*0.7 + FLF_M_2_UP*0.3",
              "",
              "",
              "RETURN res"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5916d019-cd04-427f-acac-816c815454ee"
          },
          {
            "name": "FLF_M_1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "[PRMT_1_VAL]/",
              " calculate(SUM ( 'Fact - Bonus Plan'[PLN_VAL] ), ALLSELECTED('Dimension - Plan'[PLN_GRP]))"
            ],
            "lineageTag": "0b734c75-f66f-40eb-b3af-16afe7bdd24d"
          },
          {
            "name": "FLF_M_2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "[PRMT_2_VAL]/",
              " calculate(SUM ( 'Fact - Bonus Plan'[PLN_VAL] ), ALL('Fact - Bonus Plan'[PLN_TP]), 'Fact - Bonus Plan'[PLN_TP] = \"CM/Loan Disbursement Count/M\")"
            ],
            "lineageTag": "9de2f54e-69c0-4fe9-8201-33375187cfe0"
          },
          {
            "name": "BNS_CUTOVER_SIM",
            "expression": "IF([BNS_AFTER_FLF_CORR_SIM]>=2500,2500,[BNS_AFTER_FLF_CORR_SIM])",
            "formatString": "0",
            "lineageTag": "f96819e5-7679-4a93-8f02-63cb8f0ba969"
          },
          {
            "name": "BNS_AFTER_FLF_CORR_SIM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR res1 = SUM ( 'Fact - Bonus'[BNS_AFTER_OVDU_CORR] ) ",
              "var flf = [M_FLF_PCT_FLF_RNG_SIM]",
              "RETURN  res1 * flf"
            ],
            "lineageTag": "5ef1ecf4-d254-416f-ad86-6e3c7e4e72ec"
          },
          {
            "name": "C_BNS_CUTOVER_SIM",
            "expression": [
              "",
              "VAR res = [BNS_CUTOVER_SIM]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "5fdfdd15-627d-41b4-ab2e-1bd983edd7ef"
          },
          {
            "name": "BNS_SHR_SIM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(MAX('Dimension - Bonus Tree'[CARD_VAL]),'Dimension - Bonus Tree'[ID] = 35)*[BNS_CUTOVER_SIM]",
            "lineageTag": "cae91c76-29fd-49f2-9ea4-74c3b7c15eb2"
          },
          {
            "name": "C_BNS_SHR_SIM",
            "expression": [
              "",
              "VAR res = [BNS_SHR_SIM]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "834bd6d4-7fed-4435-990e-3257a44b442c"
          },
          {
            "name": "BNS_M_SIM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[BNS_SHR_SIM]*CALCULATE(MAX('Dimension - Bonus Tree'[CARD_VAL]),'Dimension - Bonus Tree'[ID] = 37)",
            "lineageTag": "6657ef3f-6182-4af9-bf0d-0fbd5684f7c1"
          },
          {
            "name": "C_BNS_M_SIM",
            "expression": [
              "",
              "VAR res = [BNS_M_SIM]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "80816f98-bef5-47c3-a560-c2158fe4a4c1"
          },
          {
            "name": "BNS_Y_SIM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[BNS_SHR_SIM]*CALCULATE(MAX('Dimension - Bonus Tree'[CARD_VAL]),'Dimension - Bonus Tree'[ID] = 142)",
            "lineageTag": "896148a2-6cf6-432b-bce7-66f748c52509"
          },
          {
            "name": "C_BNS_Y_SIM",
            "expression": [
              "",
              "VAR res = [BNS_Y_SIM]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "b37ea146-f6cf-4158-bcd9-41efe3d02463"
          },
          {
            "name": "BNS_Y_TOTAL_SIM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM('Fact - Bonus'[BNS_Y_TOTAL]) -SUM('Fact - Bonus'[BNS_Y]) + [BNS_Y_SIM]",
            "lineageTag": "58c9dcba-cc81-48a6-9f71-9276c50aac0e"
          },
          {
            "name": "C_BNS_Y_TOTAL_SIM",
            "expression": [
              "",
              "VAR res = [BNS_Y_TOTAL_SIM]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "da992a75-f1f2-4f28-927d-6486543e2ac0"
          },
          {
            "name": "Y_FCT_LOAN_CNT_SIM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR V_FCT_Y_CNT = CALCULATE(SUM('Fact - Bonus Plan'[FCT_VAL]),'Fact - Bonus Plan'[PLN_TP] = \"CM/Loan Disbursement Count/Y\")",
              "                VAR V_FCT_M_CNT = CALCULATE(SUM('Fact - Bonus Plan'[FCT_VAL]),'Fact - Bonus Plan'[PLN_TP] = \"CM/Loan Disbursement Count/M\")",
              "                VAR V_PRMT = 'PRMT_2(LOAN_CNT)'[PRMT_2_VAL]",
              "RETURN CALCULATE(V_FCT_Y_CNT-V_FCT_M_CNT+V_PRMT)"
            ],
            "lineageTag": "0f24da46-1ddf-4d4c-9bae-a1ad66b3d522"
          },
          {
            "name": "Y_FLF_PCT_FLF_RNG_SIM",
            "expression": [
              "",
              "var FLF_M_1 = divide([FCT_Y_PORTF],",
              " calculate(SUM ( 'Fact - Bonus Plan'[PLN_VAL] ), filter('Fact - Bonus Plan', 'Fact - Bonus Plan'[PLN_TP] = \"CM/Portfolio Growth/Y\")))",
              "",
              "var FLF_M_2 = divide( [FCT_Y_LOAN_CNT],",
              " calculate(SUM ( 'Fact - Bonus Plan'[PLN_VAL] ), filter('Fact - Bonus Plan', 'Fact - Bonus Plan'[PLN_TP] = \"CM/Loan Disbursement Count/Y\")))",
              "",
              "",
              "",
              "var LMT = IF([FLF_M_1] >= 0.6 && [FLF_M_2] >= 0.6, 1,0)",
              "",
              "var FLF_M_1_UP = IF(FLF_M_1 < 0.6, 0, IF(LMT <> 1 && FLF_M_1 > 1.3, 1.3, FLF_M_1))",
              "",
              "var FLF_M_2_UP = IF(FLF_M_2 < 0.6, 0, IF(LMT <> 1 && FLF_M_2 > 1.3, 1.3, FLF_M_2))",
              "",
              "",
              "var res = FLF_M_1_UP*0.7 + FLF_M_2_UP*0.3 ",
              "",
              "RETURN res",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b29951b0-a315-4e58-8d99-f5f1760be928"
          },
          {
            "name": "BNS_AFTER_Y_FLF_CORR_SIM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[BNS_Y_TOTAL_SIM]*[Y_FLF_PCT_FLF_RNG_SIM]",
            "lineageTag": "024fc650-e024-4059-b8f1-97d0f7b0cb9e"
          },
          {
            "name": "C_BNS_AFTER_Y_FLF_CORR_SIM",
            "expression": [
              "",
              "VAR res = [BNS_AFTER_Y_FLF_CORR_SIM]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "f2727988-3db5-4e72-b5fc-d35a349d7ad6"
          },
          {
            "name": "BNS_M_NPS_SIM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[BNS_M_SIM]*MAX('Fact - Bonus'[BNS_M_NPS_VAL])",
            "lineageTag": "53ba7573-e4d9-4a32-a529-c5e9b4eddce7"
          },
          {
            "name": "C_BNS_M_NPS_SIM",
            "expression": [
              "",
              "VAR res = [BNS_M_NPS_SIM]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "fb47e643-a87b-4e21-abd2-d2ece668142f"
          },
          {
            "name": "BNS_M_IAS_NPS_LEFTOVER_PCT_SIM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[BNS_M_SIM]*CALCULATE(MAX('Dimension - Bonus Tree'[CARD_VAL]),'Dimension - Bonus Tree'[ID] = 46)",
            "lineageTag": "d160c803-094f-4867-a4b9-232078c9e6d1"
          },
          {
            "name": "C_BNS_M_IAS_NPS_LEFTOVER_PCT_SIM",
            "expression": [
              "",
              "VAR res = [BNS_M_IAS_NPS_LEFTOVER_PCT_SIM]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "1c459dcb-206f-4de4-90f0-a8ea0f00ea8e"
          },
          {
            "name": "BNS_M_IAS_SIM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(MAX('Fact - Bonus'[BNS_M_IAS_VAL])*[BNS_M_SIM])",
            "lineageTag": "4ee90bb4-33c1-471a-8f5a-b190fcf1975b"
          },
          {
            "name": "C_BNS_M_IAS_SIM",
            "expression": [
              "",
              "VAR res = [BNS_M_IAS_SIM]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "39804876-1e54-4ed9-b1e4-c1ec50abfcb9"
          },
          {
            "name": "BNS_Y_NPS_SIM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[BNS_CUTOVER_Y_SIM]*MAX('Fact - Bonus'[BNS_Y_NPS_VAL])",
            "lineageTag": "f877b60a-94cf-4268-83a0-5479177c2122"
          },
          {
            "name": "BNS_Y_IAS_SIM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(MAX('Fact - Bonus'[BNS_Y_IAS_VAL])*[BNS_CUTOVER_Y_SIM])",
            "lineageTag": "14591ae2-3977-4e82-8610-c06edf8f4852"
          },
          {
            "name": "BNS_Y_IAS_NPS_LEFTOVER_PCT_SIM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[BNS_CUTOVER_Y_SIM]*CALCULATE(MAX('Dimension - Bonus Tree'[CARD_VAL]),'Dimension - Bonus Tree'[ID] = 13)",
            "lineageTag": "baa84250-170d-4842-9dd3-480288ee0581"
          },
          {
            "name": "C_BNS_Y_IAS_SIM",
            "expression": [
              "",
              "VAR res = [BNS_Y_IAS_SIM]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "90a674c1-ba0e-48c1-9909-24762db0d4ef"
          },
          {
            "name": "C_BNS_Y_NPS_SIM",
            "expression": [
              "",
              "VAR res = [BNS_Y_NPS_SIM]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "e4df1dcf-002b-4f24-ab90-a7e48cde5420"
          },
          {
            "name": "C_BNS_Y_IAS_NPS_LEFTOVER_SIM",
            "expression": [
              "",
              "VAR res = [BNS_Y_IAS_NPS_LEFTOVER_PCT_SIM]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "6a6a77de-951e-4921-b4b8-15c360965d63"
          },
          {
            "name": "BNS_Y_FINAL_SIM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[BNS_Y_IAS_SIM] + [BNS_Y_IAS_NPS_LEFTOVER_PCT_SIM]+[BNS_Y_NPS_SIM]",
            "lineageTag": "82985878-9129-4257-9286-216dcd2dcecc"
          },
          {
            "name": "C_BNS_Y_FINAL_SIM",
            "expression": [
              "",
              "VAR res = [BNS_Y_FINAL_SIM]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "bc728ce6-c35d-4dca-a7a5-9ec11558328b"
          },
          {
            "name": "BNS_M_FINAL_SIM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[BNS_M_IAS_SIM] + [BNS_M_IAS_NPS_LEFTOVER_PCT_SIM]+[BNS_M_NPS_SIM]",
            "lineageTag": "de6c7622-f78e-41f3-b6d6-1a4ad33f86a7"
          },
          {
            "name": "C_BNS_M_FINAL_SIM",
            "expression": [
              "",
              "VAR res = [BNS_M_FINAL_SIM]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "9f357069-4662-4424-bf53-4f351b044bc9"
          },
          {
            "name": "BNS_CUTOVER_Y_SIM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF([BNS_AFTER_Y_FLF_CORR_SIM]>=2500,2500,[BNS_AFTER_Y_FLF_CORR_SIM])",
            "lineageTag": "1178730d-b71f-4263-bf92-690531fbae32"
          },
          {
            "name": "C_BNS_Y_CUTOVER_SIM",
            "expression": [
              "",
              "VAR res = [BNS_CUTOVER_Y_SIM]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( res ),",
              "        \"-\",",
              "        IF ( res = 0, \"-\", FORMAT ( res, \"###,###,### ₾\" ) )",
              "    )"
            ],
            "lineageTag": "3c6a87d7-4689-43c5-b0ef-ecccf60ce7e3"
          },
          {
            "name": "C_Y_FLF_PCT_FLF_RNG_SIM",
            "expression": [
              "",
              "VAR RES = [Y_FLF_PCT_FLF_RNG_SIM]",
              "RETURN",
              "    IF(ISBLANK(RES) || RES = 0,\"-\", FORMAT(RES,\"0%\"))"
            ],
            "lineageTag": "91b231ec-0b04-4144-80bf-f3f44bf86858"
          },
          {
            "name": "C_M_FLF_PCT_FLF_RNG_SIM",
            "expression": [
              "",
              "VAR RES = [M_FLF_PCT_FLF_RNG_SIM]",
              "RETURN",
              "    IF(ISBLANK(RES) || RES = 0,\"-\", FORMAT(RES,\"0%\"))"
            ],
            "lineageTag": "d0947d53-7e56-41ed-b933-2ff9cbc3c83a"
          },
          {
            "name": "Measure 3",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "d356fad9-31c6-4bc4-b9a4-be90f4e02ac3"
          },
          {
            "name": "FCT_Y_PORTF",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "var V_Y = CALCULATE(SUM('Fact - Bonus Plan'[FCT_VAL]),'Fact - Bonus Plan'[PLN_TP] = \"CM/Portfolio Growth/Y\")",
              "VAR V_M = CALCULATE(SUM('Fact - Bonus Plan'[FCT_VAL]),'Fact - Bonus Plan'[PLN_TP] = \"CM/Portfolio Growth/M\")",
              "VAR V_PRMT = 'PRMT_1(PORTFOLIO)'[PRMT_1_VAL]",
              "RETURN",
              "V_Y-V_M+V_PRMT"
            ],
            "lineageTag": "ac629a05-0452-4149-877f-e7453eaeed1d"
          },
          {
            "name": "FCT_Y_LOAN_CNT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "var V_Y = CALCULATE(SUM('Fact - Bonus Plan'[FCT_VAL]),'Fact - Bonus Plan'[PLN_TP] = \"CM/Loan Disbursement Count/Y\")",
              "VAR V_M = CALCULATE(SUM('Fact - Bonus Plan'[FCT_VAL]),'Fact - Bonus Plan'[PLN_TP] = \"CM/Loan Disbursement Count/M\")",
              "VAR V_PRMT = 'PRMT_2(LOAN_CNT)'[PRMT_2_VAL]",
              "RETURN",
              "V_Y-V_M+V_PRMT"
            ],
            "lineageTag": "53e691e3-f661-4f39-97ed-ce82f4240042"
          }
        ],
        "partitions": [
          {
            "name": "Simulation",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PRMT_1(PORTFOLIO)",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "efc2a60dbeea48d5a45058f3b424d9f9"
          }
        ],
        "columns": [
          {
            "name": "PRMT_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "568b2dd4-0800-4d81-b4ff-c945bc644100",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "3a82c2a2-0f88-4ff7-a2e3-dac6a0aac9d9",
        "measures": [
          {
            "name": "PRMT_1_VAL",
            "expression": "SELECTEDVALUE('PRMT_1(PORTFOLIO)'[PRMT_1])",
            "formatString": "0",
            "lineageTag": "5edfeada-ad91-4735-af3f-a2ffbf6393f8"
          }
        ],
        "partitions": [
          {
            "name": "PRMT_1(PORTFOLIO)",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 1000000, 1000)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "PRMT_2(LOAN_CNT)",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c6b4810570084f4a8ffa1d3bba92462a"
          }
        ],
        "columns": [
          {
            "name": "PRMT_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "bc9e8ce4-54b9-422d-9c52-bd71b7d6644e",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "26666f5c-c00b-4cf8-afa9-a40ae435234a",
        "measures": [
          {
            "name": "PRMT_2_VAL",
            "expression": "SELECTEDVALUE('PRMT_2(LOAN_CNT)'[PRMT_2])",
            "formatString": "0",
            "lineageTag": "fbe420bd-a456-4441-8445-73403b129f1c"
          },
          {
            "name": "PRMT_PCT_FLF",
            "expression": [
              "var v_flf = DIVIDE('PRMT_2(LOAN_CNT)'[PRMT_2_VAL],CALCULATE(SUM('Fact - Bonus Plan'[PLN_VAL]),'Fact - Bonus Plan'[PLN_TP] = \"CM/Portfolio Growth/M\"))",
              "RETURN",
              "    v_flf"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "93f706b1-2b4f-4b66-88a0-bea65fc3bcf9"
          }
        ],
        "partitions": [
          {
            "name": "PRMT_2(LOAN_CNT)",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 1000, 1)",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}