{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"v_BI_OfferCategories\",\"v_BI_OfferCheck\",\"v_BI_OfferCodes\",\"v_BI_OfferDetails\",\"v_BI_OfferExchanges\",\"v_BI_Offers\",\"v_BI_UserCoinFact\",\"v_BI_Users\",\"v_BI_Vendors\",\"v_BI_GameCoinStatistics\",\"v_BI_Calendar\",\"v_BI_Games\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.123.684.0 (23.11)"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "c8a24568-de66-4670-a243-41ecca9f3ec7",
        "fromColumn": "UserId",
        "fromTable": "v_BI_OfferExchanges",
        "isActive": false,
        "toColumn": "UserId",
        "toTable": "v_BI_Users"
      },
      {
        "name": "f7326392-dbae-4997-a530-fdb0e07ce608",
        "fromColumn": "OfferId",
        "fromTable": "v_BI_OfferCodes",
        "toColumn": "Id",
        "toTable": "v_BI_Offers"
      },
      {
        "name": "fdaee94e-d230-4675-8b53-d0b3a3a30560",
        "fromColumn": "CategoryId",
        "fromTable": "v_BI_OfferDetails",
        "toColumn": "Id",
        "toTable": "v_BI_OfferCategories"
      },
      {
        "name": "de7be8c3-7a64-4c9f-8bcb-70f77e11f689",
        "fromColumn": "GameId",
        "fromTable": "v_BI_GameCoinStatistics",
        "toColumn": "Id",
        "toTable": "v_BI_Games"
      },
      {
        "name": "55d81a65-9e8a-487d-871c-98ce3f0bdf5d",
        "fromColumn": "GameId",
        "fromTable": "v_BI_UserCoinFact",
        "toColumn": "Id",
        "toTable": "v_BI_Games"
      },
      {
        "name": "4839d943-85b0-4cfe-a225-e49b800ba735",
        "fromColumn": "OfferId",
        "fromTable": "v_BI_OfferExchanges",
        "toColumn": "Id",
        "toTable": "v_BI_Offers"
      },
      {
        "name": "0cafcff5-052f-457b-b036-e8d328e4b611",
        "fromColumn": "OfferId",
        "fromTable": "v_BI_OfferDetails",
        "toColumn": "Id",
        "toTable": "v_BI_Offers"
      },
      {
        "name": "f0bb481b-bbc7-4874-8c0f-8f0413ab6a1b",
        "fromColumn": "VendorId",
        "fromTable": "v_BI_Offers",
        "toColumn": "Id",
        "toTable": "v_BI_Vendors"
      },
      {
        "name": "c6cb8e97-f1e2-429a-8cf1-030dc1c1a7ba",
        "fromColumn": "UserId",
        "fromTable": "v_BI_UserCoinFact",
        "isActive": false,
        "toColumn": "UserId",
        "toTable": "v_BI_Users"
      },
      {
        "name": "1e788637-baff-4257-8c04-98fffd92d075",
        "fromColumn": "Hour",
        "fromTable": "v_BI_Users",
        "toColumn": "Hour",
        "toTable": "Time"
      },
      {
        "name": "a6a3dfe5-e8bc-40e4-95e1-e12806d18f02",
        "fromColumn": "CreateDT",
        "fromTable": "v_BI_UserCoinFact",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "86e9bf9c-e94e-42dc-8d33-c7709ea2d73d",
        "fromColumn": "DateKey",
        "fromTable": "v_BI_Users",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "52ab7426-27f1-4390-9474-e1f4168ebae8",
        "fromColumn": "Date",
        "fromTable": "v_BI_GameCoinStatistics",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "113ca2e1-c37f-4349-a48f-c1cc3101b817",
        "fromColumn": "DateKey",
        "fromTable": "v_BI_OfferExchanges",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "6e88bbf4-5ad2-4378-8587-581bf702ed37",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Id",
        "fromTable": "v_BI_Offers",
        "toColumn": "Id",
        "toTable": "v_BI_OfferCheck"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "v_BI_OfferCategories",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b8fb8775-c5ce-47a8-ae62-1df3316ab1e6",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03f9d623-51ec-48f2-b5cd-b014297f71c6",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7d57b9d6-aa68-4b9b-99ea-253394e44912",
        "partitions": [
          {
            "name": "v_BI_OfferCategories-3813eced-63f6-44f8-bd95-2d230cd2ac79",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"igrove.database.windows.net\", \"IGrove\", [CommandTimeout=#duration(0, 0, 2, 0)]),",
                "    dbo_v_BI_OfferCategories = Source{[Schema=\"dbo\",Item=\"v_BI_OfferCategories\"]}[Data]",
                "in",
                "    dbo_v_BI_OfferCategories"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_BI_OfferCheck",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CheckDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "265b856f-75c5-4602-b5f8-5fb9c7d6c014",
            "sourceColumn": "CheckDescription",
            "summarizeBy": "none"
          },
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f4214e9d-7e76-4da2-b3fd-8cc504eff766",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "OfferName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "450bdd8c-fe3a-40e5-a9bf-38451528107a",
            "sourceColumn": "OfferName",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3899a5d-538f-473c-8839-5c24bd0651a8",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "OfferQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4b952637-c095-4d50-b966-77ffe31739f8",
            "sourceColumn": "OfferQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "OfferCodesQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d4831997-337f-43b3-82c3-1aa4891d60af",
            "sourceColumn": "OfferCodesQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "OfferAvailableQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "551288e4-3c46-4303-b95f-3ebc2ec819f7",
            "sourceColumn": "OfferAvailableQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "OfferCodesAvailableQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b03d5e0-8c6c-4a32-aee1-273f068735f2",
            "sourceColumn": "OfferCodesAvailableQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "OfferUsedQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5358cd12-fe29-4e4a-ab56-f0615b4b8b31",
            "sourceColumn": "OfferUsedQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "OfferCodesUsedQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e00c6ce2-fa0f-46fc-8226-c1ddc5edcd5d",
            "sourceColumn": "OfferCodesUsedQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "OfferExchangesUsedQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c34c9cbf-07cb-46f5-99b4-ca66859510d8",
            "sourceColumn": "OfferExchangesUsedQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "EndDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "986bca56-c557-4496-ba74-7b3cc53d6c1e",
            "sourceColumn": "EndDate",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "35cd76d3-e4a9-4e11-86d0-34b5a1a5686b",
        "partitions": [
          {
            "name": "v_BI_OfferCheck-c6502797-1748-47c8-b8bd-0f4337a1643f",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"igrove.database.windows.net\", \"IGrove\", [CommandTimeout=#duration(0, 0, 2, 0)]),",
                "    dbo_v_BI_OfferCheck = Source{[Schema=\"dbo\",Item=\"v_BI_OfferCheck\"]}[Data]",
                "in",
                "    dbo_v_BI_OfferCheck"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_BI_OfferCodes",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5a2a94aa-3e8c-43dc-836e-b9b7ee7ef088",
            "sourceColumn": "Id",
            "summarizeBy": "count"
          },
          {
            "name": "OfferId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cb6b4604-b517-4926-a7af-4c8119bfbac9",
            "sourceColumn": "OfferId",
            "summarizeBy": "none"
          },
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c5fdfc7-46f4-436c-a65c-51964a2031f1",
            "sourceColumn": "Code",
            "summarizeBy": "none"
          },
          {
            "name": "IsShared",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "def717b4-5147-4b75-870a-cf3c7b1c9ace",
            "sourceColumn": "IsShared",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6107008a-2cd7-4f59-961b-d153401b204b",
        "partitions": [
          {
            "name": "v_BI_OfferCodes-544007f4-fb63-4ea5-98ab-9274aee5c803",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"igrove.database.windows.net\", \"IGrove\", [CommandTimeout=#duration(0, 0, 2, 0)]),",
                "    dbo_v_BI_OfferCodes = Source{[Schema=\"dbo\",Item=\"v_BI_OfferCodes\"]}[Data]",
                "in",
                "    dbo_v_BI_OfferCodes"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_BI_OfferDetails",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "462dc374-ebd6-4503-ac3b-e1b676c5468c",
            "sourceColumn": "Id",
            "summarizeBy": "count"
          },
          {
            "name": "OfferId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2251541d-6c0b-49e8-a475-10a3629ad9d2",
            "sourceColumn": "OfferId",
            "summarizeBy": "none"
          },
          {
            "name": "CategoryId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "878ba39d-949c-4335-a1a8-d3dc553aac2c",
            "sourceColumn": "CategoryId",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "54a5d974-6cdc-46f0-8164-f5fcabbf1130",
        "partitions": [
          {
            "name": "v_BI_OfferDetails-09d95372-a713-48bf-828f-af9d5cb96fae",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"igrove.database.windows.net\", \"IGrove\", [CommandTimeout=#duration(0, 0, 2, 0)]),",
                "    dbo_v_BI_OfferDetails = Source{[Schema=\"dbo\",Item=\"v_BI_OfferDetails\"]}[Data]",
                "in",
                "    dbo_v_BI_OfferDetails"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_BI_OfferExchanges",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3bd0b88b-a92c-4c97-bd95-dc0ffb285395",
            "sourceColumn": "Id",
            "summarizeBy": "count"
          },
          {
            "name": "OfferId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7427d1a3-b042-45e5-8635-00f29c292aae",
            "sourceColumn": "OfferId",
            "summarizeBy": "none"
          },
          {
            "name": "UserId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "41aff84f-854c-4f75-a0b1-68b98ad2017f",
            "sourceColumn": "UserId",
            "summarizeBy": "count"
          },
          {
            "name": "Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "ab45fd7f-18b7-4e53-a6bb-05247a7f94e3",
            "sourceColumn": "Price",
            "summarizeBy": "sum"
          },
          {
            "name": "ExchangeDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "e1d983b4-e455-470b-b7a9-50dca6a96c9b",
            "sourceColumn": "ExchangeDate",
            "summarizeBy": "none"
          },
          {
            "name": "IsActivated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "b868bb0a-e171-4e65-bb6b-9643363f84bd",
            "sourceColumn": "IsActivated",
            "summarizeBy": "none"
          },
          {
            "name": "ActivationDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ddfbf1d4-76af-4d5f-83cf-6300cfd650d0",
            "sourceColumn": "ActivationDate",
            "summarizeBy": "none"
          },
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "046e7baa-f865-4508-ba80-a88adb8f70bb",
            "sourceColumn": "Code",
            "summarizeBy": "none"
          },
          {
            "name": "ApprovedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "874ab15b-67c0-46d7-9197-e5464f278a69",
            "sourceColumn": "ApprovedBy",
            "summarizeBy": "sum"
          },
          {
            "name": "ApprovedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "364eb19e-163f-4ed8-8dd4-e827ed685cf9",
            "sourceColumn": "ApprovedAt",
            "summarizeBy": "none"
          },
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "    DATE(",
              "        YEAR( v_BI_OfferExchanges[ExchangeDate] ),",
              "        MONTH( v_BI_OfferExchanges[ExchangeDate] ),",
              "        DAY( v_BI_OfferExchanges[ExchangeDate] )",
              "    )     "
            ],
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "lineageTag": "3e74c628-95ed-49fa-9d33-1959c0539760",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "2991c59c-0b67-4ca4-afce-2ddabd9ad108",
        "partitions": [
          {
            "name": "v_BI_OfferExchanges-0c50d871-0264-43b1-9bff-746d8d415118",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"igrove.database.windows.net\", \"IGrove\", [CommandTimeout=#duration(0, 0, 2, 0)]),",
                "    dbo_v_BI_OfferExchanges = Source{[Schema=\"dbo\",Item=\"v_BI_OfferExchanges\"]}[Data]",
                "in",
                "    dbo_v_BI_OfferExchanges"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_BI_Offers",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b1e402ca-33c6-496d-8690-9f61a74f121f",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Image",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "679168ea-adab-4a93-a9a5-3d5dafa367f6",
            "sourceColumn": "Image",
            "summarizeBy": "none"
          },
          {
            "name": "OfferName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8358571-1ea9-445f-8eee-b2c8b07a806f",
            "sourceColumn": "OfferName",
            "summarizeBy": "none"
          },
          {
            "name": "Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a92652d2-c8d2-4861-9c77-aea8eed28f4c",
            "sourceColumn": "Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e365e6e2-4d01-4dad-bc37-cdc01b790076",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "AvailableQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3c6152ec-2346-444a-b1fe-1411d2b85fd4",
            "sourceColumn": "AvailableQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "QuantityPerUser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f552267a-db61-4c92-8e2b-a71b02ab7ccd",
            "sourceColumn": "QuantityPerUser",
            "summarizeBy": "sum"
          },
          {
            "name": "StartDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a4302851-c27c-414b-84ec-fc544a436ae5",
            "sourceColumn": "StartDate",
            "summarizeBy": "none"
          },
          {
            "name": "EndDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "749c7d70-34ea-4e33-9a71-09bf0e2ca6b3",
            "sourceColumn": "EndDate",
            "summarizeBy": "none"
          },
          {
            "name": "ShortDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "490d7367-884b-4111-9276-a56d72dfc9c8",
            "sourceColumn": "ShortDescription",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9c1b1d5-efb7-44a6-ba32-6f94febdcd60",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "VendorId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27ac58a6-8593-404c-8c6e-8faadf67294d",
            "sourceColumn": "VendorId",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6745abf4-d9f4-46e2-b3cf-a6e556d3614a",
            "sourceColumn": "CreatedBy",
            "summarizeBy": "sum"
          },
          {
            "name": "CreatorRole",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b45279e6-bbe4-4f86-bf29-b502a58a4e44",
            "sourceColumn": "CreatorRole",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "eb42f661-232e-4991-8a67-97be1453d18b",
            "sourceColumn": "CreatedAt",
            "summarizeBy": "none"
          },
          {
            "name": "UpdatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c6a16c2f-6c0b-441c-83eb-327fb33007bd",
            "sourceColumn": "UpdatedAt",
            "summarizeBy": "none"
          },
          {
            "name": "IsApproved",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "e31e5f29-1139-4145-99df-3837af9158f4",
            "sourceColumn": "IsApproved",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c01ed7ef-da60-4e80-b5cf-83279465b259",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "ApprovedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b4f62cdd-ea5f-4160-a9f4-95a6ffec3c04",
            "sourceColumn": "ApprovedAt",
            "summarizeBy": "none"
          },
          {
            "name": "IsExpired",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "expression": [
              "",
              "    v_BI_Offers[EndDate] <= TODAY()"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "lineageTag": "a43eacd5-663f-4529-bd8f-643eadfeb9b4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ComingSoon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "417b5dd3-8ad7-4d60-bd0a-458846794378",
            "sourceColumn": "ComingSoon",
            "summarizeBy": "none"
          },
          {
            "name": "BuyPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1be1a216-dfec-4802-9dec-0f21e3214a0c",
            "sourceColumn": "BuyPeriod",
            "summarizeBy": "sum"
          },
          {
            "name": "CodeValid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5f208d5d-14f6-44f7-bbb2-d65e0a6285d1",
            "sourceColumn": "CodeValid",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "6ee9cae3-87c7-4ce3-9bfa-150546d0d482",
        "partitions": [
          {
            "name": "v_BI_Offers-93d05c7d-7574-49cf-a2b0-348c5a154a81",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"igrove.database.windows.net\", \"IGrove\", [CommandTimeout=#duration(0, 0, 2, 0)]),",
                "    dbo_v_BI_Offers = Source{[Schema=\"dbo\",Item=\"v_BI_Offers\"]}[Data]",
                "in",
                "    dbo_v_BI_Offers"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_BI_UserCoinFact",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UserId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3a7e69d9-2bdc-4203-ac7a-dac9048bb4bc",
            "sourceColumn": "UserId",
            "summarizeBy": "count"
          },
          {
            "name": "GameId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8e532f1a-905b-4548-8f89-8fb8f9da645f",
            "sourceColumn": "GameId",
            "summarizeBy": "none"
          },
          {
            "name": "Golds",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2c586031-ceac-449f-aabd-2e0e10d0b406",
            "sourceColumn": "Golds",
            "summarizeBy": "sum"
          },
          {
            "name": "Silvers",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c7ca7a3a-51a4-4c19-a42a-5f1efb083f49",
            "sourceColumn": "Silvers",
            "summarizeBy": "sum"
          },
          {
            "name": "CreateDT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "bf8408d2-7d39-4d8f-9408-b296114d8d42",
            "sourceColumn": "CreateDT",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "35f49ee3-4a4f-43c9-9994-ae2553f0b7a3",
        "partitions": [
          {
            "name": "v_BI_UserCoinFact-1310ce0a-9f8b-47ac-9670-ccc26725c576",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"igrove.database.windows.net\", \"IGrove\", [CommandTimeout=#duration(0, 0, 2, 0)]),",
                "    dbo_v_BI_UserCoinFact = Source{[Schema=\"dbo\",Item=\"v_BI_UserCoinFact\"]}[Data]",
                "in",
                "    dbo_v_BI_UserCoinFact"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_BI_Users",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UserId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "982e81c9-c9c1-404c-ab75-d8e60bcc63c5",
            "sourceColumn": "UserId",
            "summarizeBy": "count"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5384f9e-3c07-4309-9991-afd32571031b",
            "sourceColumn": "Phone",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c99b6578-9c3f-4b95-9326-cec5a2ad153a",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Surname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0105c29-2236-4614-8ee0-0e6763b1d140",
            "sourceColumn": "Surname",
            "summarizeBy": "none"
          },
          {
            "name": "Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f08f3305-9995-484f-a285-30b3d54843c3",
            "sourceColumn": "Email",
            "summarizeBy": "none"
          },
          {
            "name": "Image",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c327b6bd-3aee-433c-a1c5-a8bb4155c732",
            "sourceColumn": "Image",
            "summarizeBy": "none"
          },
          {
            "name": "CreateDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "926c07bd-d399-4e4e-b8a5-c81cadcab747",
            "sourceColumn": "CreateDate",
            "summarizeBy": "none"
          },
          {
            "name": "UpdateDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ce896602-618d-42c0-a68a-2d8c84b0f76a",
            "sourceColumn": "UpdateDate",
            "summarizeBy": "none"
          },
          {
            "name": "Iat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "db2e8dc7-ac78-4779-b0da-44f846198085",
            "sourceColumn": "Iat",
            "summarizeBy": "sum"
          },
          {
            "name": "Role",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0621a6be-18b1-449d-ae84-a0b54ddbbac7",
            "sourceColumn": "Role",
            "summarizeBy": "none"
          },
          {
            "name": "Device",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90596e0d-ecbf-41a1-af6d-58c73455bae5",
            "sourceColumn": "Device",
            "summarizeBy": "none"
          },
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "    DATE( ",
              "        YEAR( v_BI_Users[CreateDate] ), ",
              "        MONTH( v_BI_Users[CreateDate] ), ",
              "        DAY( v_BI_Users[CreateDate] )",
              "    )"
            ],
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "lineageTag": "a2115f8d-f5b2-4ce3-912a-5022bdea74db",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Hour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "HOUR( v_BI_Users[CreateDate] )",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "cf49d63d-5405-43cb-86dc-e966a5d4ce88",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "36ea4c8d-98d9-4cde-aba4-872c9f78a48d",
        "partitions": [
          {
            "name": "v_BI_Users-c8999d86-b0a2-4507-9be5-0a3095c1ffa3",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"igrove.database.windows.net\", \"IGrove\", [CommandTimeout=#duration(0, 0, 2, 0)]),",
                "    dbo_v_BI_Users = Source{[Schema=\"dbo\",Item=\"v_BI_Users\"]}[Data]",
                "in",
                "    dbo_v_BI_Users"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_BI_Vendors",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c875394e-de1c-4834-bcf5-3242b28e0581",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a61ced4-fb42-4703-a73a-2b4532e71b18",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e4417fc-421d-4fc2-a003-3de394373dbf",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Image",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "154d9e06-535b-4976-b788-3f69b5844275",
            "sourceColumn": "Image",
            "summarizeBy": "none"
          },
          {
            "name": "SubscriptionId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "765b18fc-152e-4fdd-b620-416de914fdf2",
            "sourceColumn": "SubscriptionId",
            "summarizeBy": "count"
          },
          {
            "name": "CreateDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "038f9cef-4dfd-4359-b258-4bcb6adc21d3",
            "sourceColumn": "CreateDate",
            "summarizeBy": "none"
          },
          {
            "name": "IsActive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "6ea97964-f08f-4190-8a42-1c457a8f71b7",
            "sourceColumn": "IsActive",
            "summarizeBy": "none"
          },
          {
            "name": "ApprovedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "7a635d35-b761-4f52-82c8-b35efdaa403d",
            "sourceColumn": "ApprovedAt",
            "summarizeBy": "none"
          },
          {
            "name": "DeclinedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a3dd2fa9-5aad-47f0-83a5-7fd6e933be0b",
            "sourceColumn": "DeclinedAt",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a0ca888d-a419-4fa4-b77e-fda6a550e86a",
        "partitions": [
          {
            "name": "v_BI_Vendors-e49caf6a-c9fa-40a9-87b1-aa84ce5fcdbc",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"igrove.database.windows.net\", \"IGrove\", [CommandTimeout=#duration(0, 0, 2, 0)]),",
                "    dbo_v_BI_Vendors = Source{[Schema=\"dbo\",Item=\"v_BI_Vendors\"]}[Data]",
                "in",
                "    dbo_v_BI_Vendors"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_BI_GameCoinStatistics",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "GameId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fe68afbd-3aa5-44b2-b118-1866625287c9",
            "sourceColumn": "GameId",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7ce6c458-2576-40f8-9c61-c706fbdfc817",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1e0d1c81-3410-4136-ab5b-5c2f685fdbf8",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b11d6eb5-0c53-4995-868c-5624b9129331",
            "sourceColumn": "Day",
            "summarizeBy": "sum"
          },
          {
            "name": "Hour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3dc961a8-d3a6-429e-baa7-24e113be7b89",
            "sourceColumn": "Hour",
            "summarizeBy": "sum"
          },
          {
            "name": "Coins",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "04959545-1dc0-439d-a62e-f8b589d6d39b",
            "sourceColumn": "Coins",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "c3337611-f22f-4242-92da-5b43ce72267c",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "90458234-55aa-4e29-be8a-a9ba3ec670ee",
        "partitions": [
          {
            "name": "v_BI_GameCoinStatistics-3e604555-69c9-4b6c-a76e-a01a02815aa0",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"igrove.database.windows.net\", \"IGrove\", [CommandTimeout=#duration(0, 0, 3, 0)]),",
                "    dbo_v_BI_GameCoinStatistics = Source{[Schema=\"dbo\",Item=\"v_BI_GameCoinStatistics\"]}[Data]",
                "in",
                "    dbo_v_BI_GameCoinStatistics"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_BI_Calendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DWDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isKey": true,
            "lineageTag": "0062488a-6a39-4460-839b-b47d75d67d2b",
            "sourceColumn": "DWDateKey",
            "summarizeBy": "none"
          },
          {
            "name": "DayDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ef77ba8b-b1c6-4f3d-84fc-6bb468ba031f",
            "sourceColumn": "DayDate",
            "summarizeBy": "sum"
          },
          {
            "name": "DayOfWeekName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "32354e4c-2ca3-4852-bba7-4e5c0dbe897e",
            "sourceColumn": "DayOfWeekName",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f5f87499-e57b-440b-8ac6-4b18fbe3f3bb",
            "sourceColumn": "WeekNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d22458b4-e92b-4578-9e2f-d6a953e72d7a",
            "sourceColumn": "MonthNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81226a80-968f-4fee-a8d1-cc1b706e62da",
            "sourceColumn": "MonthName",
            "summarizeBy": "none"
          },
          {
            "name": "MonthShortName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "013e5c66-d4b2-44ac-9502-606e21b1a10e",
            "sourceColumn": "MonthShortName",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "66a39fac-85b4-4318-a6db-843dadfa9da7",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "QuarterNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c0ddd13-adea-44fd-ab5e-28edbab3c043",
            "sourceColumn": "QuarterNumber",
            "summarizeBy": "none"
          },
          {
            "name": "QuarterName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e59fbd4-8902-42ea-bb4f-59542bdb9a2c",
            "sourceColumn": "QuarterName",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "357f76cc-ebb4-446f-a7e9-bf2bb4fa7156",
        "partitions": [
          {
            "name": "v_BI_Calendar-f276df10-e075-40d0-a5e8-4c06d79a4312",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"igrove.database.windows.net\", \"IGrove\", [CommandTimeout=#duration(0, 0, 2, 0)]),",
                "    dbo_v_BI_Calendar = Source{[Schema=\"dbo\",Item=\"v_BI_Calendar\"]}[Data]",
                "in",
                "    dbo_v_BI_Calendar"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_BI_Games",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "89f0c8cf-81f4-4b36-9db5-353bf6a4ce03",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c38ac57-7767-4522-beb1-9321078678e9",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Image",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78e76464-c711-4483-a04c-551d167c565f",
            "sourceColumn": "Image",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42081a1c-3f8d-4157-a69c-c4d6826f8813",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Coefficient",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ff8d6f70-0ea7-42c3-8aaf-6e7bf1a6ed7b",
            "sourceColumn": "Coefficient",
            "summarizeBy": "sum"
          },
          {
            "name": "CreateDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "df66a7ed-e23a-45a9-9574-205cf22de155",
            "sourceColumn": "CreateDate",
            "summarizeBy": "none"
          },
          {
            "name": "ApplicationVersion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c9d4bb9-34ba-4aa7-a498-c8510511cdef",
            "sourceColumn": "ApplicationVersion",
            "summarizeBy": "none"
          },
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "    DATE( ",
              "        YEAR( v_BI_Games[CreateDate] ), ",
              "        MONTH( v_BI_Games[CreateDate] ), ",
              "        DAY( v_BI_Games[CreateDate] )",
              "    )"
            ],
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "lineageTag": "40e0dc95-acaa-476e-8c3c-e1d27f0546ac",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "e4688236-79d5-4a1d-bc68-60da08d0086d",
        "partitions": [
          {
            "name": "v_BI_Games-fee5325b-15ba-4f21-920e-9da32f55218b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"igrove.database.windows.net\", \"IGrove\", [CommandTimeout=#duration(0, 0, 2, 0)]),",
                "    dbo_v_BI_Games = Source{[Schema=\"dbo\",Item=\"v_BI_Games\"]}[Data]",
                "in",
                "    dbo_v_BI_Games"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Metrics",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0e6978869d25488cbf31f660330b4dc8"
          }
        ],
        "columns": [
          {
            "name": "Metrics Placeholder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0d1e9269-3cd0-4e22-bc22-36f2e14d97ff",
            "sourceColumn": "[Metrics Placeholder]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6336d0fe-4249-4482-b465-91ad3e7785fd",
        "measures": [
          {
            "name": "# Registrations",
            "expression": [
              "",
              "var x =",
              "CALCULATE(    ",
              "    DISTINCTCOUNT( v_BI_Users[UserId] ),",
              "    USERELATIONSHIP( 'Calendar'[Date], v_BI_Users[DateKey] )",
              ")",
              "",
              "var res = x * 1",
              "RETURN",
              "",
              "res"
            ],
            "formatString": "#,0",
            "lineageTag": "0d422ace-5c3d-4931-9d08-84174f6c8371"
          },
          {
            "name": "# Games",
            "expression": [
              "",
              "    DISTINCTCOUNT( v_BI_Games[Id] )",
              "    "
            ],
            "formatString": "0",
            "lineageTag": "1e6881da-b80a-4805-b237-67cad4f16792"
          },
          {
            "name": "# Active Users",
            "expression": [
              "",
              "var x = DISTINCTCOUNT( v_BI_UserCoinFact[UserId] )",
              "var res = x * 1",
              "RETURN",
              "",
              "res"
            ],
            "formatString": "#,0",
            "lineageTag": "ff7a3af2-3aea-43b0-a959-1510fbc0a63f"
          },
          {
            "name": "Avg. Vouchers Per User",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    "
            ],
            "lineageTag": "b6e054c7-f1db-4e23-be6f-f3c40a6ed7d0"
          },
          {
            "name": "Earliest Play Date",
            "expression": [
              "",
              "MIN( v_BI_Games[DateKey] )"
            ],
            "formatString": "General Date",
            "lineageTag": "9b4446cf-6e91-45c5-9e0f-09eb993f454b"
          },
          {
            "name": "# Offers",
            "expression": [
              "",
              "DISTINCTCOUNT( v_BI_OfferDetails[OfferId] )"
            ],
            "formatString": "0",
            "lineageTag": "923302f4-b299-495a-bbdc-a1ae71a30b26"
          },
          {
            "name": "Gold",
            "expression": [
              "",
              "var x =",
              "SUM( v_BI_UserCoinFact[Golds] )",
              "RETURN",
              "x * 1"
            ],
            "formatString": "#,0",
            "lineageTag": "9ec6257f-576b-4aeb-82a4-f08e211f7fd9"
          },
          {
            "name": "# Voucher Users",
            "expression": [
              "",
              "var x =    ",
              "    CALCULATE(    ",
              "        DISTINCTCOUNT( v_BI_OfferExchanges[UserId] ),",
              "        USERELATIONSHIP( 'Calendar'[Date], v_BI_OfferExchanges[DateKey] )",
              "    ) ",
              "RETURN x * 1    "
            ],
            "formatString": "#,0",
            "lineageTag": "8e95bdb5-dcea-4cac-8544-a49cfc36b7e4"
          },
          {
            "name": "Silver",
            "expression": [
              "",
              "VAR x =",
              "SUM( v_BI_UserCoinFact[Silvers] )",
              "RETURN",
              "x * 1"
            ],
            "formatString": "#,0",
            "lineageTag": "d6c3d21f-2ec9-435d-b1f5-7ffe90e57d14"
          },
          {
            "name": "# Voucher Exchanges",
            "expression": [
              "",
              "VAR x =",
              "CALCULATE(    ",
              "    COUNT( v_BI_OfferExchanges[ExchangeDate] ),",
              "    USERELATIONSHIP( 'Calendar'[Date], v_BI_OfferExchanges[DateKey] )",
              ") ",
              "RETURN",
              "x * 1     "
            ],
            "formatString": "#,0",
            "lineageTag": "ba7f2043-5583-49cb-ba05-b7e612d0516a"
          },
          {
            "name": "# Voucher Activations",
            "expression": [
              "",
              "COUNT( v_BI_OfferExchanges[ActivationDate] )"
            ],
            "formatString": "0",
            "lineageTag": "8f17e3b4-68ed-4039-867a-bed015e23b43"
          },
          {
            "name": "Avg. Reg 2 Exchange ( Minutes )",
            "expression": [
              "",
              "",
              "VAR RegInfo =\t",
              "\tSUMMARIZE(",
              "\t\tv_BI_OfferExchanges,",
              "\t\tv_BI_OfferExchanges[UserId],",
              "\t\tv_BI_Users[DateKey]",
              "\t)",
              "",
              "VAR ExchangeInfo =",
              "\tADDCOLUMNS(",
              "\t\tRegInfo,",
              "\t\t\"@FED\", DATEVALUE( CALCULATE( MIN( v_BI_OfferExchanges[ExchangeDate] ) ) )",
              "\t)\t",
              "",
              "VAR MinDiff =",
              "\tADDCOLUMNS(",
              "\t\tExchangeInfo,",
              "\t\t\"MinDiff\",",
              "\t\tDATEDIFF( [DateKey], [@FED], MINUTE )",
              "\t)\t",
              "",
              "VAR DayDiff =",
              "    ADDCOLUMNS(",
              "\t\tMinDiff,",
              "\t\t\"DayDiff\",",
              "\t\t[MinDiff] / 1440",
              "\t)",
              "",
              "VAR Result =\t",
              "\tAVERAGEX(",
              "\t\tMinDiff,",
              "\t\t[MinDiff]",
              "\t)",
              "",
              "// VAR Result =\t",
              "// \tAVERAGEX(",
              "// \t\tDayDiff,",
              "// \t\t[DayDiff]",
              "// \t)",
              "",
              "RETURN",
              "\tResult"
            ],
            "formatString": "#,0",
            "lineageTag": "b4d6251d-f3e6-49a3-975e-eb1378e08f73"
          },
          {
            "name": "Avg. Exchange 2 Activation ( Minutes )",
            "expression": [
              "",
              "",
              "VAR FilteredOfferExchanges =",
              "\tFILTER(",
              "\t\tv_BI_OfferExchanges,",
              "\t\tv_BI_OfferExchanges[IsActivated] = TRUE()",
              "\t)",
              "",
              "VAR MinuteDiff =",
              "\tADDCOLUMNS(\t",
              "\t\tFilteredOfferExchanges,",
              "\t\t\"DDiff\", ",
              "\t\tDATEDIFF( [ExchangeDate], [ActivationDate], MINUTE )",
              "\t)",
              "",
              "VAR DayDiff =",
              "\tADDCOLUMNS(\t",
              "\t\tFilteredOfferExchanges,",
              "\t\t\"DDiff\", ",
              "\t\tDATEDIFF( [ExchangeDate], [ActivationDate], DAY )",
              "\t)",
              "",
              "VAR Result = ",
              "\tAVERAGEX(\t",
              "\t\tMinuteDiff,",
              "\t\t[DDiff]",
              "\t)",
              "\t\t",
              "RETURN",
              "    Result"
            ],
            "formatString": "0",
            "lineageTag": "a8fcb53e-0ca0-4ec0-a601-d5d4091cff40"
          },
          {
            "name": "Avg. Time Between Registrations",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "\tVAR FiltUsers =",
              "        SUMMARIZE(",
              "            v_BI_Users,",
              "            v_BI_Users[UserId],",
              "            v_BI_Users[CreateDate] ",
              "        )",
              "",
              "\tVAR FiltUsersRanked =",
              "\t\tADDCOLUMNS(\t",
              "\t\t\tFiltUsers,",
              "\t\t\t\"Rank\",",
              "\t\t\tRANKX(",
              "\t\t\t\tFiltUsers,",
              "\t\t\t\t[CreateDate],,ASC,DENSE",
              "\t\t\t) - 1",
              "\t\t)",
              "\t\t",
              "\tVAR PrevFiltUsersRanked =",
              "\t\tADDCOLUMNS(\t",
              "\t\t\tFiltUsers,",
              "\t\t\t\"Rank\",",
              "\t\t\tRANKX(",
              "\t\t\t\tFiltUsers,",
              "\t\t\t\t[CreateDate],,ASC,DENSE",
              "\t\t\t)",
              "\t\t)",
              "\t",
              "\tVAR Renamed_FiltUsersRanked =",
              "\t\tSELECTCOLUMNS(",
              "\t\t\tFiltUsersRanked,",
              "\t\t\t\"FiltUserId\", [UserId],",
              "\t\t\t\"FiltUserRegDate\",[CreateDate],",
              "\t\t\t\"Rank\", [Rank]",
              "\t\t)",
              "\t",
              "\tVAR Renamed_PrevFiltUsersRanked =",
              "\t\tSELECTCOLUMNS(",
              "\t\t\tPrevFiltUsersRanked,",
              "\t\t\t\"PrevFiltUserId\", [UserId],",
              "\t\t\t\"PrevFiltUserRegDate\",[CreateDate],",
              "\t\t\t\"Rank\", [Rank]",
              "\t\t)",
              "",
              "\tVAR JoinedFiltUsers =",
              "\t\tNATURALLEFTOUTERJOIN(",
              "\t\t\tRenamed_FiltUsersRanked,",
              "\t\t\tRenamed_PrevFiltUsersRanked",
              "\t\t)",
              "",
              "\tVAR FilteredUsers = ",
              "\t\tFILTER(",
              "\t\t\tJoinedFiltUsers,",
              "\t\t\t[Rank] <> 0",
              "\t\t)",
              "\t",
              "\tVAR SecondDiff = ",
              "\t\tADDCOLUMNS(",
              "\t\t\tFilteredUsers,",
              "\t\t\t\"SecondDiff\",",
              "\t\t\tDATEDIFF( [PrevFiltUserRegDate], [FiltUserRegDate], SECOND )",
              "\t\t)",
              "\t",
              "\tVAR Result =",
              "\t\tAVERAGEX(",
              "\t\t\tSecondDiff,",
              "\t\t\t[SecondDiff]",
              "\t\t)",
              "\t",
              "\tRETURN\t",
              "\t\tResult "
            ],
            "lineageTag": "b7108119-1b89-472c-988d-30a00656d4ea"
          },
          {
            "name": "Avg. Time Per Registration",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR NumberOfDays = ",
              "    COUNTROWS( ",
              "        VALUES( 'Calendar'[Date] ) ",
              "    )",
              "VAR DaysInSecs = NumberOfDays * 86400",
              "VAR NumberOfHours =",
              "    COUNTROWS(",
              "        DISTINCT( 'Time'[Hour] )",
              "    )",
              "VAR HoursInSecs = NumberOfHours * 3600    ",
              "VAR NumberOfUserRegs = [# Registrations]",
              "VAR SelectedTime = ",
              "    DaysInSecs * (  NumberOfHours / 24 )",
              "RETURN",
              "    DIVIDE( SelectedTime, NumberOfUserRegs )"
            ],
            "lineageTag": "56831b8a-f2c5-4862-9104-5262c1ced1eb"
          },
          {
            "name": "# of Hours",
            "expression": [
              "",
              "COUNTROWS( 'Time' )"
            ],
            "formatString": "0",
            "lineageTag": "1753b195-196b-4090-9339-85d848246b2b"
          },
          {
            "name": "Stickiness %",
            "expression": [
              "",
              "VAR SelectedMonth = VALUES( 'Calendar'[Month Number] )",
              "VAR DailyActive = [# Active Users]",
              "VAR MonthlyActive = ",
              "    CALCULATE(",
              "        [# Active Users],",
              "        REMOVEFILTERS( 'Calendar' ),",
              "        SelectedMonth",
              "    )  ",
              "VAR Result = ",
              "    DIVIDE( DailyActive, MonthlyActive )",
              "RETURN ",
              "    Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7f60399c-ae7b-4e23-8e0c-a75ea589dc14"
          },
          {
            "name": "# Users By Cohort",
            "expression": [
              "",
              "",
              "VAR MonthCohortCustomers = VALUES( v_BI_UserCoinFact[UserId] )",
              "VAR MonthAfter = SELECTEDVALUE( 'Months After'[Value] )",
              "RETURN",
              "CALCULATE(",
              "    [# Active Users],",
              "    MonthCohortCustomers,",
              "    DATEADD( 'Calendar'[Date], MonthAfter, MONTH )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f05f9809-0a11-4ff7-a3b3-30a1360e916d"
          },
          {
            "name": "# Users By Week Cohort",
            "expression": [
              "",
              "",
              "VAR CurrYear = SELECTEDVALUE( 'Calendar'[Year Number] )",
              "VAR CurrWeek = SELECTEDVALUE( 'Calendar'[Week Number] )",
              "VAR WeekAfter = SELECTEDVALUE( 'Weeks After'[Value] )",
              "VAR Result =",
              "    IF(",
              "        NOT ISEMPTY( 'Calendar' ),",
              "        CALCULATE(",
              "            [# Active Users],",
              "            'Calendar'[Year Number] = CurrYear,",
              "            'Calendar'[Week Number] = ( CurrWeek + WeekAfter ),",
              "            TREATAS( VALUES( v_BI_Users[UserId] ), v_BI_UserCoinFact[UserId] ),",
              "            REMOVEFILTERS( 'Calendar'[Year Week] )",
              "        )",
              "    )",
              "RETURN    ",
              "    Result",
              ""
            ],
            "formatString": "0",
            "lineageTag": "a5a75eef-e1cb-4e24-968a-42e713b0f73c"
          },
          {
            "name": "User Retention % By Week Cohort",
            "expression": [
              "",
              "",
              "VAR CohortWeekUsers = VALUES( v_BI_Users[UserId] )",
              "VAR NumberOfCohortWeekUsers = COUNTROWS( CohortWeekUsers )",
              "VAR CurrYear = SELECTEDVALUE( 'Calendar'[Year Number] )",
              "VAR CurrWeek = SELECTEDVALUE( 'Calendar'[Week Number] )",
              "VAR WeekAfter = SELECTEDVALUE( 'Weeks After'[Value] )",
              "VAR NumberOfUserByCohort =",
              "    IF(",
              "        NOT ISEMPTY( 'Calendar' ),",
              "        CALCULATE(",
              "            [# Active Users],",
              "            'Calendar'[Year Number] = CurrYear,",
              "            'Calendar'[Week Number] = ( CurrWeek + WeekAfter ),",
              "            TREATAS( VALUES( v_BI_Users[UserId] ), v_BI_UserCoinFact[UserId] ),",
              "            REMOVEFILTERS( 'Calendar'[Year Week] )",
              "        )",
              "    )",
              "VAR Result = ",
              "    DIVIDE( NumberOfUserByCohort, NumberOfCohortWeekUsers )",
              "RETURN",
              "    Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b0a94fb4-ddad-4982-b432-109ec5102ed2"
          },
          {
            "name": "User Retention TEST",
            "expression": [
              "",
              "",
              "VAR CohortWeekUsers = VALUES( v_BI_Users[UserId] )",
              "VAR NumberOfCohortWeekUsers = COUNTROWS( CohortWeekUsers )",
              "VAR CurrYear = SELECTEDVALUE( 'Calendar'[Year Number] )",
              "VAR CurrWeek = SELECTEDVALUE( 'Calendar'[Week Number] )",
              "VAR WeekAfter = SELECTEDVALUE( 'Weeks After'[Value] )",
              "VAR NumberOfUserByCohort =",
              "    IF(",
              "        NOT ISEMPTY( 'Calendar' ),",
              "        CALCULATE(",
              "            [# Active Users],",
              "            'Calendar'[Year Number] = CurrYear,",
              "            'Calendar'[Week Number] = ( CurrWeek + WeekAfter ),",
              "            TREATAS( VALUES( v_BI_Users[UserId] ), v_BI_UserCoinFact[UserId] ),",
              "            REMOVEFILTERS( 'Calendar'[Year Week] )",
              "        )",
              "    )",
              "VAR Result = ",
              "    DIVIDE( NumberOfUserByCohort, NumberOfCohortWeekUsers )",
              "RETURN",
              "    NumberOfCohortWeekUsers"
            ],
            "formatString": "0",
            "lineageTag": "28041d54-ecd3-42ca-b8eb-8f3b28c087d6"
          },
          {
            "name": "Gold Retention % By Week Cohort",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR CohortWeekUsers = VALUES( v_BI_Users[UserId] )",
              "VAR NumberOfCohortWeekUsers = COUNTROWS( CohortWeekUsers )",
              "VAR CurrYear = SELECTEDVALUE( 'Calendar'[Year Number] )",
              "VAR CurrWeek = SELECTEDVALUE( 'Calendar'[Week Number] )",
              "VAR WeekAfter = SELECTEDVALUE( 'Weeks After'[Value] )",
              "VAR GoldRetentionByCohort =",
              "    IF(",
              "        NOT ISEMPTY( 'Calendar' ),",
              "        CALCULATE(",
              "            [Gold],",
              "            'Calendar'[Year Number] = CurrYear,",
              "            'Calendar'[Week Number] = ( CurrWeek + WeekAfter ),",
              "            TREATAS( VALUES( v_BI_Users[UserId] ), v_BI_UserCoinFact[UserId] ),",
              "            REMOVEFILTERS( 'Calendar'[Year Week] )",
              "        )",
              "    )",
              "VAR Result = ",
              "    DIVIDE( GoldRetentionByCohort, NumberOfCohortWeekUsers )",
              "RETURN",
              "    Result"
            ],
            "lineageTag": "a376019b-6a7b-4c36-9546-847c88183856"
          },
          {
            "name": "Gold By Cohort",
            "expression": [
              "",
              "",
              "VAR CurrYear = SELECTEDVALUE( 'Calendar'[Year Number] )",
              "VAR CurrWeek = SELECTEDVALUE( 'Calendar'[Week Number] )",
              "VAR WeekAfter = SELECTEDVALUE( 'Weeks After'[Value] )",
              "VAR Result =",
              "    IF(",
              "        NOT ISEMPTY( 'Calendar' ),",
              "        CALCULATE(",
              "            [Gold],",
              "            'Calendar'[Year Number] = CurrYear,",
              "            'Calendar'[Week Number] = ( CurrWeek + WeekAfter ),",
              "            TREATAS( VALUES( v_BI_Users[UserId] ), v_BI_UserCoinFact[UserId] ),",
              "            REMOVEFILTERS( 'Calendar'[Year Week] )",
              "        )",
              "    )",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,0",
            "lineageTag": "0e3eb2ca-d488-484a-975b-2bb2edad81dc"
          },
          {
            "name": "Voucher Exchanges By Cohort",
            "expression": [
              "",
              "",
              "VAR CurrYear = SELECTEDVALUE( 'Calendar'[Year Number] )",
              "VAR CurrWeek = SELECTEDVALUE( 'Calendar'[Week Number] )",
              "VAR WeekAfter = SELECTEDVALUE( 'Weeks After'[Value] )",
              "VAR Result =",
              "    IF(",
              "        NOT ISEMPTY( 'Calendar' ),",
              "        CALCULATE(",
              "            [# Voucher Exchanges],",
              "            'Calendar'[Year Number] = CurrYear,",
              "            'Calendar'[Week Number] = ( CurrWeek + WeekAfter ),",
              "            TREATAS( VALUES( v_BI_Users[UserId] ), v_BI_OfferExchanges[UserId] ),",
              "            REMOVEFILTERS( 'Calendar'[Year Week] )",
              "        )",
              "    )",
              "RETURN",
              "    Result"
            ],
            "formatString": "0",
            "lineageTag": "64b14d17-2247-4b31-b106-9ebb86efa0f7"
          },
          {
            "name": "# Issues",
            "expression": [
              "",
              "VAR calc =     ",
              "    CALCULATE(",
              "        COUNT(",
              "            v_BI_OfferCheck[CheckDescription]",
              "        ),",
              "        KEEPFILTERS( v_BI_OfferCheck[CheckDescription] <> \" \" )",
              "    )",
              "RETURN",
              "    IF(",
              "        ISBLANK( calc ),",
              "        0,",
              "        calc",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "2b3cad43-0285-47b0-953e-e5cb053d815d"
          },
          {
            "name": "Stickiness % ( Card )",
            "expression": [
              "",
              "",
              "VAR DailyActive =",
              "\tADDCOLUMNS(\t",
              "\t\tSUMMARIZE(",
              "\t\t\t'Calendar',",
              "\t\t\t'Calendar'[Date],",
              "\t\t\t'Calendar'[Month Number]",
              "\t\t),\t",
              "\t\t\"@Daily Active\", [# Active Users],",
              "\t\t\"@Monthly Active\",",
              "\t\tCALCULATE(",
              "\t\t\t[# Active Users],",
              "\t\t\tREMOVEFILTERS( 'Calendar'[Date] )",
              "\t\t)\t",
              "\t\t\t\t",
              "\t)\t",
              "VAR DailyActiveFiltered =",
              "\tFILTER(",
              "\t\tDailyActive,",
              "\t\t[@Daily Active] <> BLANK()",
              "\t)",
              "VAR StickinessAdded =",
              "\tADDCOLUMNS(",
              "\t\tDailyActiveFiltered,",
              "\t\t\"@Stickiness\",",
              "\t\tDIVIDE(",
              "\t\t\t[@Daily Active],",
              "\t\t\t[@Monthly Active]",
              "\t\t)",
              "\t)\t",
              "VAR Result = ",
              "\tAVERAGEX(",
              "\t\tStickinessAdded,",
              "\t\t[@Stickiness]",
              "\t)\t",
              "RETURN\t",
              "\tResult"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "79c4cd48-70ba-470e-9a4d-598e0ff74c28"
          },
          {
            "name": "OffersDate",
            "expression": [
              "",
              "    CALCULATE(",
              "        SELECTEDVALUE( v_BI_OfferExchanges[DateKey] ),",
              "        USERELATIONSHIP( 'Calendar'[Date], v_BI_OfferExchanges[DateKey] )",
              "    )    ",
              ""
            ],
            "formatString": "General Date",
            "lineageTag": "d7aacae9-7d6c-4755-8842-d9f68621d7a3"
          },
          {
            "name": "OffersCode",
            "expression": [
              "",
              "    CALCULATE(",
              "        SELECTEDVALUE( v_BI_OfferExchanges[Code] ),",
              "        USERELATIONSHIP( 'Calendar'[Date], v_BI_OfferExchanges[DateKey] )",
              "    )"
            ],
            "lineageTag": "7a938259-bf83-4bea-afdc-7c4bc0e00931"
          },
          {
            "name": "# Available Vouchers",
            "expression": [
              "",
              "",
              "VAR CurrDate = TODAY()      ",
              "VAR Result =   ",
              "    CALCULATE(",
              "        COUNT( v_BI_OfferCodes[Code] ),",
              "        v_BI_OfferCodes[IsShared] = FALSE(),",
              "        v_BI_Offers[IsExpired] = FALSE()    ",
              "    )",
              "RETURN",
              "    IF(",
              "        ISBLANK( Result ),",
              "        0,",
              "        Result",
              "    )    "
            ],
            "formatString": "#,0",
            "lineageTag": "861c2b62-250d-4786-83bc-834b3d42c101"
          },
          {
            "name": "# Vouchers",
            "expression": [
              "",
              "    COUNT( v_BI_OfferCodes[Code] )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "4a5e1d29-d8f3-4960-b83a-5a3cde363e8e"
          }
        ],
        "partitions": [
          {
            "name": "Metrics-961a1ed5-527d-455e-934b-d19d7c51f100",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "DATATABLE(",
                "    \"Metrics Placeholder\",",
                "    STRING,",
                "    {",
                "       { \" \" } ",
                "    }",
                ")       "
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bb3fd2837e084024bcc38ecd6d37d847"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "0d5507e4-9d8b-477d-b93b-c7fb16d96aa5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "076fd07a-b1e2-4886-8e30-db0e182edfc7",
            "sourceColumn": "[Year Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "65fdfc1c-0263-4c0e-8552-0bd8d4e612a9",
            "sourceColumn": "[Month Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Name Long",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "85a9992c-e3d0-465c-a6f7-648f4c05f518",
            "sourceColumn": "[Month Name Long]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ea7d3657-7eac-4381-88e3-c800a7ef76c8",
            "sortByColumn": "Month Number",
            "sourceColumn": "[Month Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "18ff2830-6dc7-4370-b2e7-bf5974d1c68d",
            "sourceColumn": "[Quarter Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3be3e211-6584-477c-92f4-2d6eac5bdf46",
            "sourceColumn": "[Quarter Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "26e9ab2c-2090-4f68-a804-87cadc57f755",
            "sourceColumn": "[Week Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YearWeek ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f003b57b-a536-4a87-906d-a13477840d4f",
            "sourceColumn": "[YearWeek ID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Weekday Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d4f03a06-f779-46b7-9328-739021b32e0f",
            "sourceColumn": "[Weekday Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Weekday Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "88bba538-ff73-447d-a9f3-590a47fc437d",
            "sourceColumn": "[Weekday Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Weekday Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3ae2c245-bf56-4624-a724-2f69b7782a82",
            "sourceColumn": "[Weekday Type]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "21ab7677-306f-4803-b65d-83b009450227",
            "sourceColumn": "[Day Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5e4de759-e2a9-40f6-8295-f7303c5bf6b2",
            "sourceColumn": "[Year Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "cc0e6a10-a86e-4d5d-9988-ea1d5865be7f",
        "measures": [
          {
            "name": "Expired ?",
            "expression": [
              "",
              "VAR ",
              ""
            ],
            "lineageTag": "c312c182-7a34-4693-8da4-90518ea1c220"
          }
        ],
        "partitions": [
          {
            "name": "Calendar-31a6080b-02d5-4cc7-9a40-788e0e7c7a70",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "",
                "VAR StartDate = MIN( v_BI_Users[DateKey] )",
                "VAR EndDate = TODAY() ",
                "",
                "VAR BaseCalendar = ",
                "    CALENDAR( StartDate, EndDate )",
                "RETURN",
                "    GENERATE(",
                "       BaseCalendar, ",
                "       VAR BaseDate = [Date]",
                "       VAR YearNumber = YEAR( BaseDate )",
                "       VAR MonthNumber = MONTH( BaseDate )",
                "       VAR DayNumber = DAY( BaseDate )",
                "       VAR MonthNameLong = FORMAT( BaseDate, \"mmmm\" )",
                "       VAR MonthNameShort = FORMAT( BaseDate, \"mmm\" )",
                "       VAR QuarterNumber = QUARTER( BaseDate )",
                "       VAR QuarterName = \"Q\" & QuarterNumber & \" - \" &  YearNumber",
                "       VAR WeekNumber = WEEKNUM( BaseDate, 2 )",
                "       VAR YearWeekID = YearNumber * 100 + WeekNumber",
                "       VAR YearWeek = YearNumber & \" - \" & WeekNumber",
                "       VAR WeekDayNumber = WEEKDAY( BaseDate, 2 ) ",
                "       VAR WeekDayName = ",
                "            SWITCH(",
                "                WeekDayNumber,",
                "                1, \"Monday\",",
                "                2, \"Tuesday\",",
                "                3, \"Wednesday\",",
                "                4, \"Thursday\",",
                "                5, \"Friday\",",
                "                6, \"Saturday\",",
                "                7, \"Sunday\"",
                "            )    ",
                "       VAR WeekdayType = ",
                "            SWITCH(",
                "                TRUE(),",
                "                WeekDayNumber <= 5, \"Weekday\",",
                "                WeekDayNumber > 5, \"Weekend\"",
                "            )",
                "       RETURN ROW (",
                "           \"Year Number\", YearNumber,",
                "           \"Month Number\", MonthNumber,",
                "           \"Day Number\", DayNumber,",
                "           \"Month Name Long\", MonthNameLong,",
                "           \"Month Name\", MonthNameShort,",
                "           \"Quarter Number\", QuarterNumber,",
                "           \"Quarter Name\", QuarterName,",
                "           \"Week Number\", WeekNumber,",
                "           \"YearWeek ID\", YearWeekID,",
                "           \"Year Week\", YearWeek,",
                "           \"Weekday Number\", WeekDayNumber,",
                "           \"Weekday Name\", WeekDayName,",
                "           \"Weekday Type\", WeekdayType",
                "       )",
                "    )"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Time",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "528ab22b6e2d4ee790b6f32f16f709ba"
          }
        ],
        "columns": [
          {
            "name": "Hour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "90d13f85-5d86-4565-abe3-efa5977c5527",
            "sourceColumn": "[Hour]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "513c9557-bb9d-4d26-9509-ad9b5f38d1c5",
        "partitions": [
          {
            "name": "Time-a5453cae-0eaf-40a2-b945-ede1df6f57ca",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SELECTCOLUMNS( GENERATESERIES( 0, 23, 1 ), \"Hour\", [Value] )",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Months After",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1a51ef07c46b4987b70f8eabbfa9b9b1"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a69145fb-e250-4a1f-aa89-da0740decfe6",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "b89915de-d2cf-4ec0-83fe-5e628bb7d10b",
        "partitions": [
          {
            "name": "Months After-35318749-a80d-4c04-b6f2-3af670bc98bf",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "    GENERATESERIES( 0, 12, 1 ) "
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Weeks After",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "9617ba8780b1471b932fb40c0305d700"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ad9c4ad8-05f7-4a1d-93d4-c452cfb2cb68",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2764aa6e-1494-4d27-a7ad-5bfaecf7b958",
        "partitions": [
          {
            "name": "Weeks After-b502fd18-87ca-4f23-b98e-9a23d5072c7d",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "    GENERATESERIES( 0, 52, 1 ) "
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Trend",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b312fc8b79224234afb46caae824cadc"
          }
        ],
        "columns": [
          {
            "name": "Trend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "43e95386-7cc6-4668-8e44-82382f2a7ddc",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Trend Fields"
                }
              ]
            },
            "sortByColumn": "Trend Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Trend Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "116c26c1-66ce-474d-a299-6f0bb855ac4e",
            "sortByColumn": "Trend Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Trend Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "881beda7-acff-4def-9b1d-06b597ba5ad1",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "7ae40a2d-70ba-46bc-ac29-97c0c2c8290e",
        "partitions": [
          {
            "name": "Trend-ac2bdab0-a31c-402a-b60e-a5b9d42e6ec6",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"# Registrations\", NAMEOF('Metrics'[# Registrations]), 0),",
                "    (\"# Active Users\", NAMEOF('Metrics'[# Active Users]), 1),",
                "    (\"Stickiness %\", NAMEOF('Metrics'[Stickiness %]), 2),",
                "    (\"# Offer Exchanges\", NAMEOF('Metrics'[# Voucher Exchanges]), 3),",
                "    (\"Gold\", NAMEOF('Metrics'[Gold]), 4),",
                "    (\"Silver\", NAMEOF('Metrics'[Silver]), 5)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}